### ISSUE TITLE
Run configuration broken for Java Platform Module System (JPMS)

### ISSUE THREAD

**Issue by fireandfuel** [eclipse/buildship#1002]
### Expected Behavior

When the project is configured for modules I expect Buildship to set up the run configuration properly with the Gradle dependencies at the modulepath parameter instead of classpath parameter.

### Current Behavior

When the project is configured for modules the Gradle dependencies are included at the classpath parameter instead of the modulepath parameter. It results in that the JRE is not able to find the modules when launching the run configuration:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module org.apache.logging.log4j not found, required by TestGradleModular
```

The current run configuration looks like this:
`C:\Program Files\OpenJDK\jdk-11.0.6+10\bin\javaw.exe -Dfile.encoding=UTF-8 -p "C:\Users\user\workspaces\test\TestGradleModular\bin\main" -classpath "C:\Users\user\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.11.2\6c2fb3f5b7cd27504726aef1b674b542a0c9cf53\log4j-core-2.11.2.jar;C:\Users\user\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.11.2\f5e9a2ffca496057d6891a3de65128efc636e26e\log4j-api-2.11.2.jar" -m TestGradleModular/TestGradleModular.TestMe`

At the run configuration at the tab 'Java Build Path > Libraries' looks like this:

```
Modulepath
|> JRE System Library [JavaSE-11]
|> Project and External Dependencies
 |> Access rules: No rules defined
 |> External annotations: (None)
 |> Native library location: No
 |> Is modular
 |> log4j-core-2.11.2.jar - C:\Users\user\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-core\2.11.2\6c2fb3f5b7cd27504726aef1b674b542a0c9cf53\log4j-core-2.11.2.jar
  |> Is modular - non modifiable
  |> Access rules: (no restrictions) - non modifiable
  |> Visible only for the test sources: No - non modifiable
 |> log4j-api-2.11.2.jar - C:\Users\user\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.11.2\f5e9a2ffca496057d6891a3de65128efc636e26e\log4j-api-2.11.2.jar
  |> Is modular - non modifiable
  |> Access rules: (no restrictions) - non modifiable
  |> Visible only for the test sources: No - non modifiable
Classpath
```

### Context

I started to modularize a Java 11 Gradle project using JPMS modules. For test purposes I created an example project called `TestGradleModular`. The module configuration looks fine, the modules are found from eclipse and I can use them in my application. Compilation from a Gradle run configuration works fine.

### Steps to Reproduce 

The issue is migrated from a stackoverflow question, example source coded is provided at:
https://stackoverflow.com/questions/62447810/eclipse-jpms-run-configuration-module-path-missing-modules

### Your Environment

Windows 10 x64 V1909
Gradle Version 6.4.1
eclipse 2019-12 (4.14.0) x64 with Buildship 3.1.3
eclipse 2020-06 (4.16.0) x64 with Buildship 3.1.4   
AdoptOpenJDK 11.0.6+10 x64

**Comment by donat** [comment]
We've introduced an experimental support for modulepath in the latest Buildship version.
<img width="657" alt="image" src="https://user-images.githubusercontent.com/419883/106461270-d23bbd80-6494-11eb-9ff8-4657a83b8b1c.png">

Can you please try that and give us feedback?

**Comment by fireandfuel** [comment]
I have some good news: 
It works perfectly with my test project

**Comment by donat** [comment]
Thanks for the confirmation!

**Comment by crowlogic** [comment]
this needs to be revisited and made so that its enabled by default, i dont think JPMS is 'experimental' any longer
