### ISSUE TITLE
Project import fails if the gradle is configured to use gradle wrapper

### ISSUE THREAD

**Issue by gayanper** [eclipse/buildship#1021]
When trying to import a new gradle project for example a project like https://github.com/gayanper/idea-spring-tools, if the buildship plugin is configured to use the gradle wrapper, the import doesn't work.

### Expected Behavior
The project should get import successfully.

### Current Behavior
A eclipse project is create but no gradle tasks or classpath are configured.

### Your Environment
Eclipse 2020-06 on Windows and MacOS

**Comment by donat** [comment]
I was able to import the project with the latest version of Buildship: 

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/419883/106472336-da9af500-64a2-11eb-93cb-6634c65afe0c.png">

I've only observed a couple of compiler errors which probably just indicate missing configurations in `eclipse.classpath.plusConfigurations`.

Let me know if you need further help.
