### ISSUE TITLE
Truncated options dialog

### ISSUE THREAD

**Issue by PyvesB** [eclipse/buildship#1023]
### Expected Behavior

The entire Options dialog should be visible, or it should at least be possible to scroll to see hidden parameters.

### Current Behavior

Some options are truncated and cannot be viewed. See screenshot below:
![truncated-options](https://user-images.githubusercontent.com/10694593/89166814-e3098600-d57a-11ea-8074-b1e15621380c.png)

### Steps to Reproduce 

Create a new Gradle project and click Next until you land on the Options dialog. If you're using a bigger screen, the truncation may not be visible initially, but you can resize the dialog. If you make it smaller, you'll notice that most of the options will end up being truncated, but the dialog won't become scrollable.

### Your Environment

Eclipse 2020-06 with Buildshipt 3.1.4.

**Comment by donat** [comment]
Interesting. It is scrollable on macOS. Can you resize the window?

**Comment by PyvesB** [comment]
Same problem on my macOS:

<img width="613" alt="Screenshot 2021-02-08 at 11 05 19" src="https://user-images.githubusercontent.com/10694593/107211566-a7ee8080-69fd-11eb-8ea8-a3c7cdf123c9.png">

**Comment by donat** [comment]
@PyvesB I've done some adjustments to the UI code. Can you please install this snapshot version and see if it improves the situation on your side? https://download.eclipse.org/buildship/updates/e416/snapshots/3.x/3.1.5.v20210216-1312-s/

**Comment by PyvesB** [comment]
@donat I installed version 3.1.5.v20210216-1312-s, unfortunately the problem still seems to be happening.

**Comment by manueljordan** [comment]
Just in case I have the same issue, but my Mac is `El Capitan`

**Comment by donat** [comment]
@PyvesB What's your display's resolution? Also, do you use scaled fonts?

**Comment by PyvesB** [comment]
On my Windows, the resolution is 1366 × 768, on my macOS the resolution is 2880 × 1800. I don't think I used scaled fonts, at least I'm not aware of having changed any such settings.
