### ISSUE TITLE
items in Gradle Tasks tree, no feedback whatsoever

### ISSUE THREAD

**Issue by grandinj** [eclipse/buildship#1031]
All of the gradle commands in the Gradle Tasks tree are disabled. 

There is no feedback. There are no errors in my log. Double-clicking does nothing.

**Comment by grandinj** [comment]
Buildship: Eclipse Plug-ins for Gradle	3.1.4.v20200326-1743	org.eclipse.buildship.feature.group	Eclipse Buildship

**Comment by donat** [comment]
Please send me a minimal sample project exhibiting the problem and I'll take a look.

**Comment by grandinj** [comment]
Hi. 

Thanks for the offer.

It turns out my problem was solved by:

    https://stackoverflow.com/questions/50753936/gradle-tasks-are-disabled-in-eclipse

And I strongly suspect my problem was caused by a "simple suggestion" from one of our devs to make a different project use the local copy of this project, instead of the copy in our local gradle repository, where we have

    includeBuild "../PeralexLibs" // Uncomment to use local PeralexLibs for developing.

in the other projects settings.gradle file

Anyhow, I'm going to revert back to ANT for my builds, just to preserve my sanity.
