### ISSUE TITLE
ProjectConfigurator runsBefore/runsAfter ordering is not respected

### ISSUE THREAD

**Issue by njbartlett** [eclipse/buildship#1032]
Problem observed in org.eclipse.buildship.core version 3.1.4.v20200326-1743.

I want to implement a `ProjectConfigurator` that adds a classpath container to the Java project. This configurator must run after the Buildship `BaseConfigurator` because that configurator removes all existing containers from the project (other than the JRE container). To achieve this I put `runsAfter="org.eclipse.buildship.configurators.base"` in the extension declaration, but this does not work.

My extension is declared as follows:

```xml
   <extension point="org.eclipse.buildship.core.projectconfigurators">
      <configurator
            class="com.example.gradleprojectconfigurator.MyProjectConfigurator"
            id="com.example.gradleprojectconfigurator.myConfigurator"
            runsAfter="org.eclipse.buildship.configurators.base">
      </configurator>
   </extension>
```

### Expected Behavior

The `configure` method of my declared configurator class should be invoked after the `configure` method of `BaseConfigurator`.

### Current Behavior

My `configure` method is actually executed before `BaseConfigurator.configure`. The configurators are invoked in whatever arbtrary order they are found by the Eclipse extension registry, which is generally based on alphabetical ordering of the contributing plugin ID.

### Context

I need to supplement the runtime JUnit classpath of a Java project in order to support a proprietary tool. Because of this ordering issue I am unable to make the change persist in the project.

### Steps to Reproduce 

Example plugin archive attached: [com.example.gradleprojectconfigurator.zip](https://github.com/eclipse/buildship/files/5223752/com.example.gradleprojectconfigurator.zip)

The easiest way to see the problem is to place a breakpoint onto the `configure` method of this plugin's configurator and BaseConfigurator, then observing the order in which they are invoked after refreshing the Gradle project. Alternatively simply observe that the dummy classpath container is never added to the project.

### Your Environment

Observation: the problem seems to be in the method: `org.eclipse.buildship.core.internal.extension.InternalProjectConfigurator.from(List<ProjectConfiguratorContribution>)`. This method removes contributions with invalid dependencies, or with cyclic dependencies, as defined by the runsBefore/runsAfter attributes. But it never actually rearranges the contribution list into an order that respects those attributes.

**Comment by donat** [comment]
@thomasdelhomenie Contributions are always welcome!

**Comment by thomasdelhomenie** [comment]
@donat I created the PR https://github.com/eclipse/buildship/pull/1215. Waiting for your feedback!
