### ISSUE TITLE
multi module project with multiple war subprojects and common composite build dependency - fails on import

### ISSUE THREAD

**Issue by attila-it4all** [eclipse/buildship#1033]
I have the following projects:
some-library  (plugin java-library)
multiple-war (make subprojects java-library)
-- subproject-1 (plugin war + dependency to some-library)
-- subproject-2 (plugin war + dependency to some-library)

Both subproject-1 and subproject-2 has a dependency on some-library. multi-war uses some-library through composite build.

### Expected Behavior
When importing multi-war into Eclipse as Existing Gradle project, it should take a few seconds to complete.

### Current Behavior
Import hangs indefinitely.

### Context
I'm trying to import these projects into Eclipse. 

### Steps to Reproduce 
See attached zip file:
[buildship_multiple_war.zip](https://github.com/eclipse/buildship/files/5305504/buildship_multiple_war.zip)

If I comment out one of the two some-library dependency, then I can import the projects into Eclipse. After that I comment back the some-library dependency, run Refresh Gradle project, and see this in the console:

Working Directory: D:\Work\sandbox_2\multiple-war
Gradle user home: C:\Users\matea\.gradle
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 6.6.1
Java Home: D:\Tools\java\jdk-11.0.8.10-hotspot
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
> Task :subproject-2:cleanEclipseWtpComponent
> Task :subproject-2:cleanEclipseWtpFacet
> Task :subproject-2:cleanEclipseWtp UP-TO-DATE
> Task :subproject-1:cleanEclipseWtpComponent
> Task :subproject-1:cleanEclipseWtpFacet
> Task :subproject-1:cleanEclipseWtp UP-TO-DATE
> Task :subproject-2:eclipseWtpFacet
> Task :subproject-2:eclipseWtpComponent
> Task :subproject-1:eclipseWtpComponent

At this point it hangs and never stops. I can however stop it in the Progress window, then these two lines appear:

> Task :subproject-1:eclipseWtpComponent FAILED
> Task :subproject-2:eclipseWtpComponent FAILED

For me it seems like some parallel issue when referencing the same wtp resource (without composite build some-library reference things just work).

### Your Environment
I'm using Windows 10, Eclipse for Enterprise Developers v2020-06, Gradle 6.6.1 and Buildship 3.1.4. I've tried to upgrade to Eclipse EE 2020-09, no change.

**Comment by claui** [comment]
Same here on Eclipse v2020-09, Gradle 6.8.rc1 and Buildship latest snapshot.

@donat What can I do to help pinpoint the root cause?

**Comment by donat** [comment]
I was able to reproduce the issue.

**Comment by donat** [comment]
It seems that the example doesn't even work on the command line. When I execute

    ./gradlew cleanEclipseWtp eclipseWtp

the build still hangs. Using the `--debug` parameter shows that the build waits for a lock:

```
2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2021-02-03T10:12:18.916+0100 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

I'll move this issue to the gradle/gradle board.

**Comment by donat** [comment]
Moved to: https://github.com/gradle/gradle/issues/16010

**Comment by attila-it4all** [comment]
> Moved to: [gradle/gradle#16010](https://github.com/gradle/gradle/issues/16010)

Thank you Donát, I'll track it in that issue.
