### ISSUE TITLE
gradle refresh project changes compiler to JavaSE-15 in eclipse

### ISSUE THREAD

**Issue by bschatz** [eclipse/buildship#1049]
### Expected Behavior

gradle takes the java that is configured in eclipse

### Current Behavior

after executing ,,Refresh gradle project'' the ,,project specific settings'' is enabled
classpath and compiler compliance level is set to 15.
This happens for all old projects and also for new (empty) gradle projects.

e.g. empty project with just:
plugins { id("java-library") }

(,,gradle build'' on console works fine)

### Context

(1) Set back the JRE System Library and JDK compliance back to workspace default (JDK11)
(2) Changed from gradle from /usr/bin/gradle to gradle wrapper.  
(3) set .settings/org.eclipse.jdt.core.prefs to readonly 

in all cases  the execution of ,,gradle refresh project'' set everything back to Java15. 
Why does the gradle plugin thinks to use an other java, and why java15 ? Is this somewhere hardcoded ?

The only workaround i found, is to set explicit the java versions in the build.gradle -->
sourceCompatibility = '1.11'
targetCompatibility = '1.11'

In the project the ,,project specific settings'' is enabled and jdk set to 11.

### Steps to Reproduce 
see ,,Current Behaviour''

### Your Environment
Up to date Linux Debian 10 box.
Eclipse 2020-12, just upgraded from Eclipse 2020-09 where everything worked fine.

java -version  && which java && echo $JAVA_HOME && echo JDK_HOME && gradle --version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
/usr/bin/java

JDK_HOME
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/usr/share/java/groovy-all.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.4.1
------------------------------------------------------------

Build time:   2012-12-21 00:00:00 UTC
Revision:     none

Groovy:       2.4.16
Ant:          Apache Ant(TM) version 1.10.5 compiled on August 27 2018
JVM:          11.0.9.1 (Debian 11.0.9.1+1-post-Debian-1deb10u2)
OS:           Linux 4.19.0-13-amd64 amd64

 sudo aptitude search '~i openjdk'
i A openjdk-11-doc                                                          - OpenJDK Development Kit (JDK) documentation                                       
i   openjdk-11-jdk                                                          - OpenJDK Development Kit (JDK)                                                     
i A openjdk-11-jdk-headless                                                 - OpenJDK Development Kit (JDK) (headless)                                          
i A openjdk-11-jre                                                          - OpenJDK Java runtime, using Hotspot JIT                                           
i   openjdk-11-jre-headless                                                 - OpenJDK Java runtime, using Hotspot JIT (headless)                                
i   openjdk-11-source                                                       - OpenJDK Development Kit (JDK) source files

**Comment by donat** [comment]
The workaround is the way to handle it. Buildship sets the compiler version based on the `source/targetCompatibility` configuration.

**Comment by MrZeusTheCoder** [comment]
So the workaround is avoiding Eclipse configuration and is the new expected behaviour? So I have to set the compatibility on all my projects? Help would be awesome, I am trying to resolve this in a context where not everyone is using the same version of Java. This entirely disallows that.
