### ISSUE TITLE
Importing new sub modules into existing project doesn't work

### ISSUE THREAD

**Issue by gayanper** [eclipse/buildship#1055]
**Reproducing steps:**
- Import an existing gradle multi module project into Eclipse
- Add new sub module into the same project out side eclipse
- Now try to import the new modules by right clicking the new folder which will start the import wizard.
- Select gradle import and choose your project root folder
- This will show the preview of the module tree with new modules
- Press Finish

**Expected Behavior**
 The new module should be added as Eclipse project into eclipse workspace

**Actual Behavior**
The new modules stays as folders in the workspace even though the required project meta files are created.

**Workaround**
Right click the folder and import as "Project from Folder or Archive" which will import the projects as java projects without the gradle nature which result in a project without dependencies.

**Comment by donat** [comment]
Here's what you do: 
- declare the new subproject in your build (in `settings.gradle(.kts)`) 
- create a corresponding directory 
- Right click on the root project - or any project from the same build - and select `Gradle > Synchronize`.

**Comment by gayanper** [comment]
Sorry for late reply, i think I forgot to share my findings. The problem i had was due to a error in build script.
