### ISSUE TITLE
Cannot import project with Gradle version 6.8.1

### ISSUE THREAD

**Issue by UdoW** [eclipse/buildship#1060]
### Expected Behavior

I want to import a Gradle project which uses version 6.8.1. When I try to do it with Buildship then Eclipse crashes without any error message or threads dump.

### Current Behavior

If I import a Gradle project which uses version 6.6.1 it is imported without problems.

### Context

I use Java 15. I tried it with Eclipse 2020-12 and 2021-03 (milestone). Also with Buildship 3.1.4 and 3.1.5. All combinations do not work with Gradle version 6.81.

### Steps to Reproduce 

Create a Java project with Gradle version 6.8.1 and import it into Eclipse.
### Your Environment

* Java 15
* Eclipse 2020-12
* Eclipse 2021-03 (Milestone)
* Buildship 3.1.4
* Buildship 3.1.5
* Windows 10, latest patch

**Comment by donat** [comment]
What happens if you use the `New Gradle project` wizard and set the Gradle version to 6.8.1?

**Comment by UdoW** [comment]
When I select version 6.8.1 in my Eclipse 2020-12 then Eclipse just crashes, i.e. the window is closed without any message.

**Comment by UdoW** [comment]
In my Eclipse 2020-12 I use Buildship 3.1.4.

**Comment by UdoW** [comment]
Also 7.0-milestone1 crashed Eclipse.

**Comment by UdoW** [comment]
Some further tests:

I used the wizard "New Gradle Project" with these versions (on Windows 10 machine):

Eclipse 2020-12, Buildship 3.1.4: 

- Gradle 6.8.1 -> Crash
- Gradle 7.0-milestone1 -> Crash

Eclipse 2021-03-m1, Buildship 3.1.5:
- Gradle 7.0-milestone1 -> Crash
- Gradle 6.8.1 -> Crash
- Gradle 6.8 -> Crash
- Gradle 6.7.1 -> Crash
- Gradle 6.6.1 -> works
- Gradle 6.4 -> works

The project folder was created but with no content.

**Comment by donat** [comment]
What JDK do you use for running Eclipse?

**Comment by UdoW** [comment]
Eclipse IDE for Java Developers (includes Incubating components)

Version: 2021-03 M1 (4.19.0 M1)
Build id: 20210114-1452

Java version for running Eclipse:
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.23.0, JRE 15 Windows 10 amd64-64-Bit Compressed References 20201022_82 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - ad583de3b5 based on jdk-15.0.1+9)

I have different global settings for Maven and Gradle:

Maven:
Changed local repository path with a global settings.xml

Gradle:
Changed in global gradle.properties file:

Java version for running Gradle with property org.gradle.java.home to

openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)

and changed Gradle home to another drive N:/gradle_home

Maybe my different settings are not working correctly anymore with the newer Gradle versions together with Buildship?
Or the fact that my Eclipse is running with a different Java version than the version which is set for Gradle?
But with Gradle versions < 6.7 it works.

**Comment by donat** [comment]
Can you try changing the Eclipse configuration to run in a Hotspot JVM? The OpenJ9 variant might be the culprit.

**Comment by UdoW** [comment]
Ok, the OpenJ9 JVM was the problem. I switched to the Amazon Corretto 11.0.8 JVM which I use in the Gradle settings.

**Comment by UdoW** [comment]
But there is still the question, why the combination of OpenJ9 and Gradle version < 6.7 works.

**Comment by UdoW** [comment]
I tried also the OpenJ9 version 11 and it works to create a new gradle project with version 6.8.1.

So maybe the different versions of running Eclipse with Java 15 and Gradle with Java 11 is the problem?

**Comment by donat** [comment]
This is a consequence of Gradle not supporting OpenJ9 at the moment. The behavior of Gradle and Buildship is not validated and can fail in many ways. I've opened an issue (⏫) to make Gradle fail with an explicit error message when running on OpenJ9.

**Comment by UdoW** [comment]
Another try: AdoptOpenJDK version 15 for Eclipse and Amazon Corretto 11 for Gralde works fine, too.
