### ISSUE TITLE
Even after uninstalling, keep getting the warning "Migration from STS Gradle to Buildship"

### ISSUE THREAD

**Issue by hegdemk2004** [eclipse/buildship#1063]
I have uninstalled the Gradle IDE and updated Buildship plugin. Why do  this warning. How do I check, if I have uninstalled all the older versions of STS?

**Comment by donat** [comment]
Check installed plugins here: `File > About Eclipse > Installed plugins`
The message is produced by the plugin with id `org.eclipse.buildship.stsmigration`. If it's there then it was not properly uninstalled.
