### ISSUE TITLE
Could not resolve dependency - Eclipse Buildship 3.1.5

### ISSUE THREAD

**Issue by fco271292** [eclipse/buildship#1081]
### Expected Behavior

I use the IDE for update the dependencies with the sentence in block repositories at same leve of mavenCentral(), but no update dependenciesn from archiva online of company
`maven { url 'http://IP:PORT/repository/internal/' }
maven { url 'http://IP:PORT/repository/snapshots/'}`

### Current Behavior

Show message **Could not resolve dependency**

### Steps to Reproduce 

In the proyecj, select Gradle / Refresh gradle project and no resolve dependencies internal

### Your Environment

Windows 10
Java JDK 1.8.0_291
Eclipse 2021-03 (4.19.0)
Gradle plugin 3.1.5

How solve this issue?, thank you in advance

**Comment by donat** [comment]
This seems like a problem with your company-internal repository. I don't have any way to investigate it for you. I can only recommend to carefully read the [corresponding chapter](https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring-repositories) of the Gradle user guide.
