### ISSUE TITLE
Importing gradle generated library got stuck

### ISSUE THREAD

**Issue by MaSven** [eclipse/buildship#1083]
### Expected Behavior
Should import the gradle project

### Current Behavior
It never finishes the import process and hangs in this window.
![Screenshot_20210517_192110](https://user-images.githubusercontent.com/9138252/118530563-16ea1c80-b745-11eb-9939-a946dd5592ee.png)

### Context
Because of this issue I can't import any newly created project.  

### Steps to Reproduce 
Download gradle 7.0.1. Create a new directory. Create a new gradle project in this directory. Try to import the project into eclipse.
Override the global settings. 
![Screenshot_20210517_192708](https://user-images.githubusercontent.com/9138252/118531230-e6ef4900-b745-11eb-9694-44e8d7faad11.png)
Click on Next. Click on finish.

### Your Environment
Eclipse
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

Buildship:
Buildship: Eclipse Plug-ins for Gradle	3.1.5.v20210113-0929	org.eclipse.buildship.feature.group	Eclipse Buildship
I also have a flight recording that I can share.

Buildscan: https://gradle.com/s/fgo5ye7lwmck4

My eclipse.ini
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
/home/sven/.p2/pool/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.100.v20210209-1541
-product
org.eclipse.epp.package.jee.product
-showsplash
/home/sven/.p2/pool/plugins/org.eclipse.epp.package.common_4.19.0.20210311-1200
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
/home/sven/.sdkman/candidates/java/16-open/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dsun.java.command=Eclipse
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
-Declipse.p2.max.threads=10
-Doomph.update.url=http://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
```

**Comment by donat** [comment]
I've used the specified eclipse-java-gradle combination but it works for me.

**Comment by MaSven** [comment]
OK I will try to debug the issue maybe I can see in which process this happens.
