### ISSUE TITLE
Buildship doesn't properly setup test compile classpath when using java-test-fixtures plugin

### ISSUE THREAD

**Issue by alienisty** [eclipse/buildship#1129]
When using the java-test-fixtures plugin, Buildship properly maps **src/testFixtures/java** as a test folder, the problem is that when the client module adds the project reference as testFixtures() in its dependencies, the provider module's **src/test/java** folder is also included in the compile classpath, when it should not be.

### Expected Behavior
The provider module's **src/test/java** folder should not be included in the consumer module's test compile classpath

### Current Behavior
The provider module's **src/test/java** folder is included in the consumer module's test compile classpath

### Context
What compiles in ecplipse does not compile from the command line

### Steps to Reproduce 
The following demonstrating project can be used to demonstrate the problem [root.zip](https://github.com/eclipse/buildship/files/7760659/root.zip)

### Your Environment
Gradle version 7.3.2
Eclipse 4.22
Buildship 3.1.5.v20210113-0929

**Comment by donat** [comment]
You are right, your use-case should not work. Problem is, there's not much we can do about it at this point. Eclipse has one compile classpath per project, that cannot be easily mapped to Gradle source sets and custom dependency configurations.  If you have a project dependency declared in your project, Eclipse can only distinguish between test and non-test source sets and dependencies. Defining further separation between test and test fixtures cannot be done, at least not without some nasty workarounds.

I'm currently working on an improvement  in this area in Gradle: https://github.com/gradle/gradle/pull/19310. You can give it a try with a [snapshot release generated from my feature branch](https://services.gradle.org/distributions-snapshots/gradle-7.4-branch-donat_eclipse_test_sources_and_deps_take_2-20211222124805+0000-bin.zip).

Unfortunately, using it won't fix your case, but it will automatically add the `test=true` classpath attribute to your project dependency. Please try it out; any feedback is appreciated.

**Comment by alienisty** [comment]
I appreciate that eclipse does not allow the distinction, but shouldn't you work with the eclipse JDT guys to remove that limitation? You are under the same eclipse umbrella, so it would make only sense that eclipse plugins work properly with eclipse.

Anyways, to be clear, if Buildship could filter out the provider's **src/test/java** folder, this issue should be solved.

**Comment by donat** [comment]
> Anyways, to be clear, if Buildship could filter out the provider's src/test/java folder, this issue should be solved.

Can you please paste a `.classath` file showing how it can be done? AFAIC you can only do filtering on the fully-qualified class names.

**Comment by alienisty** [comment]
I did try to use exported="false" for the folder I wanted to exclude, but it looks like eclipse forces it, see attachment:
![image](https://user-images.githubusercontent.com/4103676/147634891-562e119e-ae71-4d2e-b1d4-6b4d093151d4.png)
If we could disable the folder pointed in the image, then this issue could be solved.

**Comment by donat** [comment]
This thread seems to be related to your findings: https://bugs.eclipse.org/bugs/show_bug.cgi?id=224708

**Comment by alienisty** [comment]
Yes that is the change that, finally, implemented the distinction of test source folders, but, even if they mention it, they did not fix/allowed deselecting a folder in the export tab.

**Comment by alienisty** [comment]
For what is worth I filed the following bug with eclipse: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578034
