### ISSUE TITLE
Default binary file folder 

### ISSUE THREAD

**Issue by CsCherrYY** [eclipse/buildship#1131]
It seems the default behavior of buildship is to generate `.class` files in `bin` folder of the project (maybe it related to some Eclipse configurations), but for Gradle users, they might be familiar with `build` folder. There are some requests related to this issue:

- https://github.com/redhat-developer/vscode-java/issues/634
- https://github.com/redhat-developer/vscode-java/issues/1615
- https://discuss.gradle.org/t/when-buildship-imports-a-java-project-it-doesnt-change-the-build-path-output-folder/17074
- https://discuss.gradle.org/t/on-buildship-project-imports-java-buildpath-output-folder-is-left-as-bin/17414

Now I can still reproduce this in both the newest eclipse and VS Code. A workaround can be found here: https://github.com/redhat-developer/vscode-java/issues/634#issuecomment-696788135. But we can't make `build` as the default binary output folder by default. I'm not sure there if there is anything we can do at buildship side to make the user experience better. @donat could you provide any comments?

**Comment by donat** [comment]
I understand the intent, but I don't think it's a good idea. There's a reason why Eclipse and Gradle do not share their build folders. If those directories would be shared:
- The JDT editor support could be easily be broken by deleting the class files (generated by `ejc`) with a simple `gradle clean` command.
- Many Gradle features (up-to-date checks, cache hits, compile avoidance, etc) could be busted if JDT would write classes to the Gradle build directory.

**Comment by mkq** [comment]
I agree that Eclipse and Gradle output directories should be separate, but Buildship should honor Window / Preferences / Java / Build Path / Output folder name (whether the user sets it to "build" if he's adventurous or whatever).

Can we reopen this issue or should I open a new one? redhat-developer/vscode-java#1615 (mentioned in redhat-developer/vscode-java#2801 in turn mentioned above) seems close, but is about VSCode. Maybe a Buildship specific option makes sense there, but in Eclipse, the obvious Buildship Default would be to use the Eclipse preference.
