### ISSUE TITLE
"Project and External Dependencies" could not be resolved inside eclipse IDE

### ISSUE THREAD

**Issue by RobertWalterU3d** [eclipse/buildship#1132]
I ran into [this issue](https://github.com/itemis/xtext-languageserver-example/issues/79) when I used buildship in a project where I developed a DSL with Xtext, following [this template](https://github.com/itemis/xtext-languageserver-example/).

When I opened eclipse IDE, my projects did not contain the library "Project and External Dependencies". I still don't know exactly why that happend, but it must have been related to me using the root directory as my eclipse workspace.

What solved it was to create a new workspace and import the root gradle project. I would have never guessed that since buildship did not provide me any error message or information about that issue. 

It would be great if buildship would communicate this limitation with the user somehow when trying to refresh the dependencies.

### Expected Behavior
I should either be able to use the root folder as a eclipse workspace, or be informaed that I have to use a different workspace forlder to make dependency resolution work.

### Current Behavior
"Project and External Dependencies" don't show up in eclipse IDE, and all the corresponding references are broken. Trying to refresh the dependencies inside eclipse does not show any message in the console.

### Context
I wanted to open my project in eclipseIDE to develop it further. I wasn't able to use eclipseIDE.

### Steps to Reproduce 
Sorry, not able to do that.

### Your Environment
Windows 10
eclipse version is: 2020-06
buildship version (acc. to eclipse->Help->About): 3.1.4.v20200326-1743
gradle (acc to command ./gradlew -v): 5.6.4

**Comment by donat** [comment]
> but it must have been related to me using the root directory as my eclipse workspace.

Please don't do that. Buildship explicitly forbids that option and if you work around the safety guards you only end up with undefined plugin behavior.

**Comment by donat** [comment]
Both the project creation and import wizard do have a validator for this. If you use the workspace root as the project root the wizard should block the user from clicking 'Finish'. If that's not the case please let us know.
