### ISSUE TITLE
Create download.eclipse.org/buildship/updates/snapshot update site

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#1153]
https://github.com/eclipse/buildship/issues/1148#issuecomment-1110896068

**Comment by vogella** [comment]
Thanks. Would be useful for testing

**Comment by vogella** [comment]
https://download.eclipse.org/buildship/updates/snapshot/ does not work for me, neither does https://download.eclipse.org/buildship/updates/latest-snapshot/

![image](https://user-images.githubusercontent.com/139910/167775131-0cfb3c40-bd20-4427-a7be-fab2fcd9817c.png)

**Comment by donat** [comment]
The first snapshot promotion build did not finish when you tried to use it. It is live now: https://download.eclipse.org/buildship/updates/latest-snapshot/
