### ISSUE TITLE
Feature "org.eclipse.buildship.oomph" is not published any more on update sites since 3.1.6

### ISSUE THREAD

**Issue by schwitzkroko** [eclipse/buildship#1169]
With the Oomph installer we implement a configuration management for local development environment. As we regularly use Gradle we rely on the "Oomph Import Setup Task". It is referred in our setup xml a lot. 
Be overlay p2 definitions to define our own distribution with 1st and 3rd party plugins. Therefore on the stage "installation" we need to set https://download.eclipse.org/buildship/updates/latest/ as the update site and require the feature "org.eclipse.buildship.oomph".

### Expected Behavior
Product and project installed and is set up: cloned and imported by Buildship.

### Current Behavior
Installer fails with displaying:
```
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:722)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1652882601424
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1652882601424 requires 'org.eclipse.equinox.p2.iu; org.eclipse.buildship.oomph.feature.group 0.0.0' but it could not be found
```

### Context
See above descriptions.
Already investigated: neither feature is present with current update site, nor the setup task is now part of the general distribution feature "org.eclipse.buildship": the plugin bundles are missing as well.

Either this is missing from deployment, or I am missing out on the mention of a now update site url.

### Steps to Reproduce 
a) Use installer and setups and within use  ```<setupTask xsi:type="oomph:GradleImportTask" ... />``` - error see above.
b) Have available "org.eclipse.buildship" and "org.eclipse.oomph*" and in Oomph editor try to add a "New Child" > "Additional Tasks..." > "Gradle Import..." - called Installer within IDE instance does not perform.

### Your Environment
Win11Pro, JDK Temurin 11, current Eclipse Installer based on 4.23

Thanks for your consideration! And, Donat, keep up good work - many thanks!

**Comment by schwitzkroko** [comment]
perfect! thank you!

for anyone looking for a **workaround** until the time 3.1.7 is released and published, we could make do to acquire the Oomph setup task plugins from this older update site path and it works for/in "latest release" 2022-03:
https://nexus.secure.ifao.net:8443/repository/ifao-p2_eclipse-public-raw-buildship-updates/e416/releases/

**Comment by urferr** [comment]
I have the same problem but unfortunately also the workaround mentioned before does not work. When i try with the url https://nexus.secure.ifao.net:8443/repository/ifao-p2_eclipse-public-raw-buildship-updates/e416/releases/ i get an unknown host exception

**Comment by donat** [comment]
you can also use the latest snapshot repository: https://download.eclipse.org/buildship/updates/latest-snapshot/

**Comment by urferr** [comment]
thanks
i use now https://download.eclipse.org/buildship/updates/e416/releases/3.x/3.1.5.v20210113-0929 to not already use the milestone build for all buildship features. This works too

**Comment by schwitzkroko** [comment]
> I have the same problem but unfortunately also the workaround mentioned before does not work. When i try with the url https://nexus.secure.ifao.net:8443/repository/ifao-p2_eclipse-public-raw-buildship-updates/e416/releases/ i get an unknown host exception

sorry, of course i wanted to refer by this url:
https://download.eclipse.org/buildship/updates/e416/releases/

you can see the feature artifact here:
https://download.eclipse.org/buildship/updates/e416/releases/3.x/3.1.5.v20210113-0929/features/

...and in 'latest-snapshot' as @donat posted meanwhile!

**Comment by schwitzkroko** [comment]
> you can also use the latest snapshot repository: https://download.eclipse.org/buildship/updates/latest-snapshot/

hi @donat!
currently there is no feature folder published anymore - for the current versions as well, i think this happened for all update sites (re)created on 2023-03-28. this is a general problem, i suppose?

...so the oomph setup plugin is not there as well.
(our organization is resorting to https://download.eclipse.org/buildship/updates/e416/releases/3.x/3.1.5.v20210113-0929/ for now...)

**Comment by donat** [comment]
Thanks for mentioning that. The promotion build was broken for a while. I've fixed the problem. The oomph feature is also part of the generated update site: https://download.eclipse.org/buildship/updates/e48/snapshots/3.x/3.1.7.v20230405-1237-s/plugins/
