### ISSUE TITLE
Gradle 7.5+ - Eclipse cannot resolve types from projects with text fixtures

### ISSUE THREAD

**Issue by mweber03** [eclipse/buildship#1201]
Classes from `src/main/java` in projects containing text fixtures can no longer be resolved in Eclipse (i.e. `Xyz cannot be resolved to a type`). It works with 7.4.2, but does not work with 7.5 or 7.5.1.

### Expected Behavior
Eclipse should be able to resolve the classes, as it previously did.

### Current Behavior
The classes from `src/main/java` cannot be resolved in Eclipse.

### Steps to Reproduce 
1. Clone https://github.com/mweber03/gradle-test
2. Import into Eclipse
4. In Eclipse, `Gradle > Refresh Gradle Project` (note the clean build, no red Xs on classes)
5. Upgrade project to Gradle 7.5.1 (`./gradlew wrapper --gradle-version 7.5.1`)
6. In Eclipse, `Gradle > Refresh Gradle Project` (note classes can no longer be resolved)

### Your Environment
Build scan URL: https://gradle.com/s/lpfpi33q6j54o

**Comment by mweber03** [comment]
Not sure if this is a Gradle or Buildship issue, so I wrote up the Issue in both: https://github.com/gradle/gradle/issues/21853

**Comment by donat** [comment]
See https://github.com/gradle/gradle/issues/21853 for the explanation.
