### ISSUE TITLE
Undo does not work anymore in Gradle Build Script Editor in Eclipse 2022-09

### ISSUE THREAD

**Issue by MahatmaFatalError** [eclipse/buildship#1208]
### Expected Behavior
1. Open a .gradle file in Gradle Build Script Editor.
2. Edit the file and save.
3. Undo the change via cmd+z or Edit > undo

### Current Behavior
Nothing happens. Change gets not undone.

### Steps to Reproduce 
Can't reproduce it in a dummy project, only in a full-blown project.

### Your Environment
MacOS 12.6
Spring Tool Suite 4 
Version: 4.16.0.RELEASE
Build Id: 202209151144
Gradle 7.4.2
No entries in the Eclipse Error Log

**Comment by jetztgradnet** [comment]
This is broken much longer, already since 2021-09 or even eralier, I believe...

**Comment by MahatmaFatalError** [comment]
I noticed that when I have multiple build.gradle editors open, and I press cmd+z for undo on the editor with focus, the content of the gradle editor in the background gets dirty. So effectively the undo command is directed to the wrong editor window.

**Comment by BonusLord** [comment]
Yeah, this has been a problem for a year or two. It is very confusing when your undo keystrokes get directed to a non-active editor tab and end up silently making changes to a different file without you realizing it. (It's also just very challenging to iterate on a gradle script when undo/redo doesn't work consistently 😛 )

**Comment by oleosterhagen** [comment]
This issue duplicates #1188 and should be closed.

**Comment by donat** [comment]
> This issue duplicates https://github.com/eclipse/buildship/issues/1188 and should be closed.

That's correct; closing.
