### ISSUE TITLE
Show whitespace button disabled in build.gradle editor

### ISSUE THREAD

**Issue by veita** [eclipse/buildship#1211]
The toolbar button for showing whitespace is disabled when the `build.gradle` editor is active,

### Expected Behavior
It should be possible to turn showing whitespace on and off using the toolbar button.

### Current Behavior
The button is disabled and thus not functional. One has to switch the editor to e.g. a Java file, hit the button and the return back to the `build.gradle` editor to turn showing whitespace on and off.

### Environment
Eclipse Version: 2022-09 (4.25.0), Build id: 20220908-1902
Buildship,  3.1.6.v20220511-1359

**Comment by donat** [comment]
Fixed in #1243 

<img width="707" alt="image" src="https://github.com/eclipse/buildship/assets/419883/e4c5b353-b9db-4bea-b4c8-90e2dc33546f">
