### ISSUE TITLE
Update site pages incorrect in the user documentation

### ISSUE THREAD

**Issue by thahnen** [eclipse/buildship#1274]
### Current Behavior

The [user documentation](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) regarding the Eclipse update sites is leading to dead links. Additionally, for the newer versions of the Eclipse IDE, there are no links given even though the update sites do actually exist (Eclipse 2022-06 and up).

### Expected Behavior

Dead links are gone, and missing links are added.

### Steps to Reproduce 

Test all the links on the user documentation page.

## Info ❗ 

Just give me a heads up if it would be okay for me to do the changes on my own or if you prefer doing it yourselves / This is expected behavior (for whatever reason) 👍

**Comment by donat** [comment]
If you have time to create a PR, I'll be happy to review and merge it.

**Comment by thahnen** [comment]
I have, you'll get pinged when the PR is ready ^^

**Comment by thahnen** [comment]
@donat the PR is ready for review, I have no rights to set you as a reviewer 🙇‍♂️

**Comment by donat** [comment]
We should add automation to auto-assign it to committers. Anyway, I've approved and merged your PR. Thank you for your contribution!
