### ISSUE TITLE
[Mac] After update on Eclipse version 09.2023 Splash Screen  upside down 

### ISSUE THREAD

**Issue by MashaKorax** [eclipse/buildship#1278]
Hello. After update on Eclipse version 09.2023 Splash  upside down on Mac Os Sonoma. On windows - its okey :) 
<img width="988" alt="Снимок экрана 2023-11-10 в 10 34 34" src="https://github.com/eclipse/buildship/assets/84867187/d3c15748-80bb-4165-bb0f-b8819b17b0fb">

**Comment by oleosterhagen** [comment]
This problem is unrelated to Eclipse Buildship and already discussed here:

- https://github.com/eclipse-platform/eclipse.platform.swt/issues/751
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/772

@MashaKorax could you close this issue?

**Comment by MashaKorax** [comment]
Okey, Thank you!
