### ISSUE TITLE
KotlinBuildScriptModel query should be queried via ModelProvider

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#221]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [donat](https://github.com/donat)**
_Tuesday Jan 31, 2017 at 14:09 GMT_

----

This way  the fixed and transient request attributes would be set consistently for all model queries.

**Comment by oehme** [comment]
We should reuse the resolver of GSK instead.
