### ISSUE TITLE
User can enable scan creation in Buildship

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#229]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Monday Jan 23, 2017 at 13:24 GMT_

----

## Motivation

Assuming that a user is already using the build scan plugin, but doesn't use `publishAlways`, Buildship should make it easy to enable creation of build scans.

## Implementation

- Add a `Create build scan(s)` option to the workspace, project and run configuration pages, similar to offline mode.
- Honor this option when synchronizing projects or running tasks

The user can then see the scan link in the console output. Making it easier to find the scan for an execution will be part of a different story.

Adding this option prominently might lead to higher usage of the public build scan service, make sure the CS is aware and can monitor the additional load.

**Comment by donat** [comment]
Currently, we can't determine whether a project applies the build scans plugin so we can either add the `--scan` parameter to all invocations or to none of them. This means if the user enables this feature from the workspace preferences then he'll receive build configuration failures when the plugin is not applied on the project.

**Comment by oehme** [comment]
We wouldn't use `--scan`,  we would use `-Dscan` which is always safe to use.

**Comment by donat** [comment]
The workspace setting is quite simple: we add the `-Dscan` JVM argument just like we do with the `--offline` flag. 

For the run configuration, IMHO we should define a new group into the `Gradle Tasks` with an `Enable Build Scans`  checkbox.

I'm uncertain on the project configurations page. So far we avoided any project-scope configuration.   Shall we create project preferences page in which - like JDT - the settings override the workspace settings?

**Comment by oehme** [comment]
> For the run configuration, IMHO we should define a new group into the Gradle Tasks with an Enable Build Scans checkbox.

Could we group it together with `--offline` on the first page?

> I'm uncertain on the project configurations page. So far we avoided any project-scope configuration. Shall we create project preferences page in which - like JDT - the settings override the workspace preferences?

Yes. We could allow users to change their Gradle version selection there too, so they don't have to re-run the import wizard when they change their mind.

We need to consider how the overriding would work. For `--offline` mode there is currently no opt-out. When you have clicked `offline` on the workspace level, there is no way to be online for a specific run configuration. We could potentially do the same for `--scan`. The alternative would be a 3-way switch: `Enabled/Disabled/Use project settings`. We should probably start with the first and create a story for the second.

It seems we have several stories here that we should break out, could you create them?

- User can enable scan creation on a run configuration
- User can enable scan creation for the whole workspace
- User can enable scan creation for a specific project (introduce project preference page)
- User can override `--scan` (and `--offline`) project preferences in a run configuration
- User can override `--scan` (and `--offline`) workspace preferences in a project
- User can re-configure Gradle version on the project preference page

**Comment by donat** [comment]
That makes sense. The story is bigger than it looked than before. I'll create the cards soon.

**Comment by donat** [comment]
@oehme I've created the tickets, have a look if you have some time.
