### ISSUE TITLE
Project dependencies should be at the beginning of the classpath container

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#244]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [donat](https://github.com/donat)**
_Wednesday Feb 01, 2017 at 12:53 GMT_

----

## Motivation
https://discuss.gradle.org/t/eclipse-classpath-ordering-project-dependency-always-at-the-bottom-of-dependencies

## Code review

- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Wednesday Feb 01, 2017 at 13:33 GMT_

----

My comment from the forum: 

> I did a quick check and I have some bad news. It seem that the change breaks the fix we did for https://bugs.eclipse.org/bugs/show_bug.cgi?id=473348 Fortunately only projects with older Gradle versions (2.5-) are affected.
>
>Besides, there's another problem. Even if I change the classpath ordering, it is not reflected in the package explorer view. In other words, projects under the "Project and External Dependencies" node are placed after the libraries even if they come before in the project's classpath. This will likely confuse other users.

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Wednesday Feb 01, 2017 at 13:35 GMT_

----

> It seem that the change breaks the fix we did for https://bugs.eclipse.org/bugs/show_bug.cgi?id=473348

I don't understand how that is related, can you elaborate?
> This will likely confuse other users.

What counts is what happens at runtime.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Wednesday Feb 01, 2017 at 13:49 GMT_

----

If we put the projects on top of the classpath then importing the sample project attached to the bug (with Gradle 2.4), would show build errors. That's because older Gradle versions didn't set the dependency closures for each classpath but rather rely on classpath entry exports. 

Here's the interesting part from the sample.
```
dependencies {
    compile "org.springframework:spring-beans:3.1.4.RELEASE"
    compile (project(":moduleB")) {
        exclude group: "org.springframework"
    }
}
```
Effectively the `exclude` doesn't work correctly and the `"org.springframework` jars are included in the classpath with whatever version `moduleB` declares. We managed to get around that by putting the project dependencies after the binary ones.

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Wednesday Feb 01, 2017 at 13:55 GMT_

----

Got it, then let's only activate this if the Gradle version is >=2.5

**Comment by richard-steiger** [comment]
I'm using eclipse 2018-12, contains buildship 3.0.0.v20181106-1441-m.   I'm consistently seeing recurrence of this bug, specifically, "Project and External Dependencies" routinely precedes some or all direct dependencies.  This is having a profoundly irritating and significantly degrading effect on my development velocity (not to mention fun).  What can I do got this revisited?  

Thanks much in advance.

**Comment by oehme** [comment]
> "Project and External Dependencies" routinely precedes some or all direct dependencies.

Not sure what you mean by that - There should be no dependencies except for "Project and External Dependencies" on a Gradle project.

**Comment by richard-steiger** [comment]
Stefan,

Thanks for getting back to me.

Still being a bit of a Gradle noobie, I'm perfectly willing to learn 
that the issue I've run into is due to something wrong I'm doing.  The 
issue that provoked my comment is as follows:

I have a project (call it "P") that includes several libraries (the 
"direct" dependencies).  When debugging P under eclipse, and I step or 
hit a breakpoint in one of these libraries (call it "L"), eclipse 
suddenly stops displaying sources, just goes into decompilation mode.   
At this point, opening /Properties for P > Java Build Path > Order and 
Export/, L follows Project and External Dependencies.  If I move L 
before Project and External Dependencies, source display is restored.  
After some time or some action of which I'm unaware, the classpath is 
once again permutted as above, and source display fails again.

If there's a way to configure dependencies in build.gradle or in eclipse 
to prevent this from occurring, I'd love to know about it.

Hopefully this is sufficiently clear.

Thanks for looking into this (while I still have some hair that I 
haven't yet pulled out :-).

Cheers,

-rjs

**Comment by oehme** [comment]
Please share a reproducible example with us. There should be nothing next to `Project and External Dependencies`, all dependencies should be declared in your build and should then be inside that container.

**Comment by richard-steiger** [comment]
Let's see if you get the same results when doing the following:

in eclipse 2018-12 on Windows 10, with the Buildship plugin that came 
installed:

  * create 2 eclipse + gradle projects, call them *foo *and *bar*, with
    *foo *having a dependency on *bar*; under eclipse's *foo *property
    sheet, ensure that *foo *doesn't include *bar *as a dependent project
  * *foo *contains a class, say *X*, that references a method in some
    class in *bar*, say *Y*, for which *X* has an import declaration
  * open the source editor on *X*, select any occurrence of *Y*, and
    click Open Declaration (F3)
  * what I see: a source editor opens on *Y*, in decompilation mode

Regards,

-rjs

**Comment by oehme** [comment]
Please include a reproducible example as an attachement. If I create two Gradle projects with one depending on another, everything works just fine.

**Comment by richard-steiger** [comment]
I'm slammed with a huge project at work, so it may take me until next 
weekend to conjure-up a repo and send it.

Regards,

-rjs
