### ISSUE TITLE
Use wrapper.properties instead of own distribution setting

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#259]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Thursday May 19, 2016 at 09:52 GMT_

----

## Motivation

Buildship currently allows the user to specify which Gradle distribution to use for the build. This setting is persisted in the Eclipse metadata. It is independent from the wrapper.properties of the Gradle build (although the Eclipse settings can be "use the wrapper version").

On the other hand, Buildship provides no UI to update the wrapper.properties file.
## Proposed Change

Remove the possibility to overrule the wrapper.properties. Instead, make it easy to update the wrapper.properties in the Eclipse UI.
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
@oehme With current preferences implementation, I don't think we should implement this story. WDYT?

**Comment by oehme** [comment]
Yes, now that we warn the user about that setting I think it's okay.
