### ISSUE TITLE
Display an error marker for unresolved dependencies

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#263]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Thursday May 19, 2016 at 09:55 GMT_

----

## Motivation

Currently, Buildship does not inform the user about unresolved dependencies. As a result, the user is left wondering why a project does not compile.
## Proposed Change

We need to expose unresolved dependencies through the tooling API and add an error marker to the project if there are any.
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by fbricon** [comment]
this please. Also affects users of vscode-java.

**Comment by donat** [comment]
@fbricon Does vscode-java propagate the error markers to the editors?

**Comment by fbricon** [comment]
if build.gradle has the error markers, then they'll be shown in vscode
