### ISSUE TITLE
Update gson dependency

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#282]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Friday Nov 18, 2016 at 12:50 GMT_

----

## Motivation

GSon seems to be causing some problems on Java 9 and we only use it to store the "published Gradle versions" file.

## Proposed Change

We can probably store the same information in a simple csv format

## Code review

- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Friday Nov 18, 2016 at 13:13 GMT_

----

We don't store the published Gradle versions, we download it from [services.gradle.org](http://services.gradle.org/versions/all). The version information is in JSON format, hence the dependency.

We can replace the version download with a static version list what we would generate at compile time. But this way the offered versions from the import/creation wizard are not ensured to be up-to-date. I'm in favour of this change because it can prevent people running into forward-compatibility issues like [this](https://discuss.gradle.org/t/error-while-creating-a-new-gradle-based-project-on-eclipse-neon-4-6-1).

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Friday Nov 18, 2016 at 13:17 GMT_

----

Sorry, nevermind then. If we need to parse JSON to download the list, then we need to find a way to make it work on Java 9. Maybe GSON will publish a new version.

> I'm in favour of this change because it can prevent people running into forward-compatibility issues like this.

The list should always be up-to-date. Buildship _must_ be forward compatible. When it isn't, then we did something wrong.

**Comment by donat** [comment]
<a href="https://github.com/etiennestuder"><img src="https://avatars.githubusercontent.com/u/231070?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [etiennestuder](https://github.com/etiennestuder)**
_Friday Nov 18, 2016 at 13:19 GMT_

----

+1 on dropping json if it causes issues, -1 on not downloading from services.gradle.org anymore.

The not-being-forward compatible argument I do not buy: this is an issue of Buildship if it is the case. Also, people can use the Gradle wrapper and specify _any_ version they want. We need to be able to deal with newer versions (as much as we can anticipate it).

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Friday Nov 18, 2016 at 13:33 GMT_

----

We can use an alternative JSON library:
- [json-simple](https://github.com/fangyidong/json-simple)
- [jackson](https://github.com/FasterXML/jackson)

Both uses Apache 2 licensing, so it should be fine to use.

Or, if we want to get our hands dirty, we could reuse the `ShadedJar` task from GBT. :)

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Friday Nov 18, 2016 at 13:35 GMT_

----

Let's tackle this as part of Java 9 support.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Wednesday Nov 23, 2016 at 16:59 GMT_

----

GSon 2.7 is being added to orbit: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12314
Perhaps all we have to is to upgrade.

**Comment by donat** [comment]
Related issue in Bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=498728

**Comment by sonvirgo** [comment]
Same message appears after upgrade to Java9 today in my Eclipse Version: Mars.2 (4.5.2)
Build id: M20160212-1500.

**Comment by donat** [comment]
With Java 9 officially released, this is a series issue for Buildship. We should prioritize the fix.

**Comment by donat** [comment]
Fixed in 6ff9af2813416603a4f72cc4131c797092ddc497

**Comment by chaitanyagits** [comment]
I am getting gradle buildship problem I am using Eclipse 4.13 version and buildship version: 3.x and java 11.  I am getting below error

org.eclipse.core.runtime.CoreException: SynchronizingBuildScriptUpdateListener failed
	at org.eclipse.buildship.core.internal.workspace.SynchronizingBuildScriptUpdateListener$1.visit(SynchronizingBuildScriptUpdateListener.java:74)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:67)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:77)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:51)
	at org.eclipse.buildship.core.internal.workspace.SynchronizingBuildScriptUpdateListener.visitDelta(SynchronizingBuildScriptUpdateListener.java:67)
	at org.eclipse.buildship.core.internal.workspace.SynchronizingBuildScriptUpdateListener.resourceChanged(SynchronizingBuildScriptUpdateListener.java:54)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:305)


	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5838)
	at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:108)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Can't read root project location for project located at D:\runtimebuildship\FF
	at org.eclipse.buildship.core.internal.configuration.BuildConfigurationPersistence.readPathToRoot(BuildConfigurationPersistence.java:89)
	at org.eclipse.buildship.core.internal.configuration.DefaultConfigurationManager.loadProjectConfiguration(DefaultConfigurationManager.java:113)

**Comment by donat** [comment]
@chaitanyagits Your comment is unrelated to this issue.
