### ISSUE TITLE
Migrate issues to eclipse/buildship

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#286]
Bugzilla is quite old and less accessible for the community than GitHub issues. We got the PMC's permission to do the switch so we are ready to migrate to the`eclipse/buildship` repository.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Monday Jan 30, 2017 at 17:31 GMT_

----

Github issues is now enabled for `eclipse/buildship`.

**Comment by oehme** [comment]
This is done
