### ISSUE TITLE
[CLOSED] Provide an Invocationcustomizer extension point

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#301]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [oehme](https://github.com/oehme)**
_Thursday Oct 20, 2016 at 18:53 GMT_

----

## Motivation

As discussed with Blackberry, this would allow them to implement Gradle-Maven integration in the IDE by passing workspace info into the build. This is a cheap change on our side that enables a bunch of interesting extensions (e.g. the Andmore team could pass in an init script to correctly configure the classpath for Android projects)
## Proposed Change

Add an extension point that allows implementors to supply extra arguments to all Gradle invocations

```
InvocationCustomizer {
  List<String> getExtraArguments()
}
```

Add these arguments to all invocations (sync and task execution)
## Code review
- [ ] Does the change work?
- [ ] Is the change sufficiently tested?
- [ ] Is the public API modification handled appropriately?
- [ ] Is it sufficiently documented?
- [ ] Is it implemented well?

See also the [full checklist](https://github.com/gradle/process/wiki/Process#implementation-checklist).

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Thursday Oct 20, 2016 at 18:54 GMT_

----

We should only do this if we have time left before 2.0. The Blackberry guys haven't even responded yet if they are happy with this.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Wednesday Nov 23, 2016 at 16:51 GMT_

----

The first version is added as a pull request: https://github.com/eclipse/buildship/pull/195

I thought it might be a good idea not to add it straight to master, since there might be significant amount of work before it becomes production-ready.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Thursday Dec 01, 2016 at 17:23 GMT_

----

Merged to master. @oehme If you have further comments please do it here: https://code-review.gradle.org/cru/BUILDSHIP-131

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Thursday Dec 01, 2016 at 20:04 GMT_

----

Let's not create crucible reviews when we already reviewed on GitHub.

**Comment by donat** [comment]
<a href="https://github.com/donat"><img src="https://avatars.githubusercontent.com/u/419883?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [donat](https://github.com/donat)**
_Friday Dec 02, 2016 at 08:57 GMT_

----

All right. If you are satisfied with the current state then please close this issue.

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Friday Dec 02, 2016 at 09:16 GMT_

----

Actually, there were requested changes on the review. Let's not merge things while there are requested changes. I see you fixed them in the meantime, just as a general rule for future PRs. I'd really like to get rid of Crucible and only use PRs.

**Comment by donat** [comment]
<a href="https://github.com/oehme"><img src="https://avatars.githubusercontent.com/u/1191797?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [oehme](https://github.com/oehme)**
_Wednesday Jan 04, 2017 at 10:51 GMT_

----

The remaining issues were addressed in the meantime.

**Comment by oehme** [comment]
Removed mentions of confidential customer information. @donat please go through the other moved issues and make sure there is no such information left.
