### ISSUE TITLE
Publish Buildship sources on update site

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#327]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509611

**Comment by creckord** [comment]
I've just come across this as I wanted to consume some Buildship APIs in my plugin. 

It would be a great help to have source bundles available so that target platforms can be set up to automatically associate sources with buildship dependencies.

In addition, it would help if binary bundles would include a [source reference header](https://wiki.eclipse.org/PDE/UI/SourceReferences) in their manifest pointing to the correct source revision.

**Comment by oehme** [comment]
Please note that Buildship has only a single public interface at this point (`InvocationCustomizer`). Everything else is subject to change without notice. You can follow/+1 #256 for more public APIs.

**Comment by fbricon** [comment]
Publishing the sources to the update site would **really** help us (the [jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/) project) to integrate with Buildship.

Pretty please? :-)

**Comment by fbricon** [comment]
I'll emphasize something from my previous request in BZ:

> Having the source bundles be named using the standard plugin.source_version pattern (like org.eclipse.buildship.core.source_1.0.21.v20161010-1640) will make it discoverable by https://marketplace.eclipse.org/content/pde-source-lookup

**Comment by donat** [comment]
This would require changing our internal build scripts. I'll look into it.

**Comment by donat** [comment]
Well, I would like to release Buildship 3.0 as soon as possible. IIRC you recommended me to add the `Eclipse-SourceReferences` entry to the plugin manifest, and I've implemented that. That should help your use-case, right?
Last time I checked, it worked only for the master branch though, but I'm planning to merge the release branch very soon.

**Comment by donat** [comment]
FYI I'm working on publishing the source jars at the moment.

**Comment by donat** [comment]
@fbricon The [latest snapshot](https://download.eclipse.org/buildship/updates/e410/snapshots/3.x/3.0.0.v20181205-1122-s) contains source jars. I've tested it with the pde-source-lookup, and it works for me.
