### ISSUE TITLE
Automatic Gradle project refresh when build script changes

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#335]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=488946

**Comment by adammurdoch** [comment]
It would be nice if this were driven by data or events provided by the tooling API.

For example, the tooling API might describe which files affect the build model (build scripts, settings scripts, buildSrc source and build logic, wrapper properties, script plugins, etc) and which buildship should model. This should be exactly the same information that continuous build uses.

Or the daemon might watch these files (and later network resources) and fire events via the tapi when the model may have changed.

**Comment by paulvi** [comment]
This should not however block UI, while files our downloaded.

There is problem with m2e maven integration on slow Internet connection, that make Eclipse IDE unusable while files are downloaded after pom.xml change.

**Comment by wodencafe** [comment]
Hi @donat, @oehme  I have a working implementation of this, but I wanted to ask about the Buildship Preferences Configuration Model:

![screen14](https://user-images.githubusercontent.com/9727493/31776708-e12c07e6-b4b1-11e7-9079-becd0c96a82b.png)

I would like to extend this by adding a third Checkbox at the bottom, "Automatic Refresh" or something like that, which would allow the user to turn this feature on or off. 

I see in the code where to put the new Checkbox, but I'm a bit puzzled as to how to retrieve its value from, say, an IResourceChangeListener. Could you guys point me in the right direction of storing and retrieving the value of this "Auto Refresh" Checkbox? I can then include it in the submission of my PR with this feature implemented :smile:

**Comment by donat** [comment]
@wodencafe A few weeks ago I had some free time and started to implement the same thing. I didn't finish it, but the big pieces are there: https://github.com/eclipse/buildship/compare/master...donat:donat/sync/auto-refresh

**Comment by wodencafe** [comment]
Hi @donat, thanks for this, a lot of this looks similar to what I have in my branch (After I left my previous comment, I went back and found a lot of what I was missing regarding the preference implementation):
https://github.com/wodencafe/buildship/tree/auto_refresh

I will review your code more tomorrow and see if we can merge the two together to get this feature working well :smiley:

**Comment by donat** [comment]
Cool! Btw, I've updated my comment  ⏫ .

**Comment by etiennestuder** [comment]
@donat If we add this, it must be a configuration setting to opt in to, disabled by default.

**Comment by donat** [comment]
I agree this feature has to be opt-in.

**Comment by mauromol** [comment]
Why disabled by default?

**Comment by donat** [comment]
There might be people who develop larger applications with longer configuration times. For them it might be annoying to wait for the sync every time they save the editor.

**Comment by etiennestuder** [comment]
Yep. And you might be doing build changes and do not want a reimport to happen while you are still making the changes. Sync flag off by default.

**Comment by mauromol** [comment]
Why do you talk about "reimport"? It's just a refresh...
In Eclipse "Build workplace automatically" is on by default, so every change in the build path is automatically taken up by the IDE. Current Buildship behaviour is in contrast with this. One typical example is updating from SVN and seeing that things do not compile any more just because an incoming change to build.gradle was not followed by an automatic project build path refresh. This is counter intuitive.
Also, with recent Gradle versions, a Gradle refresh is usually very fast, even with large projects. IMHO, the particular case is the opposite one, i e. When someone has a so large project that wants automatic refresh off, just like the exception is to have "Buildb automatically" off, perhaps for the same reason.

And maybe a minimum period of some configurable seconds between two refreshes may help when one presses Ctrl+S quickly multiple times...

**Comment by wodencafe** [comment]
@donat can you give me more information on this commit: https://github.com/eclipse/buildship/commit/fede6206c2d77bc9bc882c7b8075eeb89e1d0e77
Specifically, can you tell me how this additional code helps the auto refresh, and how it works in conjunction with the IRefreshChangeListener impl?

**Comment by donat** [comment]
The `IRefreshChangeListener` doesn't run in the context of the classpath synchronization. This means if you want to get the build directory location you have to consult the Tooling API for the `GradleProject` model via `ModelProvider.fetchModel()`.

Now, there is the problem at startup when the model is not yet cached (before the first synchronization). If you load the model with `FetchStrategy.FROM_CACHE` then you'll get a `null` back so you can't tell which file to look for in the refresh listener. On the other hand, if you use  `FetchStrategy.LOAD_IF_NOT_CACHED` then you'll execute a long-running TAPI operation just to get the build file location. After that, the model loading will happen again because the project synchronization executes the same thing with the `FetchStrategy.FORCE_RELOAD` parameter.

Using the `PersistentModel` is the canonical way in Buildship to access Gradle model information outside of the synchronization. Just check out the usages of the interface to see what I mean. The good thing about `PersistentModel` is that it survives the Eclipse restart, so you have the cached value of the build directory at any time. 

By the way, in my implementation I forgot to add the following safety check in the `hasBuildScriptFileChanged` method:

    PersistentModel model = CorePlugin.modelPersistence().loadModel(project);
    if (model.isPresent())  {
        return false;
    }

**Comment by wodencafe** [comment]
Hi @donat, I have been working with your branch and added the missing pieces regarding the UI and the Safety Check you mentioned.

While debugging, I see something strange, as you can see in the following screen shot:

![screenshot_20171023_141226](https://user-images.githubusercontent.com/9727493/31909169-ce7cd684-b7fe-11e7-83be-a016c0331e20.png)

When I change the build.gradle file, and the SynchronizingBuildScriptUpdateListener is notified of the change, the "buildScriptPath" from PersistentModel always shows "build", but the IResourceDelta has the file as "build.gradle", so this bit of code always returns false:

```
            IPath buildScriptPath = model.getbuildScriptPath();
            Set<IPath> affectedResourcePaths  = collectAffectedResourcePaths(deltas);
            return affectedResourcePaths.contains(buildScriptPath);
```

Do you have any idea why there is a discrepancy between "build" and "build.gradle"?

**Comment by wodencafe** [comment]
Hi @donat, thank you for pointing me in the right direction with this.

I have made some changes based on your branch, implemented the additional UI code (to only show the Auto Refresh Checkbox where applicable), added your safety check, and pushed the changes here:
https://github.com/wodencafe/buildship/commit/5a5158b0eb87c3b2ef3f6a2307223409c5c6b2dc

I updated **BuildScriptLocationUpdater** to track the build script rather than the build directory, which was causing the Build Script Path to always be "build" (the build directory).

I think all that is left is the test code, I will research how to implement these tests so we can get this feature wrapped up :)

**Comment by donat** [comment]
You have made excellent progress! I had a quick peek to the implementation and it looks good. I'll do a thorough review once you submit the pull request (this is the standard procedure for Buildship internally too). 

In the `org.eclipse.buildship.ui.test` project you'll find a couple of examples how we do functional tests. One note here: when you try to execute tests from the IDE make sure that the `Run in UI thread` option is switched off.

Sorry about the bug with the build script path, my feature branch was anything but finished.

**Comment by paulvi** [comment]
The refresh can be super quick, but downloading new dependency chain may be with speed ~1K. 
Just make sure the Eclipse is not blocked during this time (e.g.100K - 100s).

**Comment by donat** [comment]
@wodencafe Any chance you can submit a PR in the near future? Don't get me wrong, I'm not pushing you. I was just preparing the next release and I wondered whether we can include this feature.

**Comment by wodencafe** [comment]
Hey @donat, so I ran into an issue of many of the existing Unit Tests failing due to constructor changes etc, and I have been reducing the errors down from ~200 to around 5 currently. I have started the basic implementation of the first test in the outline you created, but I want to get these other failures resolved before I continue with that.

I will go ahead and push what I have for now, to give you a better idea of the current status.

**Comment by donat** [comment]
@wodencafe sure, please create the PR and I'll start with the review. I think you should fix the tests that are broken because of the internal API changes. If there's something that seems unrelated to your changes please let me know and I'll have a look.

**Comment by wodencafe** [comment]
Hi @donat, I resolved the errors and failures that I was seeing in the branch, and now I am only seeing the failures that I also see on master, so it looks like everything is good.

Here is the PR: https://github.com/eclipse/buildship/pull/613/

Please let me know if there is anything else I can help with in getting this feature merged, and thank you so much for the help!

**Comment by donat** [comment]
Awesome, I'll do a review soon.

**Comment by donat** [comment]
I've added my comments to the review. I think there's not much missing so I added this feature to the upcoming release. @wodencafe I've mentioned you in the [release notes](https://projects.eclipse.org/projects/tools.buildship/releases/2.2.0) if you don't mind :)

**Comment by wodencafe** [comment]
Hi @donat, thanks for mentioning me in the release notes! I have updated the PR and think I have all the issues solved, as well as the test cases implemented.

Please let me know if there is anything else I can help with in getting this feature implemented!

**Comment by donat** [comment]
The PR has been merged. Thank you @wodencafe!
