### ISSUE TITLE
Expand and collapse actions should target all nodes on task and executions view

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#347]
## Context 
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=509297

## Implementation
- Change the toolbar menu element labels to _Expand All_ and _Collapse All_
- use the icon provides by the platform (have a look at `org.eclipse.ui.ISharedImages#IMG_ELCL_COLLAPSEALL`, etc.), as your version is slightly brownish compared to the blueish icon used elsewhere

## Test cases
We should add coverage for the tasks and for the executions view too.
- Expand all clicked -> all nodes are expanded 
- Collapse all clicked -> no nodes are expanded
- (maybe manually verify) expand and collapse actions can be assigned to keyboard shortcuts

**Comment by AndyWu2015** [comment]
Hey @donat  , I would like to remote the expand nodes and collapse context menu in Task view and Execution view , cause Buildship are going to double-click to expand and collapse , the context menu seems not so useful.

**Comment by donat** [comment]
That makes sense to me, although it's not that simple. The executions view still doesn't respond to double-clicks by default. Besides, should we add some default message to the context menu if there are no actions associated with the current selection? The bottom line is that we should have a separate ticket for this story with a detailed spec.

**Comment by AndyWu2015** [comment]
Alad that you agree with it. I can add the double-click function to Execution view.
And I think it will be good if we just show nothing when context menu is empty.

**Comment by donat** [comment]
Please keep in mind, that the Execution view does handle double-clicks for opening test source files. 

I disagree with the empty context menu. Users should know that the context menu sometimes offers functionality, so when no action is assigned to the selection, I'd still add a disabled `no actions available` action.

**Comment by AndyWu2015** [comment]
OK.

I am ok with the "no actions available" and will do that in this issue.

**Comment by donat** [comment]
Implemented in https://github.com/eclipse/buildship/pull/551
