### ISSUE TITLE
providedCompile not converted to a dependency

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#358]
Original post: https://bugs.eclipse.org/bugs/show_bug.cgi?id=511928

**Comment by i23098** [comment]
Just copy-pasting the original text from https://bugs.eclipse.org/bugs/show_bug.cgi?id=511928

I have a project that requires servlet-api.jar. That is provided by the application container, so in my gradle file I have in the  dependencies:
    providedCompile libraries.servletapi

It compiles correctly on the command line, and the jar file is not added to the generated war file, as expected.

On eclipse, I refresh the project, and it gives compilations errors "The type javax.servlet.ServletContext cannot be resolved. It is indirectly referenced from required .class files" and similar...

I have to change the providedCompile into compile, refresh gradle project, and put it back to providedCompile for it to work. I have to remember to do this every time there's some change in the gradle file...

**Comment by oehme** [comment]
Could you please provide a small example project on GitHub?

**Comment by i23098** [comment]
Sure: https://github.com/i23098/buildship_bug_358

Actually my bug report has a bug. I though that the project in question was a war but when trying to build a small example, it was actually working :) The issue occurs if the project is a jar.

One can argue that jar files don't include other jars, so dependencies should be declared as compile, not providedCompile. But, the truth is that the project builds successfully on the command line (./gradlew build). Eclipse+Buildship should be able to correctly import the project.

**Comment by oehme** [comment]
This:

`sourceSets.main.compileClasspath += configurations.providedCompile`

is the wrong abstraction layer. SourceSet.compileClasspath is a simple `FileCollection` that the `eclipse` plugin cannot analyze. The `eclipse` plugin works only on the level of `Configurations` (so it can query for source attachments etc.). If you wanted to stick with this, you would have to additionally add it to the eclipse classpath like this: `eclipse.classpath.plusConfigurations << configurations.providedCompile`.

However, there is a cleaner way to model this, by wiring your configuration at the right point in the configuration hierarchy:

`configurations.compileClasspath.extendsFrom(configurations.providedCompile)`.

Then, both the compiler and Eclipse plugin will see it.

However, this is **exactly** the same as the `compileOnly` configuration that Gradle already has. So I recommend you just use that one and remove the custom code :)

**Comment by i23098** [comment]
Thanks. Will take a look into your suggestions.

**Comment by donat** [comment]
@oehme  Wouldn't it make sense to do `eclipse.classpath.plusConfigurations << configurations.providedCompile` automatically? For web projects, the `eclipse-wtp` plugin could do that.

**Comment by oehme** [comment]
It already does. Have a look at the [example](https://github.com/i23098/buildship_bug/commit/986bf709bca17e03a3e042c33c8c635bf8342860#diff-c197962302397baf3a4cc36463dce5eaR1), the user was building their own "providedCompile" concept.

**Comment by donat** [comment]
Ah, I see, thanks!
