### ISSUE TITLE
Double entries in launchers list and search list

### ISSUE THREAD

**Issue by jdelouche** [eclipse/buildship#367]
Hello,

When using a parent project, the eclipse launchers are seen twice in the launcher list.
Same issue when searching an item with Ctrl - Shift - R, the resources found are seen from the parent and from the project path as follows :
parent/project
project

Jean-Pierre

**Comment by jdelouche** [comment]
Hello,

When using two cascaded projects,  the eclipse launchers are seen 4 times.
This is quite annoying for people using this every day.

Thanks for your help,

Jean-Pierre

**Comment by oehme** [comment]
Can you please provide a screenshot of what you are seeing twice? That would be super helpful! :)

**Comment by jdelouche** [comment]
![image](https://cloud.githubusercontent.com/assets/1420839/23457009/26fc6984-fe76-11e6-9468-58aad1611358.png)

**Comment by jdelouche** [comment]
In the sceenshot the Sn_Server_Stop.launch file is seen four times in the Java Application menu.
The gradle project has four levels of directories from top gradle parent to bottom gradle child as seen in the gradle tasks window, AsnSnTop/AsnSn/asn-sn-parent/asn-sn-server. The launcher file is defined in asn-sn-server.
The gradle projects are as follows, there is a build.gradle in the AsnSnTop directory and in the AsnSnTop/AsnSn/asn-sn-parent. There only three levels of gradle projects, 1) AsnSnTop, 2) asn-sn-parent & 3) children projects defined at the previous level.
Note: each of the four items in the menu leads to the same launcher file.

**Comment by oehme** [comment]
I'm afraid there is not much we can do here, Eclipse still doesn't "understand" hierarchical project layouts properly. 

The "open resource" dialog has a "hide duplicates" option which does what you want. But the launch configuration dialog doesn't have the same behavior. You might want to open a bug on the Eclipse platform project.

**Comment by jdelouche** [comment]
Just did what you suggested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=512873

**Comment by oehme** [comment]
Closing since we can't fix this on our side.
