### ISSUE TITLE
How to tie into the Gradle -> Refresh Gradle Project event

### ISSUE THREAD

**Issue by edeandrea** [eclipse/buildship#368]
Is there something I can do within a build file or a plugin where I can tie into the Gradle -> Refresh Gradle project event?

With the STS Gradle IDE, this event used to trigger the eclipseProject task that a plugin author could add finalizedBy tasks to so that other custom tasks could be run when the event was triggered (for example - generating JAXB sources off of .wsdl/.xsd schemas). I'd like to be able to provide similar functionality when the user right-clicks and chooses Gradle -> Refresh Gradle Project.

I don't want to have to develop an Eclipse plugin - I'd like to be able to have a hook via some task or something within the Gradle project model that gets triggered.

**Comment by oehme** [comment]
Not yet, see #265 and #266. These are not on our priority list at the moment, but we are open for contributions.

**Comment by edeandrea** [comment]
Thank you for the quick reply. I'll see about a contribution.
