### ISSUE TITLE
Buildship / Oomph Support

### ISSUE THREAD

**Issue by rwinch** [eclipse/buildship#376]
It would be good to create [Oomph](https://projects.eclipse.org/projects/tools.oomph) / Buildship support. This was originally discussed on [discuss](https://discuss.gradle.org/t/buildship-tasks-for-oomph/21104/6), but I crated this ticket to track the progress.

I work on Spring framework and I view Oomph support critical to get more users contributing and making it as easy as possible to run sample applications.

**Comment by oehme** [comment]
As mentioned on the forum, this probably needs to be done in Oomph, not in Buildship. If Oomph has some way to contribute a custom importer, then this should be pretty simple.

**Comment by rwinch** [comment]
Thanks for the fast reply. Wouldn't Oomph still be waiting on Public APIs or is that now available?

Perhaps this issue need to be create public APIs for Oomph?

**Comment by oehme** [comment]
If oomph can call a command on a project then it could use the "Add Gradle Nature" command which is public. If it needs a programmatic import API, then you are right, we would need a public and stable one for that.

**Comment by fraenkelc** [comment]
I wrote https://github.com/fraenkelc/buildship3_setuptask a while ago and it works and has some downloads (~80 for the most recent version, I didn't actively advertise it anywhere). Since there looks to be at least some interest in this still would it make sense to add a oomph setup task to buildship?

**Comment by fraenkelc** [comment]
I've got a pull request for this in the works, based partially on my already existing plugin

**Comment by donat** [comment]
Implemented in #892 .
