### ISSUE TITLE
Buildship support for AspectJ

### ISSUE THREAD

**Issue by rwinch** [eclipse/buildship#377]
Please add AspectJ support to Buildship. If it is supported, please add some documentation (or point me to some documentation) on how to leverage it properly. 

From my perspective, the integration should not require a custom Eclipse plugin to be written by the community.

**NOTE** This is possibly related to #326 but a reduced scope.

**Comment by oehme** [comment]
Hey Rob,

what special support does AspectJ need? Buildship takes whatever is configured in the `eclipse {}` model in a build. So if there is an AspectJ Gradle plugin (there is one I assume?), it should add the relevant project natures/builders there.

**Comment by rwinch** [comment]
Thanks for the reply.

It needs a way to know what projects are part of the aspectpath. [This is what I currently ](https://github.com/spring-projects/spring-security/blob/9c03571bbbe74aa44d801904798e0dd165dd251f/buildSrc/src/main/groovy/aspectj/AspectJPlugin.groovy#L84) use for the old STS Gradle plugin which allowed modifying the files directly.

**Comment by oehme** [comment]
The whenMerged hook works for Buildship as well. It doesn't actually modify a file, it works on a model. The only thing that doesn't work in Buildship is withXml.

This is supported since Buildship 1.0.18 and Gradle 3.0

**Comment by oehme** [comment]
Unrelated tip: That code shouldn't read what plugins the other projects have. Instead it should iterate over the aspectPath configuration and mark all the project dependencies it finds on it with the right attribute in the Eclipse classpath. In general projects should not be reaching into the configuration of other projects.

**Comment by oehme** [comment]
@rwinch is there anything else needed on the Buildship side? Could you please close this issue otherwise?

**Comment by rwinch** [comment]
I haven't verified it is all there yet. I guess if you like I can close and reopen if I run into issues. What is your preference?

**Comment by oehme** [comment]
Feel free to reopen if there are any issues :+1:
