### ISSUE TITLE
User can enable scan creation on a run configuration

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#378]
In the Gradle run configurations page (under the tasks) we should define a new group with the name `Build Flags`. Inside the group, there should be two checkboxes:
- Override workspace settings
- Enable Build Scans
The Build Scans checkbox should be disabled by default and should reflect the workspace settings. If the Override option is enabled, build scans should be enabled. If scans are enabled, the `-Dscan` JVM argument should be added to the execution.
If the workspace and the run configuration are both set to publish build scans still only one `-Dscan` should be added to the JVM  arguments.

**Comment by oehme** [comment]
I would do the same as we do for `--offline` first (i.e. workspace and run config settings are simply concatenated). Then introduce the "overwrite workspace settings" checkbox as part of #382.

**Comment by donat** [comment]
That is already covered by https://github.com/eclipse/buildship/issues/379.

**Comment by oehme** [comment]
This issue currently says we should have an overwrite checkbox in the first iteration. I think we shouldn't. We should start with exactly the same behavior as we currently have for `--offline` and make the overwrite checkbox part of another story instead of bundling them together in this story.

**Comment by donat** [comment]
And that's the case, only the ordering is not correct. There's nothing on the UI for `--offline ` atm. First, #379 will be implemented which will make build scans behave just like the offline mode currently. Then comes this issue, then the ones implementing the project scope preferences.

**Comment by oehme** [comment]
Oh I thought we already had a `--offline` switch in the run configuration section. I just remembered us having problems with workspace and run configuration settings before, but I guess that was just a persistence issue, not a UI issue.
