### ISSUE TITLE
User can re-configure Gradle version on the project preference page

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#381]
After #380 introduces a project preference page, we should let the user change the Gradle distribution for the project there. Applying a new Gradle distribution should trigger the synchronization.

**Comment by oehme** [comment]
We don't need an extra button. Clicking apply/ok should trigger a synchronization.

**Comment by donat** [comment]
👍 
I adjusted the text.

**Comment by donat** [comment]
Implemented in #484
