### ISSUE TITLE
Opening / Closing Projects Should Refresh Gradle Tasks View

### ISSUE THREAD

**Issue by rwinch** [eclipse/buildship#385]
Currently Projects that are opened / closed do not automatically get added / removed from the Gradle Tasks View. It would be nice if the view was automatically updated.

A workaround is to click the refresh button.

**Comment by aram535** [comment]
Just a note, that the work around does not work either.  You have to restart eclipse.

**Comment by donat** [comment]
Fixed in Buildship 3.0 via https://github.com/eclipse/buildship/pull/792.
