### ISSUE TITLE
How to turn up logging when doing Gradle -> Refresh Gradle Project

### ISSUE THREAD

**Issue by edeandrea** [eclipse/buildship#387]
I'm having an issue when doing the Refresh Gradle Project where the Project & External Libraries container is showing up empty. I'm trying to debug what the issue might be and it would be helpful to pass the -d or -s flag when performing this. Is there a way to do that?

**Comment by oehme** [comment]
There is no way to increase the logging level at the moment, but low level logs are unlikely to give you insight into that specific issue anyway. Just dropping some println statements in there should help, e.g. 

```
eclipse.classpath.file.whenMerged {
  entries.each { println it.path }
}
```

**Comment by edeandrea** [comment]
Thanks for the tip - that pointed me to my issue. I had configured a pathVariable in the eclipse configuration but never set it up in eclipse itself.

Thanks for the quick reply!
