### ISSUE TITLE
Replace `-Dscan`  with `--scan` for all build invocations

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#388]
Starting with Gradle 3.4 and scan plugin 1.6 a deprecation warning is shown, saying "Use --scan instead". On the other hand, `--scan` causes a build failure if the build scan plugin is not applied on the project. We should find a way to use `--scans` without making any builds fail.

**Comment by oehme** [comment]
@breskeby any guidance on this would be appreciated

**Comment by breskeby** [comment]
Can you elaborate a bit whats intended here? is this a flag in Buildship you can set? Currently there is no way to use --scan and not fail if the plugin is applied. What we could do is applying the buildscan plugin automatically (e.g. via init script) when this option is selected.
WDYT?

**Comment by oehme** [comment]
@breskeby We wan to have a checkbox in Buildship which activates scan scan publishing. We want it to work with all of:

- projects without the scan plugin (just do nothing or apply the scan plugin, either would be acceptable at this point)
- projects with old scan plugin versions
- projects with new scan plugin versions

**Comment by breskeby** [comment]
there are quite some possible permutation of versions for gradle and scan plugin version here to be taken into account
- gradle < 3.4 || plugin version < 1.5 -> "-Dscan"
- gradle >= 3.4 && plugin >= 1.5 -> "--scan"

The tricky part is to figure out if (and which version) of the build scan plugin is already applied. The check that let's Gradle fail is implemented in a projectsEvaluated hook. So you'd be able to put the check into a rootProject.afterEvaluate{} but then you run into the next problem: 

If you see at this point (in the afterEvaluate block) that the plugin wasn't applied yet it is quite to late to auto apply it at this stage. I don't recall, but does the Gradle build model provide you with information about applied plugins? I guess the most idiomatic way here would be to request a model from Gradle that gives you the information of the applied plugins and buildship can make further decisions based on that information (like applying the plugin automatically and/or which flag to choose.)

This would probably require further work in Gradle tapi to get that model right. As a solution without the need to change Gradle core I think there are currently two options:

1. keep using `-Dscan` for now and mark that deprecation warning as known issue
2. use `-Dscan` or `--scan` (depending on the gradle version) and auto apply the latest build scan plugin via init script. (taking the risk a different plugin version was applied in the build script already which leads also to a warning that the plugin has been applied twice.

In general I really think Gradle should provide a model with information about the plugins being applied.

**Comment by etiennestuder** [comment]
@breskeby Receiving plugin info via TAPI model has been a long-outstanding thing on the Buildship. I'm not saying that this justifies adding it for the problem above. Maybe.

To make progress, I would go with `-Dscan` at least initially.

**Comment by oehme** [comment]
Fetching a model to know what switches I can pass creates a chicken and egg problem. It's also a performance/ux problem because I would have to check before every request. The plugin might no longer be applied.

Applying the scan plugin from Buildship would require us to add a license opt-in screen which would be more stuff in the IDE which actually belongs into the build.

Imho Gradle should not fail but only print a warning when --scan is used without the scan plugin. The warning could contain instructions how to add the plugin to your build.

We'll use -Dscan for now, but we wanted to bring this problem up rather sooner than later.
