### ISSUE TITLE
Provide some feedback when  .settings/org.eclipse.buildship.core.prefs is missing

### ISSUE THREAD

**Issue by lukeu** [eclipse/buildship#390]
**Symptom:** Buildship has been running fine at work. Get home, and while Gradle > Update Project _appears_ to work (no problem is reported): dependencies are not added to my Eclipse Project, nor downloaded.

The now-known **cause** (after reading [bug 498069](https://bugs.eclipse.org/bugs/show_bug.cgi?id=498069) is that I didn't commit this prefs file to git after retrofitting my Eclipse project with a Gradle build. The thinking went that since this is in a hidden folder then it must be some working data and/or local user preference (as opposed to some hard-requirement for the project to function).

The **suggestion** would be firstly to show an error dialog rather than silence which implies success. For bonus points it would be nice if it could be manually fixed somehow - e.g. by the `Configure > Add Gradle Nature` menu item.

(On a related note: I know the precedent seems to be to only have an 'add nature' action, but I've often felt there are some good use cases for 'remove nature' actions too: trying things out, fixing things up.)

**Comment by lukeu** [comment]
The **workaround** was to checkout an earlier revision, add the gradle nature again, and keep a copy the file to squash into the "add gradle" commit. Yay for version control.

**Comment by oehme** [comment]
This is due to Buildship 2.0 accidentally removing the Buildship builder, which is responsible for checking the presence of the preference file. This is fixed for 2.0.1

**Comment by donat** [comment]
FTR here's the original issue: https://github.com/eclipse/buildship/issues/288.

**Comment by lukeu** [comment]
Thanks for the info. Just to note, I had never noticed the Gradle builder missing (I'd opened that properties dialog a few times). But it was always second, under the Java builder.
