### ISSUE TITLE
Adding Gradle to existing eclipse projects is not supported / Java Build Path -> Add Library...

### ISSUE THREAD

**Issue by smarkwell** [eclipse/buildship#391]
When a Gradle Project is setup in eclipse it add a Library section to Java projects called "Project and External Dependencies".

With Maven or IvyDE, this Library can be added after the project is already loaded into eclipse by going to the Java Build Path -> Libraries -> Add Library... section.

It would be nice if Buildship could do this as well.

**Comment by oehme** [comment]
What exactly is the use case? The container is *always* added when a project is converted to a Gradle project (and it will be re-added if removed for some reason). It makes no sense to have that container on non-Gradle projects since it would be empty.

**Comment by oehme** [comment]
Closing as there was no further feedback.
