### ISSUE TITLE
Import existing project: java.io.IOException: Read-only file system

### ISSUE THREAD

**Issue by netcrack** [eclipse/buildship#394]
I am trying to import an existing project which has the following task

`task createBuildInfo {
    Properties props = new Properties()
    def propsFile = new File("src/main/resources/buildinfo.properties")
    if (!propsFile.exists()) {
            propsFile.createNewFile()
    }
    props.load propsFile.newDataInputStream()
    props.setProperty "buildId", "$gitHash"
    props.store propsFile.newWriter(), null
}`

But while importing I am getting the following exception

[stacktrace.txt](https://github.com/eclipse/buildship/files/792767/stacktrace.txt)

I am not sure why the task **createBuildInfo** is being executed while importing the project.

**Comment by oehme** [comment]
You are executing this code at configuration time. You should wrap the logic in a `doLast {}` block. Please have a look at the [user guide](https://docs.gradle.org/current/userguide/tutorial_using_tasks.html) for more information.
