### ISSUE TITLE
Resource and derived resource (class file) showing twice using subprojects

### ISSUE THREAD

**Issue by i23098** [eclipse/buildship#398]
I created a project with a subproject, tried to open Resource (Ctrl+Shift+R) and searched for A (the only class there). I shows up 4 results: A.java twice and A.class twice, 2 from the top project, and 2 from the subproject. Better see it than explain :) http://img4.imagetitan.com/img.php?image=15_subprojectsbuildship.png

I would expect only one result to show up: A.java from the subproject.

There's a small test project available at https://github.com/i23098/buildship_bug

**Comment by oehme** [comment]
There is a "Hide duplicates" option in the open resource dialog. Unfortunately this is still not the default ;)

**Comment by i23098** [comment]
It does hide the duplicate A.java, but the class files still show...

**Comment by oehme** [comment]
That's another [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=491085) in Eclipse. Nothing we can do on the Buildship side unfortunately :(

**Comment by i23098** [comment]
But if I select to show "Gradle subprojects" in the "Package Explorer", then I do properties in the main project subproj/bin and subprob/build folders, they are not marked as derived. If I do tick it, then Open Resource dialog works correctly... until I do a gradlew clean or so...

I believe that buildship plugin should be setting that derived property

**Comment by oehme** [comment]
I guess we could work around this bug by checking whether subprojects are physically contained and add their derived resources to the list of the parent's derived resources and mark them all.

**Comment by i23098** [comment]
Somehow related, when searching for a file (Search -> File), they show twice in the Results table. -> http://img4.imagetitan.com/img.php?image=15_multiplesearchresults.png

In the Package Explorer, I have the filters to hide Gradle subprojects -> http://img4.imagetitan.com/img.php?image=15_javafilters.png

When selecting that option, Eclipse should ignore the subprojects (in the main project) for everything (be it Open Resource, Search, or some other option that goes through the project files)

**Comment by oehme** [comment]
> When selecting that option, Eclipse should ignore the subprojects (in the main project) for everything (be it Open Resource, Search, or some other option that goes through the project files)

Unfortunately we have no control over that. That filter is a UI feature that only affects the package explorer and nothing else. Eclipse does not really "understand" hierarchical project layouts.

**Comment by ericnondahl** [comment]
Is the fix for showing the class files in "Open Resource" pending the still-open eclipse [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=491085)? Or was the work-around added to a Buildship release? I'm still seeing the behavior in Buildship 2.0.2 - expected?

**Comment by oehme** [comment]
The workaround mentioned above will be in Buildship 2.1. We'll push out a milestone soon.

**Comment by adrian-baker** [comment]
I'm still seeing class files of subprojects in the "Open Resource" dialog in 2.1.2.v20170807-1324.

**Comment by oehme** [comment]
@adrian-baker please provide a reproducible example

**Comment by oehme** [comment]
That's the `bin` folder, which JDT should handle, not Buildship. Could you open a bug for JDT?

**Comment by ChristianCiach** [comment]
@oehme 
I don't think this should be handled by JDT, because the Gradle-Root-Project (which bin-folder is shown in the "open resource" dialog) is not a Java-project. It doesn't have a java-nature and thus is not handled by JDT.

**Comment by ChristianCiach** [comment]
I believe this issue to be closely related with the fact, that "File search" results are listed twice: Once under the gradle-root-project and once under the subproject. This is mildly infuriating.

**Comment by oehme** [comment]
This is JDT-related, because it is not handling nested projects correctly. The bin folder in the root project should not be shown, because it is already shown in the also imported subproject. That's completely unrelated to Gradle and happens with any nested project structure.

**Comment by CrushaKRool** [comment]
Hopefully I am not missing something that's already been considered, but I still noticed the issue in Buildship 2.2.2 (snapshot). Not only when listing resources but also with other things like
- multiple launch configuration entries if the .launch files are in subprojects
- duplicate search results for resources in subprojects, as also described in this post: https://discuss.gradle.org/t/eclipse-search-annoyance-with-gradle-subprojects/21624

I believe the solution to these problems could be to add a resource filter to each project that excludes all Gradle-subprojects. In fact, this is something the old Gradle STS plugin did automatically upon import
![resourcefilter](https://user-images.githubusercontent.com/7923164/44717037-3b48cb00-aabc-11e8-89ec-edd730d2570c.png)
while Buildship is not doing anything here at the time.
Adding these filters manually did get rid of the duplicate search results when I tested it. Or is there a good reason for Buildship to not add these filters?

**Comment by kai2nenobu** [comment]
I noticed that gradle can add Eclipse resource filters by using [EclipseProject.html#resourceFilter](https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/eclipse/model/EclipseProject.html#resourceFilter-org.gradle.api.Action-).

To add resource filters for all subprojects, `build.gradle` are like below.
(This code assumes recursive subprojects don't exist. If exist, some more work may be required.)

```gradle
apply plugin: 'eclipse'

subprojects {
  apply plugin: 'java'
  apply plugin: 'eclipse'
}

eclipse.project {
  project.subprojects.each { subproject ->
    def relPath = project.relativePath(subproject.projectDir)
    resourceFilter {
      appliesTo = 'FOLDERS'
      type = 'EXCLUDE_ALL'
      matcher {
        id = 'org.eclipse.ui.ide.multiFilter'
        arguments = "1.0-projectRelativePath-matches-false-false-${relPath}"
      }
    }
  }
}
```

When execute `eclipseProject` task, `.project` including resource filters is generated.
Then derived resources are not shown in `Open Resource`, and search results don't duplicate.

Unfortunatelly, buildship is not aware of `EclipseProject#resourceFilter`, so you need to
execute `eclipseProject` task manually at this time. If #271 will be resolved,
it may be done automatically.
