### ISSUE TITLE
Reimporting existing projects ignore Gradle distribution changes

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#399]
Consider the following steps
- Create a new Gradle project with `wrapper` distribution
- Delete the project from the workspace
- Import the same project with `3.4` distribution

As a result, the imported project will still use the `wrapper` distribution. The `.settings/org.eclipse.buildship.core.prefs` file contains `GRADLE_DISTRIBUTION(WRAPPER)`.

**Comment by donat** [comment]
This seems something we should fix in the 2.0.1 release.

**Comment by donat** [comment]
Here's what happens: because we refresh the project in the project synchronization, the Gradle classpath updater kicks in and initiates a refresh. But, because the existing configuration contains an outdated distribution, the `SynchronizeGradleBuildsJob.isCoveredBy` will returns `false` and two synchronization runs in parallel.

**Comment by oehme** [comment]
This is probably caused by the fact that we now delete the persistent data when the project is deleted, so the container initializer no longer has an "old state" that it can reuse.

I think the initializer should not run at all when a synchronization is running. A simple ThreadLocal might help detect this.

**Comment by donat** [comment]
We can fix it if `SynchronizeGradleBuildsJob.isCoveredBy` would only compare the root projects rather than the equality of the `GradleBuild`s.

**Comment by donat** [comment]
(ups, wrong button; reopened)

**Comment by oehme** [comment]
> We can fix it if SynchronizeGradleBuildsJob.isCoveredBy would only compare the root projects rather than the equality of the GradleBuilds.

If we did that, then we'd ignore an attempt to change settings if some other job just happened to be running in the backgorund.

**Comment by donat** [comment]
We can check if a sync job is running with the following snippet:
```
    private boolean isSyncRunning(File file) {
        Job[] allJobs = Job.getJobManager().find(null);
        for (Job job : allJobs) {
            if (job instanceof SynchronizeGradleBuildsJob) {
                for (GradleBuild gradleBuild : ((SynchronizeGradleBuildsJob) job).getBuilds()) {
                    if (gradleBuild.getRequestAttributes().getProjectDir().equals(file)) {
                        return true;
                    }
                }
            }
        }
        return false;
    }
```
I wonder if we should add it as a new method to the `GradleBuild` interface.

**Comment by oehme** [comment]
I guess that should work. I think we have (had?) a job family so you don't need to iterate over all jobs.

**Comment by oehme** [comment]
LGTM.
