### ISSUE TITLE
Eclipse WTP support not working

### ISSUE THREAD

**Issue by ruschka** [eclipse/buildship#405]
I think there is a bug in Buildship 2.0.1 because test dependencies are published/exported to WEB-INF/lib folder. If I try version 1.0.21 it works fine.

**Comment by donat** [comment]
I created a demo web project, but the test dependencies were not exported to `WEB-INF/lib` for me. Can you please create a sample project exhibiting the problem?

**Comment by oehme** [comment]
Closing since there was no feedback.
