### ISSUE TITLE
Classpath container serialization should not use platform encoding

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#406]
The classpath container is serialized with `UTF-8` and loaded with the platform encoding. 

AERI report exhibiting the problem: https://dev.eclipse.org/recommenders/committers/aeri/v2/#!/problems/58b00a53e4b0b20241269e8d

**Comment by donat** [comment]
Commit containing the fix: https://github.com/eclipse/buildship/commit/7a9ba6857046e715b24287306878cf8ac4e95937

**Comment by oehme** [comment]
LGTM.
