### ISSUE TITLE
Gradle Tasks - truncated names

### ISSUE THREAD

**Issue by rmundkowsky** [eclipse/buildship#407]
The task names in the "Gradle Task" window are truncated to looks likes about 26 characters. See picture below.  This is on Windows 8.1, Eclipse NEON.1, and Buildship 2.0.0. Also would be nice if there was a way to filter which project/s are shown in the "Gradle Task" window.

![image](https://cloud.githubusercontent.com/assets/10341863/23410885/aec2c788-fd9e-11e6-861a-ebde3f671de4.png)

**Comment by oehme** [comment]
There is an option to show the column headers and then you can resize them. 

@donat I think we should show the headers by default, this is confusing many people. I'm not even sure it is useful to have this toggle at all.

**Comment by rmundkowsky** [comment]
thanks! I did not see the arrow for the options on the right side.

**Comment by donat** [comment]
Originally we hid the header simply because it looks ugly. I think, there's a better way: automatically update the column sizes if the content doesn't fit. I remember I've already seen a snippet that exactly does and it's not a huge deal to implement.

**Comment by rmundkowsky** [comment]
As a developer, I do not use Eclipse, because it is pretty nor has a nice user interface. It just has functionality to make my life easier.  As an analogy, do you think users like Microsoft Windows 7 or 8/10?  People hate 8 and 10, because Microsoft tries to hide things to make things easier to use.

**Comment by rmundkowsky** [comment]
I should note, it is nice that you tried to make things look nice.  But in this case, I think ease of use is more helpful.

**Comment by simark** [comment]
I just had the same problem:

http://nova.polymtl.ca/~simark/ss/filednKcic.png

**Comment by kittaakos** [comment]
@simark Could you please add another screenshot with the latest Buildship version. It has the same problem. Additionally, please confirm, you are on GTK. Could be an SWT problem.

**Comment by kittaakos** [comment]
Also, I can confirm; this works fine on OS X.

**Comment by simark** [comment]
Right, I should have provided information about my setup.

 * Buildship: Eclipse Plug-ins for Gradle: 2.0.1.v20170220-1742-m
 * Ubuntu 14.04, x86-64  
 * I'm launching Eclipse with `SWT_GTK3=0`.

**Comment by rmundkowsky** [comment]
Just to be clear, there was no bug or error. It is just that they default to small column width and you have to change the options to make the column wider.

**Comment by donat** [comment]
We enabled the table header by default in Buildship 2.1 (See #475).

**Comment by rmundkowsky** [comment]
thanks!
