### ISSUE TITLE
Fixed and Transient attributes should be able to apply themselves on TAPI configuration objects

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#410]
Ideally, Fixed/Transient attributes should have methods to apply themselves to GradleConnector/ProjectConnection/ConfigurableLauncher, so we don't need to repeat ourselves.

**Comment by oehme** [comment]
Note that another option might be to remove these two classes or replace them with something else in Buildship. There really isn't anything "fixed" about JVM args for instance, they can be set differently on each invocation if needed. The only "fixed" things on a conneciton are project dir and Gradle distribution.

**Comment by oehme** [comment]
This is superseded by our `BuildConfiguration`/`ProjectConfiguration`/`RunConfiguration` classes.
