### ISSUE TITLE
Kotlin templateClasspath should not require starting a daemon

### ISSUE THREAD

**Issue by oehme** [eclipse/buildship#412]
The classpath of the template is just the content of the distribution's lib folder. This can be found using just the `BuildEnvironment` model. This means we don't need any dependency on GSK in Buildship.

**Comment by oehme** [comment]
I have exchanged this issue with another bug that I moved back to the backlog. I think giving the JetBrains team quick feedback on the overhauled API is more important.

**Comment by donat** [comment]
I managed to get rid of the GSK dependency: https://github.com/eclipse/buildship/commit/cb3ecc20df79b6c38b6ca11e6fc376b918d996b8

There's one item left: how to find the classes for the accessors (e.g. for `application { ... }` blocks).  The relevant classes live in the ` ${gradleUserHome}/caches/3.5-20170305000422+0000/gradle-script-kotlin/${scriptMd5Hash}` folder and I'm not sure if we can calculate correclty without invoking GSK.

**Comment by oehme** [comment]
> There's one item left: how to find the classes for the accessors (e.g. for application { ... } blocks). 

These are only required for actually compiling the script, not for loading the template. That's what GSK's ScriptDependenciesProvider is there for.

**Comment by donat** [comment]
We actually want to query the Kotlin classpath via the TAPI and pass it directly to the compiler. For that we need https://github.com/gradle/gradle-script-kotlin/issues/293 to be implemented.
