### ISSUE TITLE
Prefer --scan over -Dscan for build scan support

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#416]
The build scan plugin deprecated the usage of the `-Dscan` argument the behavior of `--scan` has been altered. Buildship should prefer using `--scan` when possible. As explained at https://code-review.gradle.org/cru/REVIEW-6465 Buildship should apply the following logic:

- for 3.3 and below, use `-Dscan` (since `--scan` was introduced in 3.4) 
- for 3.4, I would say use `-Dscan` too, and live with the deprecation warning (since using `--scan` might cause the build to fail if the build scan plugin is not applied) 
- for 3.5+ use `--scan`

**Comment by donat** [comment]
I'm struggling with the implementation approach what we discussed during our last meeting. if I implement the feature only for the run configuration, then the process is simple: query the `BuildEnvironment` model, select the proper argument and launch the build.

However, how'd you do the same with the model synchronization? First, you have to query the `BuildEnvironment` model without the arguments to calculate the proper `FixedRequestAttributes`, but you need the `FixedRequestAttributes` to execute the query.  Catch 22. 

I'm thinking about replacing the `GradleBuild` instance at the beginning of the project synchronization to have the proper arguments. Any other ideas on this?

**Comment by donat** [comment]
Or maybe we could save/update the version upon synchronization and store it in the persistent properties.

**Comment by oehme** [comment]
Keep in mind that querying the build environment does not require any parameters, as it runs completely in-process. So there should be no problem here. You can hide this completely inside the logic that creates `ModelBuilder`/`BuildLauncher` instances.

**Comment by donat** [comment]
Should the `--scan` have any effect on the model loading? I see a warning if the build scan plugin is not applied but no build scans are published when the plugin is applied.

**Comment by oehme** [comment]
I would have assumed that it should publish scans when loading models too. If it doesn't that would be a bug. Loading a model is also just a kind of "build".

**Comment by donat** [comment]
I'll ask the CS team about it.

**Comment by donat** [comment]
I've had a chat wit @etiennestuder on the subject. Turns out that build scans are disabled for the model loading as the exact behavior is not yet well-defined. 

Relevant code snippets:
https://github.com/gradle/dotcom/blob/c52e2deaaf24f1bba2f9cf24d8ecdcdeb21287ef/scans-plugin-test-func/src/test/groovy/com/gradle/scan/plugin/test/func/ToolingModelBuildingPluginFuncTest.groovy#L40
https://github.com/gradle/dotcom/blob/3f522609a7490969148ee4350eb574b06929f34a/scans-plugin/src/main/java/com/gradle/scan/plugin/BuildScanPlugin.java#L510-L510

**Comment by etiennestuder** [comment]
It was never a priority so far and we do not want to enable something for which we have not well-defined the expected behavior.

**Comment by oehme** [comment]
It's not urgent right now, but I think all of Eclipse, IDEA and Android Studio would benefit from this.
