### ISSUE TITLE
Project Explorer filter Gradle sub projects not working in Linux

### ISSUE THREAD

**Issue by i23098** [eclipse/buildship#419]
I recently moved from Windows 7 to Fedora 25, and can't remember if this was ever working in Linux or not (was ok in Windows for sure). I use Eclipse Java EE IDE for Web Developers, neon.2 with openjdk8 1.8.0_121-b14.

I created a new workspace, cloned my simple project at https://github.com/i23098/buildship_bug and Import Existing Gradle Project in eclipse. In Package Explorer, click the "little down arrow" and tick to filter "Gradle sub projects". On the main builship_project, the subproj directory is still shown.

**Comment by donat** [comment]
I was able to reproduce the issue. Seems like it's a regression in the project synchronization logic.
