### ISSUE TITLE
Gradle tasks not shown

### ISSUE THREAD

**Issue by jeusdi** [eclipse/buildship#420]
I've a gradle project structure and I'm using eclipse. I've installed gradle plugin for eclipse.

However tasks aren't shown in Gradle Tasks Panel, so I'm not able to launch these ones.

    project/
       build.gradle
       settings.gradle
       .project
       .classpath

I'm able to perform any task using command line.

Any ideas?

**Comment by donat** [comment]
I'm guessing that you've used the `eclipse` task to initialize your project and then imported it to Eclipse as a general project. You should use the 'Import Existing Gradle Project' wizard from Eclipse to be able to use the Gradle Tasks view.

**Comment by oehme** [comment]
Closing as there was no further feedback.
