### ISSUE TITLE
Add support for external annotations 

### ISSUE THREAD

**Issue by ChristianCiach** [eclipse/buildship#421]
It seems buildship currently has no support for [external annotations](https://wiki.eclipse.org/JDT_Core/Null_Analysis/External_Annotations). 

It works if I add them manually using the "Java build path" dialog, resulting in an added attribute in the ".classpath" file:
```
<classpath>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer">
		<attributes>
			<attribute name="annotationpath" value="/path/to/annotations"/>
		</attributes>
	</classpathentry>
</classpath>
```

Unfortunately, the added attribute is gone as soon as I use "Gradle -> Refresh Gradle Project" on the project.

**Comment by donat** [comment]
If your project is using Gradle 3.0+ then you can customize the classpath attributes from the build script:

```
apply plugin: 'java'
apply plugin: 'eclipse'

eclipse {
    classpath {
      containers 'org.eclipse.buildship.core.gradleclasspathcontainer'  
      file {
            whenMerged {
                def source = entries.find { it.path == 'org.eclipse.buildship.core.gradleclasspathcontainer' }
                source.entryAttributes['annotationpath'] = '/path/to/annotations'
            }
        }
    }
}
```

You can find more examples for classpath customization in the [Buildship 1.0.18 release announcement](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012).

**Comment by ChristianCiach** [comment]
Thanks! Actually, we are using Gradle 2.12 and your example seems to work just fine.

**Comment by oehme** [comment]
If you were using 2.12, then Buildship would not have touched the classpath attributes (because support for them was only added in 3.0). Are you using the Gradle wrapper? If not, you might be getting the default version that Buildship ships with.

**Comment by ChristianCiach** [comment]
Sorry, you are right: The Gradle version on my system is 2.12, but I am using the Gradle wrapper with buildship which uses the Gradle version 3.4.0.

**Comment by mauromol** [comment]
> If your project is using Gradle 3.0+ then you can customize the classpath attributes from the build script:

Hi @donat ,
with Buildship 3.1.3 and Gradle 5.6.4 this does not work any more, there's no classpathentry with path 'org.eclipse.buildship.core.gradleclasspathcontainer' in the {{whenMerged}} block, but one entry for each JAR file contributed by Gradle/Buildship (as {{Library}}s). I would like to avoid to set the external annotation path on each of those JARs, but I'd rather like to do it on the Gradle classpath container itself. Can this be still done and how?

**Comment by donat** [comment]
@mauromol So when you add

    containers 'org.eclipse.buildship.core.gradleclasspathcontainer'  

Then you don't see that entry in the `whenMerged` block?

**Comment by mauromol** [comment]
Oh, well, sorry, perhaps I missed it and didn't add:

    containers 'org.eclipse.buildship.core.gradleclasspathcontainer'

What is this supposed to do and why is it needed? I do have the "Project and External Dependencies" classpath container in my Eclipse project even if I don't specify this in my build script...

**Comment by donat** [comment]
The `whenMerged` block is executed in the contexts of the Gradle daemon and not in Eclipse. Gradle doesn't know anything about the Buildship classpath container, that's why we need the declare it separately if we want to modify it.
