### ISSUE TITLE
ClassNotFoundException on executing JUnit Debug As 

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#423]
[Original report from Kevin Hine](https://bugs.eclipse.org/bugs/show_bug.cgi?id=513079)

When I try to Debug As a Test case or a single method.  I get something similar to the following stack trace.

The project is imported via gradle 3.3 and 3.4 and the test target runs successfully.

I try to override the output directory to the PROJECT_LOC\build\classes where my application split into classes and test directories like:

PROJECT_LOC\build\classes\main
PROJECT_LOC\build\classes\test

HOwever running the Debug As JUnit creates the following in the Console

Java and Gradle builders are enabled.

java.lang.ClassNotFoundException: biouisvr.search.DASResultsCellValueMediaTypeTest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClass(RemoteTestRunner.java:688)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadClasses(RemoteTestRunner.java:421)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
	
	
.classpath contains:
```
	<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src/main/java">
		<attributes>
			<attribute name="FROM_GRADLE_MODEL" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" path="src/test/java">
		<attributes>
			<attribute name="FROM_GRADLE_MODEL" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" path="src/test/resources">
		<attributes>
			<attribute name="FROM_GRADLE_MODEL" value="true"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6/"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer">
		<attributes>
			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
		</attributes>
	</classpathentry>
	<classpathentry combineaccessrules="false" kind="src" path="/BiometricsCommon"/>
	<classpathentry kind="output" path="ide_build"/>
</classpath>
```
When I update the classpath on Debug As configuration of the Junit with my application's main and test classes directory via an External Folder.  I am able to use the Debug As on my tests

**Comment by oehme** [comment]
> I try to override the output directory to the PROJECT_LOC\build\classes
> where my application split into classes and test directories like:
> PROJECT_LOC\build\classes\main
> PROJECT_LOC\build\classes\test

That can't work. The classes are in `build/classes/main`, so when you add `build/classes` to the classpath, the JVM will treat "main" as a package. Instead, you need to set the output folder for each source folder. E.g.

```
eclipse {
    classpath {
        file {
            whenMerged {
                def src = entries.find { it.path == 'src/main/java' }
                src.output = "/$eclipse.project.name/classes/main-java"
            }
        }
    }
}
```

**Comment by kevinwhine** [comment]
I do not follow you when you say this can not work.  All I want buildship to do is honour the Gradle script and what the test target does when run from the command line

**Comment by oehme** [comment]
Please provide a reproducible example and reopen if you think this is a bug in Gradle or Buildship.

**Comment by kevinwhine** [comment]
Will do at the weekend.  You will have an update on Monday.


Kevin


________________________________
