### ISSUE TITLE
Use the eclipse environment, the implementation of gradle project import operation, how to configure gradle implementation parameters?

### ISSUE THREAD

**Issue by menger163** [eclipse/buildship#425]
Heys, Who can tell me  use the eclipse environment, the implementation of gradle project import operation, how to configure gradle implementation parameters?

**Comment by oehme** [comment]
I'm not sure what you are asking for, could you give an example of what you want to achieve, please?

**Comment by oehme** [comment]
Closing as there was no further feedback. Please feel free to reopen with more information on the problem.
