### ISSUE TITLE
buildship won't keep source folder as source folder for Groovy project 

### ISSUE THREAD

**Issue by sc1478** [eclipse/buildship#426]
I am trying to manage a collection of groovy scripts in a gradle project that will be deployed into a directory in my jenkins instance.  Such groovy scripts are typically expected to live in the default package.  I can apply the groovy plugin in my build script and then Eclipse lets me make a source folder.  If I then refresh the project, my source folder no longer shows up as a source folder.

**Comment by oehme** [comment]
Buildship removes source folders that are not marked as such in Gradle. You can either add them to a `sourceSet` so Gradle will compile them as well (which might be nice for sanity checking)

```
sourceSets {
  main {
    groovy {
      src 'folder/with/scripts'
    }
  }
}
```
Or you can manually add them to the Eclipse classpath model using 
```
eclipse.classpath.file.whenMerged {
  entries << new org.gradle.plugins.ide.eclipse.model.SourceFolder('folder/with/scripts', null)
}
```

**Comment by sc1478** [comment]
First one fails:

![2017-03-16_13-01-10](https://cloud.githubusercontent.com/assets/15382550/24011546/191f8e7a-0a49-11e7-9fe0-2c2c899118c6.png)

**Comment by sc1478** [comment]
I think you meant 
sourceSets {
  main {
    groovy {
      include 'folder/with/scripts'
    }
  }
}

**Comment by oehme** [comment]
Sorry I meant `srcDir`.
