### ISSUE TITLE
Buildship plugin needs to ignore project/self-referenced dependencies

### ISSUE THREAD

**Issue by digulla** [eclipse/buildship#429]
I have this layout: `main` -> `junit` -> `test`, that is I inserted a "JUnit support library" between the `main` and `test` code parts. This support library makes it easier to write unit tests for the main code. It has to be compile before the tests and it's a public dependency for other projects that want to write their own unit tests. The support library contains test data factories, JUnit rules, etc. to make your life easier.

To make this work, I have to add a couple of dependencies to the project:

        project.dependencies {
            junitCompile project.sourceSets.main.output
            // This breaks Gradle
            //junitCompile project.configurations.compile
            // This is the only way both Eclipse and Gradle work
            junitCompile project.sourceSets.main.compileClasspath
            
            //testCompile project(path: ':sqg-toolbox2-utils', configuration: 'junit')
            testCompile project.sourceSets.junit.output
        }

As you can see from the comments, this is brittle. The main problem here is that Eclipse will refuse to compile the project because Buildship adds a dependency to `/project-folder/build/classes/junit/`. This dependency can only be resolved by starting the build (so the folder is created) but since it's a classpath dependency, Eclipse refuses to start building -> deadlock.

The workaround is to hide this dependency from Buildship:

    def configureEclipsePlugin(Project project) {
        def configurations = project.configurations
        
        project.plugins.withId('eclipse') { plugin ->
            log.debug('Configuring Eclipse plugin')
            //println 'Configuring Eclipse plugin'
            //println plugin
            
            def eclipse = project.extensions.findByType(EclipseModel.class)
            //println eclipse
            
            eclipse.classpath {
                minusConfigurations += [
                    configurations.junit
                ]
                //configurations.each {
                //    log.debug('configureEclipsePlugin: configurations {}', it)
                //}
                //configurations.testCompile.each {
                //    log.debug('configureEclipsePlugin: configurations.testCompile {}', it)
                //}
                
                file {
                    // Remove "junit" dependency for Eclipse. When the dependency exists, Eclipse refuses to compile the 
                    // project because it wants a folder .../build/classes/junit/ which doesn't exist (yet) and which isn't
                    // necessary for Eclipse to build the project.
                    whenMerged { classpath -> 
                        //log.debug('configureEclipsePlugin: file classpath {}', classpath)
                        def toRemove = []
                        classpath.entries.each {
                            log.debug('configureEclipsePlugin: file classpath.entry {}', it)
                            if (it.path.endsWith('/junit')) {
                                toRemove << it
                            }
                        }
                        
                        log.debug('configureEclipsePlugin: toRemove {}', toRemove)
                        //println "toRemove ${toRemove}"
                        classpath.entries.removeAll(toRemove)
                    }
                }
            }
        }
    }

It would be much nicer if Buildship would check such internal dependencies and filter them out (since Eclipse has only one classpath for everything, anyway).

The strange thing is that Buildship already works correctly when I append integration tests *after* the tests. It only fails when I insert something between main and test.

**Comment by oehme** [comment]
The right way to model this is by setting up the relationship of the configurations and sourceSets:

```
sourceSets
  testFixtures {
    compileClasspath += main.output
    runtimeClasspath += main.output
  }
  test {
    compileClasspath += testFixtures.output
    runtimeClasspath += testFixtures.output
  }
}

configurations {
  testFixturesCompile.extendsFrom(compile)
  testFixturesRuntime.extendsFrom(runtime)
  testCompile.extendsFrom(testFixturesCompile)
  testRuntime.extendsFrom(testFixturesRuntime)
}
```

No eclipse customization required.

**Comment by digulla** [comment]
Thanks, that looks much cleaner :-) I love it when I can delete 100 lines of code!

I'd suggest to extend from `compileOnly`, though. That would include optional dependencies which are available when compiling `main`. That's code that the test fixtures should be able to support, too.

In a similar fashion, I've extended `testCompile` from `testFixturesCompileOnly`.

**Comment by oehme** [comment]
I'd suggest making it more explicit: `testCompileOnly.extendsFrom(testFixturesCompileOnly)`. Otherwise you are leaking `compileOnly` dependencies into downstream projects.

**Comment by digulla** [comment]
While that sounds like a good idea at first glance, now many tests fail because they can't see the `compileOnly` dependencies at runtime anymore. So I had to mix the two ideas:

            junitCompile.extendsFrom(compile)
            junitCompileOnly.extendsFrom(compileOnly)
            junitRuntime.extendsFrom(runtime)
            testCompile.extendsFrom(junitCompileOnly) // <<-- needs to extend compileOnly or tests won't see optional dependencies of the fixtures.
            testCompileOnly.extendsFrom(junitCompileOnly)
            testRuntime.extendsFrom(junitRuntime)

I don't feel that classpath pollution is a big issue for unit tests since we discourage test JAR dependencies (that's what the JUnit Support JAR is for).

**Comment by oehme** [comment]
If you need something at runtime, it's not a `compileOnly` dependency. `compileOnly` is meant for exactly what the name implies: Things you only ever need when compiling (e.g. annotation processors).
