### ISSUE TITLE
Daemon directory not created in USER_HOME/.gradle/ leads to 2 daemons being started

### ISSUE THREAD

**Issue by kohlerm** [eclipse/buildship#430]
I'm using gradle 3.2 and buildship 2.0 on Ubuntu 16.04. Running my build scripts from the command line starts one daemon and doing a gradle refresh in Eclipse starts another daemon. 
It seems the reason is that in Eclipse the daemon directory is created in my gradle installation directory e.g. /usr/share/gradle3.2, but the commandline tools use the directory mentioned in the title. 

I cannot afford running 2 daemons because of the size of my project (jar files are being downloaded twice as well).

I wonder whether there is a workaround, I tried setting the directory, but that does not seem to work. 
I

**Comment by oehme** [comment]
Buildship does not use a different directory, unless you told it to do so in the workspace preferences. Please check whether you changed the "Gradle User Home" there.

**Comment by kohlerm** [comment]
Thanks for the quick reply. Indeed I played around with that setting and accidentally . It seems that my original problem was caused by some settings (using another gradle version) stored in org.eclipse.buildship.core.prefs in my projects.
