### ISSUE TITLE
Project import ignores Java home configuration in the Gradle home

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#437]

**Comment by oehme** [comment]
It doesn't ignore it. It's just that the Gradle Distro download happens on the Client side. And that client is Eclipse. So if the distro is hosted with https and the Client VM has no SSL capability, it will fail.

It would be interesting to know why SSL doesn't work on that client VM. If it cannot be fixed, then a potential workaround is to host the Gradle distro yourself and allow plain http access to it inside your company.
