### ISSUE TITLE
Upgrade the Buildship build to the latest Gradle release

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#442]
Currently, a change in the internal test execution API prevents us from upgrading the used Gradle version.

**Comment by nicolas-albert** [comment]
Hi, there is any update about this ?

I try to run with gradle 3.5 but the **eclipsebuild** plugin (from buildSrc) failed to build with 7 errors. Gradle 4.0 is just released and I guess it doesn't compile it too.

I'll continue my tests with gradle 3.0 for now.

**Comment by donat** [comment]
We are on 4.3 now. 
@nicolas-albert is your project open-source. I'd be glad to learn how you use those build scripts.
