### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by oehme** [eclipse/buildship#444]

**Comment by donat** [comment]
We are only waiting for the following CQs to be approved:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13164
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13165

**Comment by oehme** [comment]
We also need a small announcement.

**Comment by donat** [comment]
Release complete.
- Announcement: https://discuss.gradle.org/t/buildship-2-0-2-is-now-available
- Project page: https://projects.eclipse.org/projects/tools.buildship/releases/2.0.2
- SimRel contribution: http://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/?id=bb99f2802b72d4f9dc4c28fc3218292c643c036d
