### ISSUE TITLE
Open grouping node in Gradle Tasks via on double-click

### ISSUE THREAD

**Issue by vogella** [eclipse/buildship#448]
Would be nice if double-click on a grouping would open this tree node.

![image](https://cloud.githubusercontent.com/assets/139910/24869685/4fa5c9d0-1e14-11e7-800b-2ab3f867f81d.png)

**Comment by AndyWu2015** [comment]
make a try on this , and send the pr, hoping it can be merged

**Comment by donat** [comment]
Thank you @AndyWu2015 for the implementation!
