### ISSUE TITLE
Refresh Gradle action should be enabled for all editors

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#452]
The [original report](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514205) from Bugzilla:

>I try as much as I can to avoid using the mouse.  Tools should facilitate that ability, without making it harder for mouse-dependent users.
>
>When I make a change to my build.gradle file, like adding a dependency, after saving it to disk with a keypress, I now have to move my mouse over to the package/project explorer, right-click on my project, select the Gradle menu, and then "Refresh Gradle Project".  I can then switch back to the editor view, move to one of my classes, and start using the new functionality.
>
>What I want to be able to do is press a single key sequence after saving the build.gradle file, which will cause the enclosing Gradle project to be refreshed, causing the new dependency to be available.  I then want to be able to switch to my source file and add the reference to the new artifact, all without touching the mouse.
>
>I've attempted to bind "Refresh Gradle Project" to a key (with a "When" value of "In Windows"), but pressing that key sequence does nothing.

I tried to set up a hotkey and in fact, it only worked when the file was opened with the default `org.eclipse.buildship.ui.gradlebuildscripteditor`. We should enable the action for all editors when a resource is selected from a Buildship project.

**Comment by edeandrea** [comment]
Doesn't the m2e plugin automatically refresh the project whenever a save of pom.xml is triggered? That would be nice.

**Comment by danielebosetti** [comment]
This feature would be nice to have-
As it currently works, we can use a key shortcut to refresh the gradle project, but that only works if "project explorer" is selected.

Maybe not from any editor- the shortcut could be available just after editing the build.gradle file (so, from "text editor"?).
So that after editing the build file, we can press CTRL+S to save and then ALT+F8 to refresh (say we configured this shortcut);
in this way we avoid using the mouse, and there is no need to switch to project explorer.

**Comment by oleosterhagen** [comment]
This issue has been accidentally resolved by https://github.com/eclipse/buildship/pull/1287:

https://github.com/eclipse/buildship/blob/06828cf4d0d6e822076f7da89435a4a9a1845239/org.eclipse.buildship.ui/plugin.xml#L208-L213

(This definition makes the _Refresh Gradle Project_ action for Gradle Kotlin DSL files in the _Generic Editor_ possible without introducing a direct dependency on the `org.eclipse.ui.genericeditor` bundle.)

@donat Can you close this issue?
