### ISSUE TITLE
Gradle projects may produce circular references in Buildship.

### ISSUE THREAD

**Issue by rhencke** [eclipse/buildship#460]
This is a contrived example of a real issue I hit attempting to make a larger project work with Buildship. (2.0.1.v20170302-1039)

Consider the following project.

```gradle
// settings.gradle
include ':a'
include ':b'

// a/build.gradle
plugins { id 'java' }
dependencies { testCompile project(':b') }

// b/build.gradle
plugins { id 'java' }
dependencies { testCompile project(':a') }
```

This is a legal project with no circular dependencies, as each testCompile configuration refers to the default configuration of the other project.

However, when importing this into Buildship, the following error is encountered:

```
A cycle was detected in the build path of project 'a'. The cycle consists of projects {a, b}
The project cannot be built until build path errors are resolved
```

**Comment by donat** [comment]
This is the expected behavior. Since Eclipse supports only one classpath per project, Buildship uses a union of dependencies from all build configurations (which happens to be `testCompile`).

You can change the error to warning with the following configuration:
<img width="733" alt="screen shot 2017-04-28 at 11 30 28" src="https://cloud.githubusercontent.com/assets/419883/25523286/68a4a6e0-2c06-11e7-9cd0-606cf348b586.png">

**Comment by rhencke** [comment]
@donat Thanks for this.  I appreciate the workaround.

Has an approach been considered such as per-sourceset projects, as is an option with IntelliJ IDEA's Gradle integration?  (Currently, I'm using the Eclipse classes in Gradle to generate something like this out manually, with project-per-sourceset)

**Comment by donat** [comment]
Unfortunately, Eclipse - at least for the time being - is very limiting as it lets us define one source set with one classpath per project. We'll address this problem later, but it will require quite some preliminary planning.

**Comment by UdoW** [comment]
Is this true that Eclipse cannot handle to mapping of Gradle source sets?

**Comment by UdoW** [comment]
And what are the plans to solve this issue? I mean by not using the mentioned "workaround" above?

**Comment by stephan-herrmann** [comment]
I'm coming here from https://bugs.eclipse.org/bugs/show_bug.cgi?id=562964 ...

> Since Eclipse supports only one classpath per project, Buildship uses a union of dependencies from all build configurations (which happens to be `testCompile`).

This is no longer true since 4.8, see https://www.eclipse.org/eclipse/news/4.8/jdt.php#jdt-test-sources

Does buildship set the "test" attribute on test source folders?

If you see smth missing in JDT (e.g., differentiation between compile time vs. runtime dependencies) feel free to file an enhancement request. We can negotiate additional classpath attributes that would be evaluated differently by the compiler and when launching.

**Comment by regrog** [comment]
Well, I think that there's another aspect about circular dependencies.
In gradle you can also have something like this:
```
// settings.gradle
include ':web'

// project with only interfaces of a
include ':a'
// implementations of a
include ':a-impl'

// project with only interfaces of b
include ':b'
// implementations of b
include ':b-impl'

// projects build.gradle

// web
plugins {
    id 'java-library'
    id 'war'
}
dependencies {
    implementation project(':a')
    implementation project(':b')
}

// a
plugins { id 'java-library' }
dependencies { runtimeOnly project(':a-impl') }
// a-impl
plugins { id 'java-library' }
dependencies {
    implementation project(':a')
    // a uses functions defined in b
    implementation project(':b')
}

// b
plugins { id 'java-library' }
dependencies { implementation project(':b-impl') }
// b-impl
plugins { id 'java-library' }
dependencies { implementation project(':b') }
```
This structure is to avoid unsolvable dependencies between **a** and **b**.
I'm using Spring to inject the implementations of **b** in **a**, decoupling api and implementation.
This also helps me to enhance builds compile time by decoupling.

In the other hand, Eclipse doesn't support this type of dependency by differentiating runtime and implementation (or maybe is what I know ).

**Comment by stephan-herrmann** [comment]
Once more: buildship is free to interact / negotiate with JDT (https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT), but **buildship** needs to **drive this actively**, if any improvement is desired.

**Comment by morgwai** [comment]
it's been 3 years since eclipse-4.8 has been released... I wonder how much does jetbrains "donate" to gradle/buildship to leave this unfixed...

**Comment by tijanssen** [comment]
Please, please fix this problem
