### ISSUE TITLE
Streamline preferences UI

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#465]
The preferences UI should look and behave similarly on the workspace/project/run config level.

**Comment by donat** [comment]
I refactored the code so that now we have reusable composites for the more complex widgets (user home and distribution selection). Using this I've created a simple mockup to discuss the placements of the elements. 

Workspace configuration
<img width="508" alt="workspace" src="https://cloud.githubusercontent.com/assets/419883/26263596/be9b92d2-3cd9-11e7-87f5-6631bb8bf299.PNG">

Project configuration
<img width="595" alt="project" src="https://cloud.githubusercontent.com/assets/419883/26263606/c6250ff6-3cd9-11e7-8200-e28d52e32d4d.PNG">

Run configuration
<img width="610" alt="runconfig" src="https://cloud.githubusercontent.com/assets/419883/26263621/d17fad66-3cd9-11e7-834a-5b83a17f12d1.PNG">

For comparison, here's how an average jdt preference page looks like
<img width="493" alt="jdt" src="https://cloud.githubusercontent.com/assets/419883/26263696/0ea63002-3cda-11e7-85ba-6b4c04a936c0.PNG">

So how do you think the elements should be arranged?
/cc @etiennestuder

**Comment by etiennestuder** [comment]
I would show the 'Override ... settings' at the top of pur screens, too. And use a delimiter right below given they do the same for the javac settings screen. Everything else I would leave as you have it now.

Q: Why can the Gradle Distribution not be set on the Workspace level? (I'm not saying it should be, I would just like to understand the rationale)

**Comment by donat** [comment]
The Gradle distribution is an attribute the user sets during project import. That's why there's no distribution on the workspace settings. Also, that's why I didn't put the overwrite settings in the top of the project preferences page.

**Comment by oehme** [comment]
There's no reason why we can't allow a distribution at the workspace level. Several users asked for this already.

**Comment by donat** [comment]
Seems reasonable. So if I get this right, we should also change the creation/import wizard and let the users choose whether they want to use/override the default distribution configured on the workspace level.

**Comment by oehme** [comment]
I think that would make sense from a consistency point of view. And it would make some users happy who for whatever reason don't like the wrapper ;)

**Comment by donat** [comment]
I managed to make the all the dialogs uniform. Here's how they look like:

Import dialog
<img width="490" alt="1 import" src="https://cloud.githubusercontent.com/assets/419883/26317005/67c00a26-3f16-11e7-80ec-67387b604fa2.PNG">

Workspace configuration
<img width="543" alt="2 workspace config" src="https://cloud.githubusercontent.com/assets/419883/26317015/6dead674-3f16-11e7-878d-2d29f96f0e00.PNG">

Project configuration
<img width="542" alt="3 projectconfig" src="https://cloud.githubusercontent.com/assets/419883/26317033/76aa21b6-3f16-11e7-8199-8e813f9d479c.PNG">

Run configuration
<img width="789" alt="4 runconfig" src="https://cloud.githubusercontent.com/assets/419883/26317040/7b8a68ee-3f16-11e7-83c4-52625633059c.PNG">

**Comment by oehme** [comment]
This looks great, just one small enhancement request: When "override" is not checked, all the other options should be greyed out.

**Comment by donat** [comment]
That's the next step :)

**Comment by donat** [comment]
Implemented in #484.
