### ISSUE TITLE
Configure Gradle user home in run configuration

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#467]

**Comment by donat** [comment]
An interesting aspect of this is the Gradle User home is an external location on the local file system which not meant to be shared. I remember that in the past users complained about absolute paths being present in the project settings. This time it's a bit different because it's only present if the user explicitly overwrites the workspace settings. Any concerns about that, @oehme?

**Comment by oehme** [comment]
What's the use case for configuring the user home on the project level?

**Comment by donat** [comment]
I think we should let the users overwrite the preferences consistently, that's why I included the Gradle user home there. I can imagine it can come handy when the user wants to test dependency resolution, up-to-date checks, etc.
