### ISSUE TITLE
Unable to import project with a plugin repository defined in settings.gradle

### ISSUE THREAD

**Issue by eaaltonen** [eclipse/buildship#468]
I implemented a small custom in-house plugin.

The build file now applies it using the Plugins DSL
```
plugins {
    id 'my.plugin' version '0.1'
}
```

The in house Nexus repository is defined in `settings.gradle` in the projects top directory.

This works fine from the command line, but when trying to import the project in
Buildship 2.0.2.v20170420-0909
results in an error
```
Plugin [id: 'my.plugin', version: '0.1'] was not found in any of the following sources:
```

**Comment by oehme** [comment]
I assume your in-house repo needs some credentials, which you have specified in your Gradle user home? Make sure that you haven't changed the user home location in the workspace preferences.

**Comment by eaaltonen** [comment]
Yes, I've configured the credentials in `~/.gradle/gradle.properties`.
The "Gradle User Home" in Eclipse is also empty, I have not touched it.

**Comment by oehme** [comment]
Is there some proxy between you and the repo? If yes, have you configured the proxy settings in Eclipse?

**Comment by oehme** [comment]
Can you paste the full error message, ideally some debug output?

**Comment by eaaltonen** [comment]
It was my mistake. I had not updated **this** project to use Gradle 3.5.
```
org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.4.1-bin.zip
```

So updating `gradle/wrapper/gradle-wrapper.properties`
```
distributionUrl=https\://services.gradle.org/distributions/gradle-3.5-bin.zip
```
Fixed the issue.

Sorry for the noise.
