### ISSUE TITLE
Buildship - cannot resize "Gradle Tasks" treeview

### ISSUE THREAD

**Issue by mimmoz81** [eclipse/buildship#475]
When using Buildship, if you have a large task name, in Gradle Tasks treeview the name itself is truncated (and the same applies to the description). See screen below:

![immagine](https://cloud.githubusercontent.com/assets/14213760/26298464/b1fcd20c-3ed7-11e7-9e3b-cd48d7f70f67.png)

It would be better to have some splitpane-like control between the name and the description, to be able to resize the view accordingly to user need.

### Expected Behavior
A control like a splitpane should be placed between task name and description, to be able to resize the view and see the full name.

### Current Behavior
Cannot resize the view

### Your Environment
Gradle 3.4.1
Buildship 2.0.2
Eclipse 4.6.3

**Comment by oehme** [comment]
@donat Can we show the headers by default please? This is the 5th time a user asks how to resize columns in the task view :)

@mimmoz81 You can go to the options of the view and activate "Show Headers". Then you can resize them.

**Comment by mimmoz81** [comment]
Ok I see.
Thanks

**Comment by donat** [comment]
Sure, I'll do it.
