### ISSUE TITLE
Build script code completion for non Java projects

### ISSUE THREAD

**Issue by eaaltonen** [eclipse/buildship#479]
I am making a build system for a project in a language and toolset other than Java. However, I am using gradle-plugins and Groovy functions (Java and Groovy, respectively).

I would like to have Buildships code completion available while working with the buildscript (ideally with minimal or zero configuration).

I tried a quick hack of adding the either the `java-gradle-plugin` or `java` plugin, but both of them conflict with the `clean` task for this project.

**Comment by oehme** [comment]
The plugins of the project have nothing to do with the tooling for the build scripts. There currently is no editor support for Groovy-based build scripts in Buildship. We will soon add support for [Gradle-Script-Kotlin](https://github.com/gradle/gradle-script-kotlin) though, see https://github.com/eclipse/buildship/issues/211

**Comment by eaaltonen** [comment]
If I create a new Java project with

    gradle init --type java-library

and "Import Gradle project" in Eclipse I do get code completion in the **build.gradle** for the following snippet
```java
ArrayList<String> list = new ArrayList()
list.
```

I can get the same effect by manually editing and adding the **javanature** to the projects `.project` file.
```xml
        <natures>
                <nature>org.eclipse.jdt.core.javanature</nature>
                <nature>org.eclipse.buildship.core.gradleprojectnature</nature>
        </natures>
```

However, such changes are lost if I for example update a plugin version and refresh the project in Eclipse.

Since groovy scripts can always use Java classes, would it be ok to add the **javanature** by default?

**Comment by oehme** [comment]
You can add the java nature in your build.gradle file

```
eclipse.project.natures 'org.eclipse.jdt.core.javanature'
```

**Comment by eaaltonen** [comment]
I found a bug report on buildship 1, that is basically what I would like to achieve.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=491773

so although the projects source code is not Java, for the `build.gradle` I would want the following to present after importing the project
- classpath entries that include the JRE and Groovy
- javanature (or similar for code completion)


Future: I also have (documented) Java classes in my plugin, which I would like to automatically add to the classpath.
