### ISSUE TITLE
WEB-INF/lib not added to eclipse deployment assembly settings in a gradle web project

### ISSUE THREAD

**Issue by esz** [eclipse/buildship#496]
In a war project depending on external jars (retrieved from a maven repo) Buildship seems to fail configuring the deployment assembly settings of the eclipse project correctly.
A record for "Dependencies -> Deploy-Path: WEB-INF/lib" is missing. Thus when deploying the webapp to a server within eclipse, dependency-classes are not available.

I published a small example which reproduces the problem: https://github.com/esz/eclipse_buildship_war_deployment

Please follow these steps to reproduce:

- mylibrary> gradle install
- start eclipse (I'm on Neon.3 (4.6.3), gradle 3.5, Buildship 2.0.2.v20170420-0909) and import "mywebapp" using Buildship gradle-integration
- have a look at the deployment assembly settings, an entry for WEB-INF/lib is missing
- deploy to a servlet 3 compliant container (I tried tomee 7.02. webprofile and ibm websphere liberty 8.5)
- observe java.lang.ClassNotFoundException: mylibrary.SomeOtherClass in the server's log when requesting http://localhost:8080/mywebapp/myservlet

Assembling the war using "gradle clean build" and copying it into the server's deployment dir works without any issues (since the built war contains all required WEB-INF/lib dependencies).

**Comment by esz** [comment]
Changing
`implementation 'mywebapp:mylibrary:0.0.1-SNAPSHOT'`
to
`runtime 'mywebapp:mylibrary:0.0.1-SNAPSHOT'`
in 
`https://github.com/esz/eclipse_buildship_war_deployment/blob/master/mywebapp/build.gradle`
helps. The deployment assembly settings in eclipse then include a WEB-INF/lib containing the project's dependencies.

Seems like the implementation dependency configuration is ignored. Hower this seems a little counter-intuitive since the dependencies are included in the .war when building on the command line.

**Comment by mauromol** [comment]
IMHO this issue title is wrong. The problem is not that WEB-INF/lib is not added to Eclipse Deployment Assembly, because Buildship does not need to publish the WEB-INF/lib folder (which should be empty if Buildship is used to handle *all* dependencies), but rather that `implementation` dependencies are not published.

**Comment by clo-vis** [comment]
_implementation_ dependencies are not the only ones not published; _api_ dependencies are also ignored. 
(this happens if the war project depends on a java-library which is included with _includeBuild_)

**Comment by regrog** [comment]
Any news about this issue?
I'm facing this problem right now.
Thanks

**Comment by donat** [comment]
Adding `runtimeClasspath` to `libConfigurations` is a way to go which I also suggested at [another issue](https://github.com/eclipse/buildship/issues/691#issuecomment-456482174).

The composite build support for the `eclipse-wtp` plugin would require significant work. It's a community driven plugin so it's up to the community if it will be implemented or not. I'm happy to help guiding anybody though the process if there are volunteers.

FYI the Buildship `wtp` support is based on invoking the `cleanEclipseWtp` and `eclipseWtp` tasks on synchronization. This means that if something is not well set up in the workspace then adjustments can be done in the `eclipse.wtp.component.file.whenMerged {}` [block](https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseWtpComponent.html).

**Comment by mauromol** [comment]
Donat, I think I'm a bit lost here. Isn't here the problem that `implementation` dependencies are not published? The workaround seems quite easy for me for inclusion in the core, why do you say that implementing it in `eclipse-wtp` plugin would require significant work?
What if Gradle deprecates the `compile`/`runtime` configurations? Will `eclipse-wtp` "stop to work"?

**Comment by oehme** [comment]
@donat We should fix this in Gradle instead of only recommending a workaround. Gradle issue is here: https://github.com/gradle/gradle/issues/6341

**Comment by donat** [comment]
@oehme And it seems that you also fixed the problem in Gradle.

**Comment by njc1431985** [comment]
> _implementation_ dependencies are not the only ones not published; _api_ dependencies are also ignored.
> 
> A workaround:
> 
> ```
> eclipse {
>     wtp {
>         component {
>             libConfigurations += [ configurations.runtimeClasspath ]
>         }
>     }
> }
> ```
> (but projects included with includeBuild are still ignored)

This workaround. Does it have to go inside the WebProject, or all projects the WebProject is dependent on ?
