### ISSUE TITLE
Remove white background from feature image

### ISSUE THREAD

**Issue by vogella** [eclipse/buildship#500]
See screenshot.

![image](https://user-images.githubusercontent.com/139910/27221324-7f726800-5288-11e7-99ef-7e7c208fa7e2.png)

**Comment by vogella** [comment]
![image](https://user-images.githubusercontent.com/139910/27221361-9de9583e-5288-11e7-833e-a29ceb95c3b7.png)

**Comment by donat** [comment]
I think that without the white background the Gradle logo would be almost invisible, so it looks better this way.

**Comment by vogella** [comment]
@donat good point. I close this issue.
