### ISSUE TITLE
Is there any plan to provide decent editor for gradle files ?

### ISSUE THREAD

**Issue by to-kra** [eclipse/buildship#501]
Hello,
Do you have any plan to provide decent editor for gradle files with color syntax highlighting, autocomplete etc ?
Thank you

**Comment by donat** [comment]
This has been answered on the [Gradle forum](https://discuss.gradle.org/t/gradle-autocompletion/22962/2):

> We will provide auto completion, source lookup etc. with the new Kotlin DSL5. We are already working on Eclipse support for it, together with the JetBrains team.
> 
> Providing the same support for Groovy is not planned, as we will phase Groovy out in the long run. Also, Groovy Eclipse is not actively maintained, so we wouldn't have a stable base to build on anyway.

**Comment by to-kra** [comment]
@donat Do you have some rough estimate when we could expect this feature in Eclipse ? Will groovy support go sunset because of Kotlin ? thank you

**Comment by dwaal** [comment]
@donat is there an official statement from Gradle.org that Groovy will go away? When? Gradle 5, 6, 7, 8?

**Comment by oehme** [comment]
Groovy will remain supported for a very long time, we just don't have the capacity to enhance it's IDE support. On the Kotlin side JetBrains is doing that work for us. If you want to see better support for Groovy scripting in Eclipse, then helping out the groovy-eclipse maintainers would be a good place to start.

**Comment by dwaal** [comment]
You wrote that you will "phase out Groovy in the long run". Is this just some internal thing you say or is this official? I guess there is no time frame when to phase it out? 2, 4, 6 years?

**Comment by oehme** [comment]
We don't have a time-frame for this yet. The Kotlin DSL is only reaching 1.0. Any planning about actually phasing out Groovy will only start when the majority of our user base have migrated, which will take years.

**Comment by dwaal** [comment]
Thanks for the info. Why remove Groovy? Is Kotlin so much superior? Supporting groovy-eclipse seems a dead end then since Gradle was the last place where it is really used. Grails seems also dead.

**Comment by oehme** [comment]
The main reason is IDE support and static typing, so that our users get proper auto completion etc. Groovy has `@CompileStatic`, but IDE support for it has remained spotty.
