### ISSUE TITLE
Missing Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs

### ISSUE THREAD

**Issue by MartinHaeusler** [eclipse/buildship#504]
I'm using BuildShip for a gradle multi-project build that resides in a git repository. From time to time, I like to run `git clean -xdf` and `git reset --hard HEAD` on it to get to a clean state. When that happens, the file

`.settings/org.eclipse.buildship.core.prefs`

... also gets erased. The buildship plugin will complain about it and refuse to build. The only workaround seems to be to delete the project from the eclipse workspace altogether and re-import it using the Buildship importer (generic project importer doesn't work!). That's really quite annoying, not even running `gradle eclipse` fixes it. The behaviour I would expect to see is that if buildship detects the absence of the preferences file, it silently creates a new one with default settings.

I'm using gradle 3.x and the latest version of the Buildship plugin, on Eclipse Oxygen.

**Comment by oehme** [comment]
Buildship can't recreate that file as it cannot know what your root project was (Gradle supports arbitrary project layouts). You should either check the settings file in or not check in any Eclipse files at all. Checking in .project while leaving out .settings is not supported.
