### ISSUE TITLE
Eclipse source folders removed

### ISSUE THREAD

**Issue by dhakehurst** [eclipse/buildship#506]
I upgraded to 2.0.2 from 1.0.21.
All the source folders that I had explicitly added in eclipse, got removed
and now get removed (again, if I re add them) every time I refresh the gradle project.

this is different behaviour to 1.0.21

**Comment by donat** [comment]
Buildship synchronizes the source folders from the build configuration. Just define the folders in your [build script](https://docs.gradle.org/4.0/userguide/java_plugin.html#sec:changing_java_project_layout) and execute another refresh.

**Comment by dhakehurst** [comment]
This is not going to work in my situation.
see gradle file below,

the js files are put into a specific place of the jar

```
jar {
	from ("${projectDir}/src/main/js", {
		into "META-INF/resources/webjars/dynamic/${version}"
		include "**/*.js"
	})
}
```

if I add
```
sourceSets {
	main {
            resources {
                srcDirs = ["${projectDir}/src/main/js"]
            }
	}
}
```
then the js files get added twice to the jar.

I don't need to tell gradle that they are resources,
I just need to tell eclipse to display the folder as a source folder.

**Comment by oehme** [comment]
If you add it as a JDT source folder, then JDT will just copy those JS files into the root of the output folder, which means when use "Run As" inside Eclipse, your result will be different than when you run with Gradle. Here's how you'd add a custom source folder:

```
import org.gradle.plugins.ide.eclipse.model.SourceFolder

eclipse.classpath.file.whenMerged {
  entries << new SourceFolder('src/main/js', null)
}
```

Correct me if I'm wrong, but in order for Eclipse to match your command line build better it seems you would want something like this:

- a task that takes the files and copies them into a folder that contains the right version number
- Buildship calls that task on every auto-build
- that folder is then added as a source folder

That could be achived once we implement #266

**Comment by dhakehurst** [comment]
thanks
> when use "Run As" inside Eclipse, your result will be different
true but at present its not an issue.

>in order for Eclipse to match your command line build better
yes that would be much better

many thanks for the tips.
