### ISSUE TITLE
Gradle Refresh Task should keep existing Eclipse natures

### ISSUE THREAD

**Issue by carlolf** [eclipse/buildship#508]
In our project there are some subprojects which are using the Eclipse GWT Plugin, and therefore they have this nature: 
`<nature>com.gwtplugins.gwt.eclipse.core.gwtNature</nature>`

This nature is applied, if we set it by the mentioned plugin. I understand, Buildship knows anything from this Eclipse-GWT-Plugin and therefore it cannot itself add this nature when first importing the projects. But I think, it should KEEP this nature once it is set and if later Gradle projects are (only!) refreshed.

**Comment by donat** [comment]
This has been discussed [here](https://github.com/eclipse/buildship/issues/392) and is already implemented. You can try using the latest 2.1 snapshot which contains the fix.
