### ISSUE TITLE
Add editor support with basic highlighting capabilities for build scripts

### ISSUE THREAD

**Issue by cmoine** [eclipse/buildship#514]
My suggestion may seem naive, but never mind: why not integrating a fork of as a starting point for a gradle editor  such as https://github.com/Nodeclipse/GradleEditor ?
I think the MIT license shoudl allows this.

Btw: I can provide a PR  for that

**Comment by donat** [comment]
I  think having a basic syntax highlight is much better than using a plain text editor for Gradle files. If the implementation is simple and robust enough then please go ahead and create the pull request.
As of the licensing, I'll handle the IP clearance with the Eclipse Foundation. The MIT license should be fine here.

**Comment by cmoine** [comment]
Is there someone to integrate my last PR please ? https://github.com/eclipse/buildship/pull/559

**Comment by donat** [comment]
Hi! Sorry for the slow response, I've just got back from vacation. I'll try to look into your PR in the upcoming days.

**Comment by cmoine** [comment]
No pb, I was just wondering if it was ok from my side ! :) Don't hesitate. Good luck for coming back to work ;)

**Comment by jimmytheneutrino** [comment]
Hi!

Awesome work on the editor! 

I wonder if it will also support some auto completion?

**Comment by cmoine** [comment]
Hi, thank you very much. Probably in a second release of the editor ;) Step by step :)

**Comment by jimmytheneutrino** [comment]
Sure:) Thank you for doing this.

**Comment by cmoine** [comment]
No problem. I love Gradle, and love Eclipse too... But a Gradle editor was definitely missing I think :) 

I will try to address this after my PR is accepted ;)

**Comment by donat** [comment]
PR merged, thank you for the contribution! We'll probably publish a post on the forum to let the users try this feature out.

**Comment by cmoine** [comment]
Thank you very much. That was a pleasure. If I can help on further improvements. I would like to have a first feedback from end user before starting with basic completion, and so on.
