### ISSUE TITLE
Plug-in "org.eclipse.buildship.ui" unable to start

### ISSUE THREAD

**Issue by sayseakleng** [eclipse/buildship#517]
Hello guys! Please help to assist my problem. it happened to Eclipse Neon.3 Release (4.6.3) when I updated Gradle buildship plugin.

Thank ahead :)

The selected wizard could not be started.
Plug-in "org.eclipse.buildship.ui" was unable to instantiate class "org.eclipse.buildship.ui.wizard.project.ProjectCreationWizard".
loader constraint violation: loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) 
previously initiated loading for a different type with name "com/google/common/base/Optional"

**Comment by donat** [comment]
Thanks for the report, we'll provide a fix shortly.

**Comment by donat** [comment]
Let's continue at #519.

**Comment by donat** [comment]
I've created a snapshot release containing the fix. Can you please install it and verify if it fixes your problem? The update site urls are:
- http://download.eclipse.org/buildship/updates/e47/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e46/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e45/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e44/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e43/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e42/snapshots/2.x/

**Comment by sayseakleng** [comment]
@donat , the problem is fixed. Thank you

**Comment by logicalravii** [comment]
@donat I had the same problem. and your solution solved it. Thank you so much...
