### ISSUE TITLE
LinkageError after STS update to version 3.9.0.RELEASE

### ISSUE THREAD

**Issue by Bjoern2** [eclipse/buildship#518]
Hi. After the update of STS I receive following error at start:
```java
Loading tasks of all Gradle projects failed due to an unexpected error.
loader constraint violation: when resolving method "com.gradleware.tooling.toolingmodel.repository.internal.DefaultOmniEclipseProject.getAll()Lcom/google/common/collect/ImmutableList;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, org/eclipse/buildship/ui/view/task/ReloadTaskViewJob, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, com/gradleware/tooling/toolingmodel/repository/internal/DefaultOmniEclipseProject, have different Class objects for the type com/google/common/collect/ImmutableList used in the signature
java.lang.LinkageError: loader constraint violation: when resolving method "com.gradleware.tooling.toolingmodel.repository.internal.DefaultOmniEclipseProject.getAll()Lcom/google/common/collect/ImmutableList;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, org/eclipse/buildship/ui/view/task/ReloadTaskViewJob, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, com/gradleware/tooling/toolingmodel/repository/internal/DefaultOmniEclipseProject, have different Class objects for the type com/google/common/collect/ImmutableList used in the signature
	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.fetchEclipseGradleProjects(ReloadTaskViewJob.java:92)
	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.loadContent(ReloadTaskViewJob.java:65)
	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.runToolingApiJob(ReloadTaskViewJob.java:55)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

Same problem when I update the gradle tasks.

My current eclipse version:
```
Spring Tool Suite 
Version: 3.9.0.RELEASE
Build Id: 201707061903
Platform: Eclipse Neon.3 (4.6.3)
```
Buildship version: 2.1.0.v20170711-1519

I tried to reinstall the plugin. But without success.

**Comment by donat** [comment]
Thanks for the report, we'll soon provide a fix.

**Comment by donat** [comment]
Let's continue at #519.

**Comment by donat** [comment]
I've created a snapshot release containing the fix. Can you please install it and verify if it fixes your problem? The update site urls are:
- http://download.eclipse.org/buildship/updates/e47/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e46/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e45/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e44/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e43/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e42/snapshots/2.x/

**Comment by Bjoern2** [comment]
Sorry, same problem with this snapshot.
Installed version: 2.1.1.v20170712-2309-s

**Comment by donat** [comment]
I've found the reason why it didn't work for you. The patched plugin's versions were not changed, which caused the update to ignore them. The latest snapshot fixed that. Would you mind giving it another go?

**Comment by Bjoern2** [comment]
Version 2.1.1.v20170713-0826-s works for me. Thanks!

**Comment by donat** [comment]
Cool! I'll proceed with the release, thanks for helping out.

Btw I'd suggest to you - and to all who ends up reading this thread - to use the snapshot or milestone stream of Buildship. We use feature branches for development, so the master branch doesn't contain anything unstable. On the other hand, there are so many possible installation and configuration out there that we can't possibly cover all that and thus early feedback is invaluable for us. Besides, we like constructive criticism :)
