### ISSUE TITLE
Tooling-commons picks up different version than Buildship

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#519]

**Comment by donat** [comment]
Reported on the Gradle forum: https://discuss.gradle.org/t/synchronize-gradle-projects-with-workspace-failed-due-to-an-unsupported-configuration-in-the-referenced-gradle-build/21692/5

**Comment by donat** [comment]
The reason for the problem is that tooling-commons defines a different range for the Guava dependency. Now, since we have different Guava version requirements for different Buildship target platforms, the maintenance cost of having a separate subproject just became a much bigger maintenance burden. I think the proper solution here is to finally remove the tooling-commons dependency.

**Comment by oehme** [comment]
Don't we repackage tooling-commons inside the Buildship build anyway? If so we could modify its version range just like we do for the Buildship packages. At least until we remove the dependency, but that's a bigger refactoring.

**Comment by donat** [comment]
No, we don't. We generate a zipped p2 repository in the tooling-commons build which we consume in Buildship as-is.

**Comment by oehme** [comment]
Do we ever expose that repo to our users? I thought we upload tooling-commons together with the other Buildship bundles. If that's the case, we can change the manifest before we do so.

**Comment by donat** [comment]
Technically the p2 repo is publicly [available](https://repo.gradle.org/gradle/libs-snapshots/com/gradleware/tooling/p2-repository/) but we didn't announce it anywhere. I don't think anybody would use it.

**Comment by oehme** [comment]
Then I think just correcting the metadata in our public repo is a feasible hotfix.
