### ISSUE TITLE
Build on subproject builds complete multi-project

### ISSUE THREAD

**Issue by andilem** [eclipse/buildship#520]
After upgrading to Buildship 2.1.0, when building a subproject from the Gradle Tasks view, not only the subproject is built, but instead the complete multi-project.

When inspecting the run configuration, it seems like the working directory (which is set correctly) is **not** used during the task execution (the console output shows the root project location as working directory).

Expected behavior: Only the selected subproject is built (as in 2.0.2).

Tested with Gradle 3.5 and Gradle 4.0.

**Comment by oehme** [comment]
Thank you for the detailed description! We'll fix this in the next patch release.
