### ISSUE TITLE
Loading tasks of all Gradle projects failed due to an unexpected error

### ISSUE THREAD

**Issue by leomorgans** [eclipse/buildship#521]
Using Buildship 2.1.0, when I open the Gradle Tasks view, occurrs the following error:
[Eclipse bug report](https://dev.eclipse.org/recommenders/community/aeri/v2/#!/submissions/ExZelLg1iz5vk7aZqq8RfOBhFSkxD6zPybXQ6R7j87DFIhtmRDPSwDSCZKqL9Njc
)
> java.lang.LinkageError: loader constraint violation: when resolving method "com.gradleware.tooling.toolingmodel.repository.internal.DefaultOmniEclipseProject.getAll()Lcom/google/common/collect/ImmutableList;" the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the current class, org/eclipse/buildship/ui/view/task/ReloadTaskViewJob, and the class loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for the method's defining class, com/gradleware/tooling/toolingmodel/repository/internal/DefaultOmniEclipseProject, have different Class objects for the type com/google/common/collect/ImmutableList used in the signature
> 	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.fetchEclipseGradleProjects(ReloadTaskViewJob.java:92)
> 	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.loadContent(ReloadTaskViewJob.java:65)
> 	at org.eclipse.buildship.ui.view.task.ReloadTaskViewJob.runToolingApiJob(ReloadTaskViewJob.java:55)
> 	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
> 	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
> 	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
>

**Comment by donat** [comment]
Let's continue at #519.

**Comment by leomorgans** [comment]
OK, thanks!. I will follow the issue #519

**Comment by donat** [comment]
@leomorgans I've created a snapshot release containing the fix. Can you please install it and verify if it fixes your problem? The update site urls are:
- http://download.eclipse.org/buildship/updates/e47/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e46/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e45/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e44/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e43/snapshots/2.x/
- http://download.eclipse.org/buildship/updates/e42/snapshots/2.x/

**Comment by leomorgans** [comment]
@donat, I've updated the plugin with the snapshot version for Eclipse 4.6.
But unfortunately I had the same error. 
Below I attached a file with my environment info.

[env-info.txt](https://github.com/eclipse/buildship/files/1142927/env-info.txt)

**Comment by leomorgans** [comment]
@donat 
The problem seems to be with the multiple versions of **com.goole.guava** plugin.
As you can see in the env-info.txt file, I have two different versions of the mentioned plugin:

```
com.google.guava (15.0.0.v201403281430) "Guava: Google Core Libraries for Java" [Resolved]
com.google.guava (21.0.0.v20170206-1425) "Guava: Google Core Libraries for Java" [Resolved]
```

If I delete the com.google.guava (21.0.0.v20170206-1425) version, everything seems to be working well with Buildship.

**Comment by donat** [comment]
Thanks, @leomorgans, that is indeed the source of the problem and also this is what my hotfix tries to patch. I've just found the reason why it didn't work for you. The patched plugin's versions were not changed, which caused the update to ignore them. The latest snapshot fixed that. Would you mind giving it another go?

**Comment by leomorgans** [comment]
@donat 
Everything seems to be alright now.
The problem is fixed.

**Comment by donat** [comment]
Awesome, thanks for checking!
