### ISSUE TITLE
Tasks View: Project name cut off

### ISSUE THREAD

**Issue by kthoms** [eclipse/buildship#522]
The label of a project is cut off, see screenshot. Buildship version 2.0.2.

<img width="617" alt="screenshot 54" src="https://user-images.githubusercontent.com/265597/28128476-21fab6ca-6730-11e7-9897-62e289afaf6b.png">

**Comment by donat** [comment]
Hi! just enable the`Show Headers` from the view's context menu (on the upper left). Then you'll be able to adjust the column width.

**Comment by kthoms** [comment]
Right. But the default experience is wrong. Maybe enable the Show Header setting by default?

**Comment by donat** [comment]
You are correct. In fact, we fixed it for the [2.1.0 release](https://discuss.gradle.org/t/buildship-2-1-0-is-now-available).
