### ISSUE TITLE
compile project('common') can't be included into Web Project (Web Dynamic ) in Eclipse Tomcat Server

### ISSUE THREAD

**Issue by sayseakleng** [eclipse/buildship#523]
Hello! I'm facing a problem in multiple project structure (includeFlat). Projects compile time and building for production are ok. But when I added into eclipse tomcat server plugin, it made java.lang.ClassNotFoundException. It seems like tomcat doesn't recognize project included using **compile project** 
I have to  go to Properties -> Deployment Assembly -> Remove  -> and Add again

**Comment by mauromol** [comment]
Your common project must also apply the "eclipse-wtp" plugin in its build.gradle.
This should fix your issue. Please see https://github.com/gradle/gradle/issues/1333.

**Comment by sayseakleng** [comment]
@mauromol , thank you so much for your comment :)
After applying plugin "eclipse-wtp" on "common" project, the problem still persists :(

I found that in eclipse tomcat deployment folder, exports source folder instead of built jar of "common" project. [Screenshot](https://drive.google.com/open?id=0BwNdJe9ZJKCHbFc4VS14b3BRQkE)

If possible you can have a review on my sample configure project: [Project](https://drive.google.com/open?id=0BwNdJe9ZJKCHTmZ3TkpaVzBrLTQ)

The environment I worked on: Neon.3 and Buildship 2.1.2

Best Regards

**Comment by mauromol** [comment]
@sayseakleng I didn't look at your project, though if you use Buildship 2.x, have both projects (the webapp and the common project) apply 'eclipse-wtp', then issue a Gradle | Refresh Gradle Project on both, you should see the common project in the webapp project deployment descriptor (right click on the webapp project, then Properties | Deployment Descriptor), as "Source" = name of the common project, "Deploy path" = WEB-INF/lib.

If so, remove all modules from your Tomcat server and confirm. Then add again your webapp project to the server and publish: you should see the JAR of the common project in the WEB-INF/lib folder of the published webapp. If you don't do a remove+add, it's possible that WTP does not see the new "structure" of the webapp project and hence it does not publish the dependency common project.

**Comment by mauromol** [comment]
Other things to check after you apply 'eclipse-wtp' plugin on both projects and issue a "Refresh Gradle Project": the common project should have the "Utility module" facet checked (see Properties | Project Facets on the common project) and have its own Deployment Assembly (containing just its src folders deployed at "/").

**Comment by sayseakleng** [comment]
@mauromol It works, it's really a great help.

Because module projects lost, and the following configuration helps:
eclipse.wtp {
	facet {
		facets = []
		facet name: 'jst.java', version:"$sourceCompatibility"
		facet name: 'jst.utility', version:"1.0"
	}
}

Regards and thanks
