### ISSUE TITLE
FixedRequestAttributesBuilder is gone

### ISSUE THREAD

**Issue by martinlippert** [eclipse/buildship#524]
Somehow (I can't find the commit in the repo) the class FixedRequestAttributesBuilder disappeared (or got moved). We are using this class when driving project imports in STS for Gradle projects, so our code breaks at the moment.

Can you provide more details when this class got removed and whether it would be possible to get it back? That would be great.

Thanks!!!

**Comment by oehme** [comment]
This is unintentional, we only plan to break this in 3.0. @donat we should bring it back and clearly document that this is used by STS, so it's easy to spot in code reviews.

**Comment by reyabreu** [comment]
I'v rolled back to  `2.0.1.v20170302-1036` in order to have a working version - looking forward to a fix

**Comment by martinlippert** [comment]
Hey @oehme @donat is there any ETA for bringing back this class/API? People installing Buildship 2.1.x from the Marketplace are still stuck when using this from STS... :-(

**Comment by oehme** [comment]
The tentative release date for 2.1.2 is July 24th (see the milestone on the ticket).

**Comment by martinlippert** [comment]
Ah, great, looks good. Thanks!!!

**Comment by donat** [comment]
@martinlippert We've merged the changes for the STS fix. Can you please give it a try?
Here's the update site url for Eclipse 4.7: http://download.eclipse.org/buildship/updates/e47/snapshots/2.x

**Comment by edeandrea** [comment]
I just verified that 2.1.2.v20170718-1426-s fixes this issue as well as #525.

**Comment by reyabreu** [comment]
Thanks! just verified that I can use the import wizard again successfully after latest STS update to 2.1.2.v20170718-1426-s

**Comment by martinlippert** [comment]
Great, thanks for fixing this!!!

**Comment by martinlippert** [comment]
I can also verify that this works with the latest STS CI builds... :-)
