### ISSUE TITLE
Import options dialog colors not matching Eclipse one (dark theme)

### ISSUE THREAD

**Issue by mimmoz81** [eclipse/buildship#532]
Using buildship 2.1.1 with Dark appearance on Eclipse Oxygen, the Options dialog is not respecting the datk theme (see screenshot).

![immagine](https://user-images.githubusercontent.com/14213760/28412659-28e92578-6d45-11e7-9117-a70991f3755d.png)

**Comment by AndyWu2015** [comment]
I am looking into this , hope this can be fixd soon.

**Comment by AndyWu2015** [comment]
Sorry @donat  and guys , I resigned from my company and will not do eclipse plugins related development , so I would rarely have time to help with this repo. Hope you can do it well in the future.
Regards.
Andy Wu

**Comment by donat** [comment]
I'm sorry to hear that. Good luck in your future endeavours!

**Comment by mimmoz81** [comment]
Closing as resolved, by #683
