### ISSUE TITLE
where to download the dist package other than install it online?

### ISSUE THREAD

**Issue by junneyang** [eclipse/buildship#545]
thanks!

**Comment by donat** [comment]
I'm not 100% sure, what you mean. If you want to download a Gradle distribution manually, then have a look at http://services.gradle.org. Otherwise please elaborate your use-case and we'll see if we can help.

**Comment by junneyang** [comment]
thanks @donat 
i mean how can i get the buildship eclipse plugin offline other than update from eclipse marketplace/install center

i have searched this but without any result
thanks for your help

**Comment by AndyWu2015** [comment]
Hey @junneyang  ， if the reason that you want  dist package is the unstable network, you want to download it manually  and install it locally , I didn't not find it also , but you can try this mirror  , it would be fast. http://ftp.jaist.ac.jp/pub/eclipse/buildship/updates/e46/releases/2.x/2.1.2.v20170807-1321/

**Comment by junneyang** [comment]
@AndyWu2015 
thanks, it works for me!

**Comment by AndyWu2015** [comment]
cause we are both in China...haha
