### ISSUE TITLE
Attach Sources for `gradleApi()` and Similar Dependencies

### ISSUE THREAD

**Issue by cspurk** [eclipse/buildship#547]
When using Gradle distribution specific dependencies like `gradleApi()` or `gradleTestKit()`, Buildship doesn’t attach the sources to the corresponding Eclipse build path dependencies. When working on Gradle plugins, such sources (and the corresponding Javadoc) would often be very helpful, though.

**Comment by AndyWu2015** [comment]
agree with that , I think buildship should download the source jar and attach it just like m2e.

**Comment by samized** [comment]
Would be nice if buildship can solve this problem: https://github.com/gradle/gradle/issues/1003

**Comment by oehme** [comment]
Closing, since this is already tracked by gradle/gradle#1003 and needs to be done in Gradle, not Buildship.

@samized Your workaround should work fine. Have you put some logging in there to see if it is getting invoked?
