### ISSUE TITLE
Buildship is not updating the classpath in Eclipse

### ISSUE THREAD

**Issue by eximius313** [eclipse/buildship#550]
I created empty project using ```gradle init``` and I imported it into Eclipse (Oxygen) using Buildship.
When I added new dependency in build.gradle and hit ```Refresh Tasks for All Projects``` under ```Gradle Tasks``` I can see that dependency is being downloaded, but Eclipse classpath it not being updated (I can not use this library right away).
When I delete the project from Eclipse and import it again using Buildship - classpath is correct and I can use the dependency.

**Comment by oehme** [comment]
As the name of the button implies, it only refreshes the tasks view, nothing else. If you want to refresh your project configuration, you can do so in the context menu of your project or build file.
