### ISSUE TITLE
Implement sorting support in the Gradle Tasks View

### ISSUE THREAD

**Issue by christopherbryanboyd** [eclipse/buildship#554]
Hello all,

the "Gradle Tasks View" has no way to sort the columns.
![screenshot_20170823_202639](https://user-images.githubusercontent.com/31221500/29645224-b31ae7f6-8841-11e7-9eca-0a59eb3461ef.png)

The columns are here (name and description), but are not clickable / sortable.

**Comment by AndyWu2015** [comment]
good idea, I would like to add such feature if Buildship Team agree with it

**Comment by etiennestuder** [comment]
Can you please describe in detail how that sorting should work?
Are you proposing to also sort by description? (I see no value for that)
How would sorting the task column work, sort by group name, or...?

**Comment by AndyWu2015** [comment]
O I see, the task is already sorted by name if you "Group Tasks" in the toolbar of "Tasks View".
That is good enough for me.

**Comment by donat** [comment]
Closing as inactive. @christopherbryanboyd feel free to reopen the issue if you still think it should be implemented.
