### ISSUE TITLE
Can't refresh or configure projects if use gradle javafx plugin 

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#573]
[Report from Patrick Trabocchi](https://bugs.eclipse.org/bugs/show_bug.cgi?id=516883):

Hi to all, i've encountered this problem after adding javafx-gradle-plugin to one of the module in project i'm developing.
The error is about the impossibility to found the 'ant-javafx.jar', error reported is about wrong configuration of JAVA_HOME or missing JDK. Everything is configured properly: JAVA_HOME point to install directory in my HDD and JDK is present.

Before posting here, i've tested the solution proposed here:
https://www.quickprogrammingtips.com/java/how-to-develop-javafx-programs-using-eclipse-and-gradle.html
where the author indicate to add access permission to classpath entry for JRE_LOCATION value.

The error isn't present if i'm run gradle tasks about javafx from console.

buildship: 2.0.2-20170420
JDK: 8u131
gradle-javafx-plugin:8.8.2
Gradle is configured as 3.4 from project init and using wrapper

Best regards

**Comment by donat** [comment]
I tried to reproduce your problem, but for me, everything worked as expected. I used the latest Gradle version and the sample project from the tutorial you linked from the quickprogrammingtips.com website. Then, I applied the `javafx-gradle-plugin` with the minimal configuration from the documentation.

Here's my build script:
```
import org.gradle.plugins.ide.eclipse.model.AccessRule

apply plugin: 'java-library'
apply plugin: 'eclipse'
apply plugin: 'javafx-gradle-plugin'

buildscript {
    dependencies {
        classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: '8.8.2'
    }
    repositories {
        jcenter()
    }
}

repositories {
    jcenter()
}

dependencies {
}

jar {
    manifest {
        attributes 'Main-Class': 'JavaFXDemo'
    }
}

eclipse {
    classpath {
        file {
            whenMerged {
                def jre = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
                jre.accessRules.add(new AccessRule('0', 'javafx/**'))
            }
        }
    }
}

jfx {
    // minimal requirement for jfxJar-task
    mainClass = 'JavaFXDemo'
    
    // minimal requirement for jfxNative-task
    vendor = 'ACME Inc.'
}
```

If it doesn't work for you then feel free to reopen this issue. Also in that case, please provide a sample project so that I can analyze your problem more thoroughly.

**Comment by integrys-net** [comment]
Hi donat, the problem is not using gradle(w) from command line, but in eclipse ide, specifically in Gradle Task, i can't refresh projects.
When i try to do this, eclipse give me the stacktrace pasted here:
https://ghostbin.com/paste/ayhhr
The project is IDE agnostic.

Today i have updated gradle to latest version.
I'm using
Eclipse neon.3
buildship: 2.0.2-20170420
gradle-javafx-plugin:8.8.2

**Comment by oehme** [comment]
Please configure `org.gradle.java.home` in your `~/.gradle/gradle.properties` to point to the right JDK. Ideally the JDK would be configurable in the JavaFX plugin instead of using whatever the daemon is running on.

**Comment by integrys-net** [comment]
oehme, thank you for reply.
Your suggestion solved the problem. I don't know i need to set the value of the `org.gradle.java.home` property in GRADLE_HOME.
Thank you to all, to time used to solve my issue.
Best regards.
