### ISSUE TITLE
Confusing warning decorations on Gradle preference page

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#582]
[Report from Andreas Sewe](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522637)

>Testing the Photon M2 Java EPP package, I found that the Gradle preference page shows Warning decorations even if the "offending" selection wasn't made (see attched screenshot). AFAIK, this is against UI guidelines. Also, I find it personally confusing as well.

![gradle-preference-page](https://user-images.githubusercontent.com/419883/30809740-190e4726-a203-11e7-8ef6-a615ec4c4dcb.png)

**Comment by donat** [comment]
@sewe The purpose of those warnings is to preliminarily inform the users that the marked configuration options may have unwanted side-effects. Would it be better if we simply replace the images? How about the info icon?

**Comment by oehme** [comment]
I think we should only show them if the user actually uses them.
