### ISSUE TITLE
Incorrect JAVA HOME

### ISSUE THREAD

**Issue by sayseakleng** [eclipse/buildship#587]
Hello! I'm facing a problem to execute any task from "Gradle Tasks" view in eclipse.
It always references to wrong JAVA HOME on machine when there are JDK & JRE both are installed.

**Buildship version:**
2.1.2

**System variable:**
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_131

**Eclipse  installed JRE:**
JRE_HOME = C:\Program Files\Java\jdk1.8.0_131\jre

**Buildship task execution:**
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 3.5
Java Home: C:\Program Files\Java\jre1.8.0_144

==> :compileJava FAILED FAILURE: Build failed with an exception

Yours Regards.

**Comment by donat** [comment]
You can configure the Java home via the `org.gradle.java.home` property: https://docs.gradle.org/current/userguide/build_environment.html
