### ISSUE TITLE
Buildship Developer Documentation Workspace has errors after installation

### ISSUE THREAD

**Issue by wodencafe** [eclipse/buildship#589]
When I followed the instructions here:
https://github.com/eclipse/buildship/blob/master/docs/development/Setup.md

I encountered errrors after launching Eclipse and waiting for Oomph to set up the workspace:
![ezgif-2-d67dc927f2](https://user-images.githubusercontent.com/9727493/31348982-f9e8d444-ace6-11e7-9f51-94566d616364.gif)

**Comment by donat** [comment]
Can you please elaborate on the problem?

**Comment by wodencafe** [comment]
Hi @donat, sorry about that! For some reason my description was not saved when I created this bug originally.

**Comment by donat** [comment]
No problem, I just didn't know where to look for the problem. 

It seems that the Oomph setup model is a bit out-of-sync with the current target platform. I'll fix it later. For the time being, you can eliminate the error markers by activating the target platform defined in the `tooling-e47.target` file.

**Comment by donat** [comment]
BTW big 👍 for the animation. I wish every bug report had one.

**Comment by wodencafe** [comment]
Hi @donat, I tried doing what you said, by selecting "Neon" as the "Buildship Target Platform" in Oomph. 

Unfortunately, the workspace still has errors.

**Comment by donat** [comment]
I've adjusted the Oomph configuration and the codebase so that your workspace should not have any exceptions.
