### ISSUE TITLE
could not build plugin with gradle 4.2.1 and java 9.0.1

### ISSUE THREAD

**Issue by hpollak** [eclipse/buildship#603]
cloned the project and tried to build brings (gradle build):
`WARNING: Using incubator modules: jdk.incubator.httpclient

> Task :buildSrc:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/opt/gradle-4.2.1/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
/home/hpollak/Downloads/buildship/buildSrc/src/main/groovy/eclipsebuild/testing/EclipseTestExecuter.java:43: error: cannot find symbol
import org.gradle.internal.time.TrueTimeProvider;
                               ^
  symbol:   class TrueTimeProvider
  location: package org.gradle.internal.time
/home/hpollak/Downloads/buildship/buildSrc/src/main/groovy/eclipsebuild/testing/EclipseTestExecuter.java:250: error: cannot find symbol
        new TestMainAction(detector, processor, new NoOpTestResultProcessor(), new TrueTimeProvider(), testTaskOperationId, rootTestSuiteId, String.format("Gradle Eclipse Test Run %s", testTask.getIdentityPath())).run();
                                                                                   ^
  symbol:   class TrueTimeProvider
  location: class EclipseTestExecuter
2 errors
startup failed:
Compilation failed; see the compiler error output for details.

1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:compileGroovy'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
`

**Comment by hpollak** [comment]
it seams like
org.gradle.internal.time.TrueTimeProvider
has removed in 4.2

**Comment by hpollak** [comment]
Using org.gradle.internal.time.Time.clock() instead of new TimeProvider() works for me

**Comment by donat** [comment]
I'm glad you found the solution. I'll also adjust the Buildship build script code very soon. In fact, I'm in the middle of updating Buildship to use Gradle 4.3.

**Comment by donat** [comment]
@hpollak FYI. The build scripts have been updated to use Gradle 4.3.
