### ISSUE TITLE
Eclipse gluon new project does not finish

### ISSUE THREAD

**Issue by adnion** [eclipse/buildship#606]
"It seems version 2.x of Buildships Gradle has rearranged its packages and contents making the finish button unclickable." [https://stackoverflow.com/questions/42953287/eclipse-gluon-new-project-does-not-finish](https://stackoverflow.com/questions/42953287/eclipse-gluon-new-project-does-not-finish)

Is this the right place for a bug report? If not, just delete and please point me to the appropriate place.
Thank you very much! :)

**Comment by oehme** [comment]
That plugin seems to be calling private APIs which have changed in the meantime. Buildship provides no public API for project import, though we have agreed with a few projects (like STS and jdt.ls) to support a very [limited](https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/workspace/GradleBuild.java#L49) private API until there is a public one. The maintainers of the Gluon project can use that one too.
