### ISSUE TITLE
Unable to reference other gradle project

### ISSUE THREAD

**Issue by totszwai** [eclipse/buildship#609]
Project structure:

> + root
>   + lib-test1
>     - build.gradle
>     - settings.gradle
>   + lib-test2
>     - build.gradle
>     - settings.gradle

The settings.gradle file of my test2:

```
include ':lib-test1'

project(':lib-test1').projectDir = new File(settingsDir, '../lib-test1')

rootProject.name = 'lib-test2'
```

The build.gradle file of my test2:
```
dependencies {
    compile project(':lib-test1')  // line 38
}
```
When I try to refresh the gradle tasks, it failed on my test2:

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\me\Source\Repos\java\lib-test2\build.gradle' line: 38
> 
> * What went wrong:
> A problem occurred evaluating project ':lib-test2'.
> Project with path ':lib-test1' could not be found in project ':lib-test2'.
> 

But there is nothing wrong when I build my test1. And the weird thing is that when I run it in command line, it ran fine?

```
PS C:\Users\me\Source\Repos\java\lib-test2> .\gradlew build
:lib-test1:compileJava
:compileJava
:processResources NO-SOURCE
:classes
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:lib-test1:processResources NO-SOURCE
:lib-test1:classes
:lib-test1:jar
:test NO-SOURCE
:check UP-TO-DATE
:build UP-TO-DATE
:lib-test1:assemble
:lib-test1:compileTestJava NO-SOURCE
:lib-test1:processTestResources NO-SOURCE
:lib-test1:testClasses UP-TO-DATE
:lib-test1:test NO-SOURCE
:lib-test1:check UP-TO-DATE
:lib-test1:build

BUILD SUCCESSFUL

Total time: 6.475 secs

```
I've also tried to clean the project by running the following on both of my projects:

```
./gradlew cleanEclipse
./gradlew cleanEclipseProject
./gradlew cleanEclipseClasspath
./gradlew eclipse
```
I can't get it to work AT ALL.

**Comment by donat** [comment]
Hi! I tried to recreate your project, but it seems fine to me: the task view refresh works as expected.

<img width="1085" alt="screen shot 2017-12-15 at 18 20 11" src="https://user-images.githubusercontent.com/419883/34052914-a2ce7e8a-e1c4-11e7-9e52-36f754adbda6.png">

It might be thought that my project is too simple. Can you please have a look at it and maybe adjust it to exhibit the problem?

https://web.tresorit.com/l#A0klvQqe74II1Wk97Pb2fQ

**Comment by totszwai** [comment]
I can import and load your sample project just fine too... In the end, I had to create a new gradle project from scratch and then bring all the files back into the new project. This is quite annoying, I'm sorry I can't provide any additional information... 

I suspect that it must be some Eclipse gradle files/settings not getting generated properly... Ideally though, I would think that running the following 3 commands would make it a clean slate...

```
./gradlew cleanEclipse
./gradlew cleanEclipseProject
./gradlew cleanEclipseClasspath
```

But it doesn't seem to be the case.

**Comment by donat** [comment]
I'm glad you found the solution. Just one more note: Using Buildship and calling the `gradle eclipseXXX` tasks are mutually exclusive. If you call the tasks basically you generate or delete files that might overwrite the configuration Buildship has set up.
