### ISSUE TITLE
Eclipse: Add dependencies to the module path

### ISSUE THREAD

**Issue by SheridanG** [eclipse/buildship#620]
Eclipse: Oxygen
Buildship: 2.2.0
Gradle: 4.3.1

In Eclipse, when using java8, gradle dependencies are automatically added to the _classpath_ (by Buildship, I believe).

When using java 9 Eclipse defines a _module path_ in addition to the _classpath_. This is visible in the project configuration _Java Build Path / Libraries_ page. The name of the added library is _Project and External Dependencies_.

When using java 9, I would expect the dependencies (especially automatic modules defined from legacy jars) to be added to the _module path_ instead. Without this, references to the given automatic modules cannot be resolved by the Eclipse compiler.

It is possible, of course, to add the jar files one by one, manually, but that is impractical when a project depends on over 60 jars. Moreover, Buildship will remove them all each time the project is resynch with gradle.

**Comment by donat** [comment]
Just to be clear, we haven't added support for developing Java 9 applications in Buildship 2.2, we only made sure that Buildship works when Eclipse is executed on Java 9.

Your proposal makes sense, Buildship should put jars on the module path. The question is: what happens if a jar is *not* a module but declared as one. Unfortunately, Gradle doesn't have this knowledge yet, so for the time being Buildship could either set all of the dependencies as modules or none of them.

In any case, there is a workaround. Adding a jar to the module path can be done with the following snippet.

    apply plugin: 'eclipse'
    
    eclipse {
        classpath {
            file {
                whenMerged {
                    entries.findAll { isModule(it) }.each { it.entryAttributes['module'] = 'true' }
                }
            }
        }
    }

    boolean isModule(entry) {
        // filter java 9 modules
       true
    }

**Comment by SheridanG** [comment]
Thanks for your reply. It tried your suggestion and it works well.

Due to my limited knowledge of gradle I had to struggle with the error:
No such property: entryAttributes for class: org.gradle.plugins.ide.eclipse.model.Output

After a lot of trials & errors, I got it to work by adding:

```
boolean isModule(entry) {
    // filter java 9 modules
	entry.kind == 'lib'  // Only libraries can be modules
}
```

**Comment by donat** [comment]
The entry you get should be an instance of [ClasspathEntry](https://docs.gradle.org/current/javadoc/org/gradle/plugins/ide/eclipse/model/ClasspathEntry.html). You should use those classes.

**Comment by donat** [comment]
I'm closing the issue now. @SheridanG if you have further questions feel free to still ask it here or in a new thread.

**Comment by wbsouza** [comment]
I had a similar problem but combinin sub-projects and jars, the solution was based on @SheridanG  sugestion:

```
apply plugin: 'eclipse'

eclipse {
    classpath {
        file {
            whenMerged {
                entries.findAll { 
                	it.kind == 'src' || it.kind == 'lib' 
                }.each { it.entryAttributes['module'] = 'true' }
            }
        }
    }
}
```

**Comment by telebh** [comment]
I have problem with accessing same class from different packages (classpath and modulepath) I am getting the following error in Eclipse  "The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml", how to resolve this, one jar is from JDK11 and the other in Maven dependency
