### ISSUE TITLE
Add Eclipse Source Reference Headers to MANIFEST.MF

### ISSUE THREAD

**Issue by fbricon** [eclipse/buildship#621]
Can you please add Eclipse Source Reference Headers (`Eclipse-SourceReferences` attribute) to Buildship's various MANIFEST.MFs, as described in https://wiki.eclipse.org/PDE/UI/SourceReferences, so that we can easily reference the source code associated with the various binaries.

**Comment by donat** [comment]
@fbricon Is it possible to specify a commit hash in the header entry? Something like 

```
Eclipse-SourceReferences: scm:git:https://github.com/eclipse/buildship.git;tag=2e93d866714a6274bd27f50d7bca322597f2b73
```

If so then we can associate all releases with the sources.

**Comment by donat** [comment]
Sorry, found my answer. FTR: 
``` 
Eclipse-SourceReferences: scm:git:git://git.eclipse.org/gitroot/platfo
 rm/eclipse.platform.team.git;path="bundles/org.eclipse.compare";tag="
 I20180418-2000";commitId=b771accd19e5806552c113be35e86e4f8bd9429b
```

**Comment by donat** [comment]
Fixed by https://github.com/eclipse/buildship/commit/4330972ee476ae203d3df81535064ee5668cb2f3 on master and https://github.com/eclipse/buildship/commit/aca9a98b3eb3b4a6e98308aad0a6292ef0074f48 on release.
