### ISSUE TITLE
Arguments tab should let users specify properties with spaces

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#624]
Original report: 

https://discuss.gradle.org/t/program-arguments-with-spaces/25136

On the command line, you can specify arguments with spaces:

    -Parg='foo bar'

The arguments tab on the other hand don't let you do this. The corresponding code:
```
GradleRunConfigurationAttributes.applyArgumentExpressions(CollectionsUtils.splitBySpace(this.argumentsText.getText()), configuration);
```

**Comment by hanct** [comment]
Is this issue solved? If not, we can't pass multiple arguments via buildship.

**Comment by donat** [comment]
@hanct I've fixed it in the [latest snapshot](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md). If you have time give it a try and give us feedback.
