### ISSUE TITLE
Can't import a project from git and use the "new project wizard" to create an Eclipse Gradle project

### ISSUE THREAD

**Issue by guss77** [eclipse/buildship#626]
I'm using a non-default configuration for the Eclipse GIT plugin, where the git repository is inside the working copy (the standard way for the `git clone` command, which is unfortunately not supported well under Eclipse).

Steps:

 * Import
 * Project From GIT -> Clone URI
 * Paste the URI in the dialog -> Next
 * Verify all branches are selected -> Next
 * Under "Destination", click "Browse" and select the workspace directory -> Next
 * Under "Select a wizard to use" select "Import using the New Project Wizard" -> Finish
 * Select "Gradle" -> "Gradle Project"
 * In "New Gradle Project":
    * make sure "Project location" has "use default" checked
    * under "Project name", type the name of the project from the git URI

Expected:
 * We should be able to click "Next" and create the Gradle project setting

Actual:
 * An error message appears: "Target project directory already exists", and both "Next" and "Finish" buttons are disabled.

This works well for the "New Java Project" wizard.

**Comment by donat** [comment]
It's a bit interesting that the git plugin only allows the users to use the _new_, but not the _import_ wizards. In the case of Buildship, the _new_ wizard is designed only to generate template projects, the real import functionality is available in the _import_ wizard.

I'd suggest using the 'import as general projects' option in the git wizard, then adding the Gradle nature to the root project (right-click > Configure > Add Gradle Nature) and executing the Gradle project synchronization.

**Comment by guss77** [comment]
I think there is some confusion here about what is an "Import wizard" and what its supposed to do - which is, IMO, to import things from outside the Eclipse workspace. To adopt things that are already in the workspace directory and just not listed as a project in Eclipse, you use the "new project wizard". 

This is how it works for the Java toolkit, the PHP toolkit, the DLTK and any toolkit I've ever used. So, for example, there is no "Java import wizard", there's just the "New Java project" wizard which you can use to create the relevant Eclipse metadata files in an existing directory. You can, as a further example, import an EAR file, a C++ executable, a Phar archive or things of that nature.

I believe that the "new Gradle project" functionality not supporting creating the Gradle project configuration in an existing directory is inconsistent with the rest of the Eclipse ecosystem and is a surprising behavior for Eclipse users.

**Comment by donat** [comment]
Thanks for the explanation. I think your proposal makes sense. I'll create a separate issue
 summarizing the expected behavior.
