### ISSUE TITLE
Integrate Java Software Model

### ISSUE THREAD

**Issue by dhakehurst** [eclipse/buildship#627]
I am trying out the Java Software Model [https://docs.gradle.org/current/userguide/java_software.html]

e.g.
apply plugin: 'jvm-component'
apply plugin: 'java-lang'

the buildship plugin for eclipse doesn't recognise my gradle project as a java project.

**Comment by oehme** [comment]
The java software model is [no longer being developed](https://blog.gradle.org/state-and-future-of-the-gradle-software-model), so we won't offer support for it.
