### ISSUE TITLE
Mark Gradle's build directories as derived resources

### ISSUE THREAD

**Issue by tbrannt** [eclipse/buildship#630]
Reopening https://jira.spring.io/browse/STS-2832

> By default the command-line gradle outputs to the project's build directory. The default Eclipse output is the bin directory. These should remain separate.
> 
> The Eclipse resource view includes the compiled files in the build directory. It would improve the usability if these directories were marked as "derived" when importing a project.
> 
> The workaround [1] of rewriting the project file to add resource filters is error prone and resulted in STS-2822. It would be nice if this was part of the plugin instead.
> 
> [1] http://forums.gradle.org/gradle/topics/eclipse_generated_files_should_be_put_in_the_same_place_as_the_gradle_generated_files

I came across the exact problem described in STS-2832 while using buildship. However this issue was closed with a hint to reopen it here.

**Comment by oehme** [comment]
They are already marked as derived. If this is not working for you, can you please provide a reproducible example project?

**Comment by donat** [comment]
Closing as inactive. Feel free to reopen if this is still an issue.

**Comment by tbrannt** [comment]
Ok, turns out this was because I had 1 gradle root project and 3 child projects. I only got the class files in the "Open Resource" dialog because the search included the parent project. I created a workingset without the parent project and selected that working set for my "Open Resource" dialog. Now it works fine.
