### ISSUE TITLE
Buildship does not use gradle.properties on initial download of wrapper

### ISSUE THREAD

**Issue by David-NYC** [eclipse/buildship#640]
I have been trying to create a new Gradle project using Buildship, but I get the following error within the wizard:

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This is happening because our proxy uses an intermediate certificate that must be trusted. Therefore I want to use a new truststore file. Unfortunately, it appears as though Buildship tries to download the initial wrapper prior to checking the gradle.properties file, so it does not pick up the proper truststore.
gradle.properties:
org.gradle.jvmargs=-Djavax.net.ssl.trustStore=C:\certs\cacerts -Djavax.net.ssl.trustStorePassword=changeit

Are there any options within Eclipse that I can set that buildship will use? I modified my jvm args within my sts.ini file, but they do not seem to be applied either.
STS.ini:
-javax.net.ssl.trustStore=C:\certs\cacerts
-javax.net.ssl.trustStorePassword=changeit

**Comment by donat** [comment]
To communicate with Gradle, Buildship uses the `Tooling API` module which runs within the JVM hosting Eclipse. I think you can fix the problem by adding the `-Djavax.net.ssl.trustStore=...` argument to the `eclipse.ini` file: https://wiki.eclipse.org/Eclipse.ini

**Comment by David-NYC** [comment]
That's what I thought as well, but the STS.ini is the equivalent of the eclipse.ini. As I stated previously, this doesn't seem to work for Buildship. It works for the eclipse marketplace, but for some reason the Tooling API must not use those arguments when invoking the jvm.

**Comment by David-NYC** [comment]
Oops. I'm just careless. I forgot the "-D" in my options in the STS.ini file. You can see from my original post.
