### ISSUE TITLE
Cannot install Buildship 2.2 with p2 director

### ISSUE THREAD

**Issue by eheck-is** [eclipse/buildship#641]
Using the following
`eclipse -application org.eclipse.equinox.p2.director -installIU org.eclipse.buildship.feature.group -repository http://download.eclipse.org/buildship/updates/e47/releases/2.x`

I get
`Installing org.eclipse.buildship.feature.group 2.2.0.v20171211-1404.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: Buildship: Eclipse Plug-ins for Gradle 2.2.0.v20171211-1404 (org.eclipse.buildship.feature.group 2.2.0.v20171211-1404)
 Missing requirement: Buildship, Eclipse Plug-ins for Gradle - Core 2.2.0.v20171211-1404 (org.eclipse.buildship.core 2.2.0.v20171211-1404) requires 'bundle com.google.guava [15.0.0,16.0.0)' but it could not be found
 Cannot satisfy dependency:
  From: Buildship: Eclipse Plug-ins for Gradle 2.2.0.v20171211-1404 (org.eclipse.buildship.feature.group 2.2.0.v20171211-1404)
  To: org.eclipse.buildship.core [2.2.0.v20171211-1404]
Application failed, log file location: [...]`

Problem started with 2.1.1 or 2.1.2. The workaround is to install Guava 15 first from another update site, then install Buildship. Still would prefer if it "just worked".

**Comment by donat** [comment]
For some reason, we no longer include Guava 15 in the update site. I'll investigate.

**Comment by donat** [comment]
Fixed: https://github.com/eclipse/buildship/commit/1361b8bd6e3bacea28d6b8c47efbea5237182279

**Comment by donat** [comment]
It should be fine now. @eheck-is Can you please give the following update site a try?
http://download.eclipse.org/buildship/updates/e47/snapshots/2.x/2.2.1.v20180116-1545-s

**Comment by donat** [comment]
Excellent, thank you for checking!
