### ISSUE TITLE
Ensure proper cross-version coverage

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#650]
We should have proper cross-version coverage for model loading and project synchronization.
After we have all the test coverage, we should explicitly tell what is the minimum supported Gradle version and make Buildship fail early if the user tries to use an unsupported one.

**Comment by oehme** [comment]
Let's rename this issue to "Ensure proper cross-version coverage". We don't need to test the models themselves like we did in tooling-commons if we already have end-to-end coverage in Buildship (after all, the models still need to be used correctly by the calling code).

**Comment by donat** [comment]
I agree. I've just renamed the story.
