### ISSUE TITLE
On added event for imported Gradle project, the Gradle nature is not set on the project 

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#652]
Erin Harris [reported](https://bugs.eclipse.org/bugs/show_bug.cgi?id=530805):

> We have an IResourceChangeListener that is registered to listen for IResourceChangeEvent.POST_CHANGE events.  On import of a Gradle project that has several sub-projects, when the added event is received for one of the sub-projects the Gradle nature is not set (org.eclipse.buildship.core.gradleprojectnature).  It is not always the same sub-project and it does not happen 100% of the time.  All of the other sub-projects have the Gradle nature when the added event is received, it is usually just one of them that doesn't.  Also, I could not reproduce this problem with 3 sub-projects or less.  Once I had 4 sub-projects then I could reproduce the problem.

> We have similar code for Maven and do not see the same issue with it.

Attached is a zip file of the project used.  Unzip it and in the top level parent project do a "gradle build".  Then import the top level project into eclipse as an existing Gradle project.  We are using Oxygen2 (4.7.2).

> I could reproduce this problem both on Windows 10 and RedHat 7.4.

[https://app.zenhub.com/files/32398083/3cb6c9ad-79a4-43e0-86c1-3612b4bcef78/download](https://app.zenhub.com/files/32398083/3cb6c9ad-79a4-43e0-86c1-3612b4bcef78/download)

**Comment by donat** [comment]
I probably happen because the synchronization operation is not an atomic operation and you receive the project added event is broadcasted before the project is assigned to the project. We fixed this issue in the latest Buildship 3.0 snapshot (by wrapping the synchronization in an `IWorkspaceRunnable`). Could you please verify that it works for you?

**Comment by oehme** [comment]
@donat We [already do that](https://github.com/eclipse/buildship/blob/7a47f49855ab655a090f211444d2e32e8a4122a6/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/workspace/internal/SynchronizeGradleBuildOperation.java#L131) in 2.x.

Note that this is intentionally only wrapping each individual project. Wrapping the whole build leads to too much memory pressure as Eclipse buffers all the notifications. This was a big problem for larger projects, so we shouldn't change that in 3.0

**Comment by donat** [comment]
With Buildship 3.0, you don't have to rely on resource change listeners anymore. There's a new extension point called `project configurators` which lets you hook into the project synchronization.
