### ISSUE TITLE
Custom classpath provider removed from launch config during synhronization

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#653]
## Original report
https://discuss.gradle.org/t/launchers-lose-buildship-classpath-on-import-regain-it-later

## Actual behavior
The problem happens when the launch configurations are stored in a project file. If the project containing a launch config is synchronized before the project referenced in the launch config then the custom provider is removed. 

## Expected behavior
The launch config should stay untouched during the synchronization. We should refresh the launch configs after all projects are imported into the workspace (e.g as the last operation in `SynchronizeGradleBuildsJob.synchronizeBuild()`).

**Comment by donat** [comment]
An alternative solution would be never to delete the classpath provider attribute. If we do this, we should make sure that the classpath provider falls back to the default provider for non-Gradle projects.

**Comment by thomasmhofmann** [comment]
I see this too when upgrading the buildship version in Eclipse. Is there any news on this?

**Comment by krivanekm-javlin** [comment]
Started happening with Buildship 3.1.5.v20210113-0929 after upgrading from Eclipse 2020-06 to 2021-09.

**Comment by donat** [comment]
The current implementation no longer uses custom classpath providers as they were replaced by test sources. If you look at the [implementation](https://github.com/eclipse/buildship/blob/master/org.eclipse.buildship.core/src/main/java/org/eclipse/buildship/core/internal/launch/DefaultExternalLaunchConfigurationManager.java#L101) the classpath provider gets removed if 
- Gradle version > 5.6
- Eclipse version > 4.8
