### ISSUE TITLE
Buildship doesn't download source jar of dependency 

### ISSUE THREAD

**Issue by chhex** [eclipse/buildship#655]
If Buildship is used along side m2e with the same local maven repository , Buildship doesn't download the source code of a dependency if it has already been downloaded by m2e. m2e has the option the download the source lazy. This makes migrating from m2e to Buildship very cumbersome. As a work around is  to delete the needed dependencies in the local repository and refresh the gradle model to force again a download of all jars. On windows in order to do this i need to exit eclipse. 
I would be very helpful if Buildship would also be capable to download the source code of a dependency lazy.

**Comment by oehme** [comment]
> Buildship doesn't download the source code of a dependency if it has already been downloaded by m2e

That's because Gradle reuses the jars that Maven already downloaded. It will attach that as the source instead. If this doesn't work for you, please provide a reproducible example project.

**Comment by chhex** [comment]
Exactly. With m2e, you have in the preferences the option *not* to (eagerly) to download the source jars with the binary jars:  the unchecked Download Artifact Sources option. So you have only the binary jars in the local repo - at least initially.   But m2e downloads in this case the source jars lazy , when you select in the Maven Dependencies a class File of a Dependency.  
This isn't the case with Buildship. So basically it would be nice if Buildship would implement a simliar feature: When a class file is selected in the Project and External Dependencies and the source jar isn't found,  the source jar is downloaded then (if available)

**Comment by oehme** [comment]
The sources are always downloaded for all dependencies if they aren't already there, so I don't understand the problem yet. The title of your issues says "Buildship doesn't download sources", but it does always and eagerly.

Lazy downloads are not something we plan to support.

**Comment by chhex** [comment]
Well, that's the problem:  the dependency is there - the binary jar, but the source jar not, since m2e DOES support lazy downloading. Which is i find a nice and useful feature, with two goals: safe space and bandwith. 
But ok. if  it's not planed, and community feedback  resp. real life requirements aren't important for Buildship, so be it.

**Comment by oehme** [comment]
When the source jar isn't there, Gradle will download it. 

If that's not working, please provide a reproducible example.

**Comment by oehme** [comment]
Yes, no matter what. If that doesn't happen you'd have found a bug, which is why I'm asking for a reproducible example :)

**Comment by chhex** [comment]
"Yes, no matter what. If that doesn't happen you'd have found a bug"
ahhh, ok , sorry for the misunderstanding ;-) 
"which is why I'm asking for a reproducible example :)"
I can do that.  Sorry if for asking stupid. 
Would a eclipse workspace with two small projects , each with the same dependency, but one m2e and one gradle project and the corresponding local mavenrepo do?

**Comment by oehme** [comment]
Yes, that would be a great setup.

**Comment by chhex** [comment]
Great i ll do (.... and then it probably works, haha ;-)

**Comment by chhex** [comment]
I created a small example at https://github.com/chhex/buildship-test, which reproduces the situation.

**Comment by chhex** [comment]
Yes exactly, i knew that. But with having only

`repositories {
    mavenCentral()
}`
The dependencies are downloaded to Gradle's cache. 

But since we in the course of migrating to Gradle  - and this will take us some time  - we have Maven projects side by side, which is why we configure explicitly mavenLocal, so that all Projects share locally the repos. 

Explicitly have both configured 
`repositories {
   mavenLocal()
    mavenCentral()
}`

doesn't help.

**Comment by oehme** [comment]
Having both configured should work. Does it not in the example you prepared?

**Comment by chhex** [comment]
"Having both configured should work, but is unnecessary for the reason I mentioned - Gradle already reuses jars from .m2 before downloading."
Ah ok. So Gradle copies the jars implicitly from mavenLocal() to the Gradle cache, if they are there? From where does Gradle know to do that?  
I see in the  Project and Dependencies Container of the Gradle project the jars from there only when mavenLocal()  is explicitly declared.  Otherwise the jars are from the Gradle cache
"When using mavenCentral in the example you prepared it still doesn't work?"
Just tried again, no, doesn't work.

**Comment by oehme** [comment]
Gradle does not copy them, it just uses them if the checksums match the checksums on the server. If it has them in its own cache it will use those of course.

**Comment by chhex** [comment]
Interesting is though  that in the Szenario explained  when mavenLocal() ist declared i see the jar  in the Project and External Dependencies pointing to the local Maven Repository ...as expected ... and yes there is any source jar there ... as explained.

When i have only mavenCentral() declared it points to the Gradle cache, in which case i also have the Source jar

**Comment by oehme** [comment]
> So yes in the first case, Buildship doesn't have a Source Jar attached and would need some lazy loading mechanism ....

Buildship doesn't do anything here. Gradle resolves dependencies, not Buildship. And when you tell Gradle to *only* use `mavenLocal`, then it won't look anywhere else. It's doing what you tell it to do :)

I just tested your example and all you need to do is remove `mavenLocal()` or make it the second repository. Gradle will not mix artifacts from different repositories when they belong to the same coordinates. It'll either take it fully from `mavenLocal` or fully from `mavenCentral`. Since you made `mavenLocal` the first, it didn't find anything there and stopped.

I was wrong when I said Gradle uses the .m2 jar directly. It does copy it over into its own cache, but it doesn't re-download. The copy is done so we don't have to keep re-checking the checksum on every build (since Maven could change the file, e.g. when updating a SNAPSHOT).

So you do pay a cost in the form of disk space, but there will be no additional downloads.

**Comment by chhex** [comment]
So basically you are basically confirming what we observed: 
The repository declaration order defines Gradle's lookup order for the artifacts. 
And since it is found first in mavenLocal: that's it, meaning no source jars.  
For us reversing the search order is no option, because, as said,  we have gradle and m2e said by side and want to at least retrieve from and publish to the same local Repository, without having to go through the build server. Specially since the m2e and gradle projects don't know of each other in the workspace. 
What is new for me is that Buildship is out of the game here, unlike m2e, which does load missing jars lazily. So we are left we the option the turn on the downloading of source jars option in m2e generally.

**Comment by oehme** [comment]
> For us reversing the search order is no option, because, as said, we have gradle and m2e said by side and want to at least retrieve from and publish to the same local Repository

I don't understand how reversing the order would be a problem here. Gradle will first look on `mavenCentral`, where it obviously won't find things you published locally. Then it'll continue to `mavenLocal` and find the things you published locally. `mavenLocal` should basically never be the first repo in the list.

**Comment by chhex** [comment]
Good point. And best thanks for your patience. 

But since we are developing with SNAPSHOTs and with our own Remote Repository , proxying for example also to MavenCentral ... so we effectively have something like: 

`repositories {
		mavenLocal()
		maven { url "http://mavenrepo.xxxxxx.ch/nexus/content/groups/public/" }
		maven { url "http://mavenrepo.xxxxxx.ch/nexus/content/repositories/releases/" }
		maven { url "http://mavenrepo.xxxxxx.ch/nexus/content/repositories/snapshots/" }
		maven { url "http://mavenrepo.xxxxxx.ch/nexus/content/groups/public-snapshots/" }
	}`

So if we install  a SNAPSHOT to mavenLocal() in a m2e project, the gradle project would stick to the "older" snapshot from remote , if we reverse the order.

**Comment by oehme** [comment]
> the gradle project would stick to the "older" snapshot from remote , if we reverse the order.

Got it, I didn't think about that use case. This is something we intend to fix by the way, so Gradle will keep searching for newer snapshots in other repositories.

In the meantime I think there is no better workaround than to let Maven download sources at all times.

**Comment by chhex** [comment]
Great thanks for patience! Btw u guys are doing a great job. It just takes some time to get all the code over to gradle.

**Comment by schuettec** [comment]
> This is something we intend to fix by the way,

...okay but this issue has been closed? Where to track progress of this issue then?
I'm still having problems with Gradle not supporting Maven Local and other repositories.

**Comment by chhex** [comment]
Yep, whould be great to habe a issue number to track this problem: getting the newest snapshot version of all repositories, not just the first found.

**Comment by oehme** [comment]
https://github.com/gradle/gradle/issues/1737
