### ISSUE TITLE
If your gradle build requires any in-line parameters, import/refresh fails

### ISSUE THREAD

**Issue by aram535** [eclipse/buildship#659]
Version being used: 2.2.1

When importing a new project or refreshing a project, if the build.gradle requires an inline parameter it fails. 

The most likely scenario is that you have to pass a hostname or auth information to Gradle.  In my case, a sub-task requires dbPassword to be presented if connecting to the database, this isn't normal function but is required for the sub-task.  The import fails because the variable is missing.  The workaround was to define the variable in the ext {} block but then every update to the build.gradle has the same problem after the import since the -PdbPassword argument is missing.

**Comment by oehme** [comment]
I'm not sure what you mean by in-line parameters. If your build uses project properties, it should always have a sensible fallback for when a property is missing. Importing a project into the IDE should not require passing properties. Failures should only happen when running tasks that need those properties.
