### ISSUE TITLE
Gradle editor does not show useful information in the status bar

### ISSUE THREAD

**Issue by veita** [eclipse/buildship#666]
Gradle Build Script Editor editor should display the usual editor information in the status bar.

This enables users e.g. to quickly find lines where a build script error occurred.

**Comment by donat** [comment]
This is actually implemented in the 3.x stream. We synchronization errors as error markers. You can install the latest snapshot from the [update sites](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md). The snapshot builds are pretty stable as the development is happening on separate feature branches.

Also, please let us know what do you think of the latest state.
