### ISSUE TITLE
spring bootRun throw error

### ISSUE THREAD

**Issue by ppsnumi** [eclipse/buildship#673]
env:
gradle 4.6
eclipse oxygen.2 (4.7.2)
gradle buildship 2.2.1, 2.1.2 
spring boot 1.5.10

error throwing when my smtpApplication run bootRun task.
SmtpApplication is main class and find it correct but run incorrect class or command parameter
but work fine after command line enter "gradle bootRun"

log:
Working Directory: D:\Dev\workspace\smtp
Gradle User Home: C:\Users\user
Gradle Distribution: Local installation at D:\Dev\apps\gradle-4.6
Gradle Version: 4.6
Java Home: D:\Dev\apps\jdk1.8.0_162
JVM Arguments: None
Program Arguments: --debug
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: bootRun

...
12:55:26.985 [DEBUG] [org.gradle.api.Project] Looking for main in: [D:\Dev\workspace\smtp\build\classes\java\main]
12:55:26.989 [INFO] [org.gradle.api.Project] Computed main class: xxx.smtp.SmtpApplication
12:55:26.989 [INFO] [org.gradle.api.Project] Found main: xxx.smtp.SmtpApplication
...
12:55:27.028 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Resolve files of :runtimeClasspath' completed
12:55:27.028 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command 'D:\Dev\apps\jdk1.8.0_162\bin\java.exe''. Working directory: D:\Dev\workspace\smtp Command: D:\Dev\apps\jdk1.8.0_162\bin\java.exe -DapplicationXMI=org.eclipse.ui.workbench/LegacyIDE.e4xmi -Dawt.toolkit=sun.awt.windows.WToolkit -Dds.delayed.keepInstances=true -Declipse.application=org.eclipse.ui.ide.workbench -Declipse.buildId=4.7.2.M20171130-0510 -Declipse.commands=-os
win32
-ws
win32
-arch
x86_64
-showsplash
D:\Dev\apps\eclipse\\plugins\org.eclipse.epp.package.common_4.7.2.20171218-0600\splash.bmp
-launcher
D:\Dev\apps\eclipse\eclipse.exe
-name
Eclipse
--launcher.library
D:\Dev\apps\eclipse\\plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.551.v20171108-1834\eclipse_1630.dll
-startup
D:\Dev\apps\eclipse\\plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
--launcher.appendVmargs
-product
org.eclipse.epp.package.jee.product
-Xverify:none
-vm
D:/Dev/apps/jdk1.8.0_162/jre/bin/server/jvm.dll
 -Declipse.home.location=file:/D:/Dev/apps/eclipse/ -Declipse.launcher=D:\Dev\apps\eclipse\eclipse.exe -Declipse.launcher.name=Eclipse -Declipse.p2.data.area=@config.dir/../p2/ -Declipse.p2.profile=epp.package.jee -Declipse.product=org.eclipse.epp.package.jee.product -Declipse.startTime=1520653511249 -Declipse.stateSaveDelayInterval=30000 -Declipse.vm=D:/Dev/apps/jdk1.8.0_162/jre/bin/server/jvm.dll -Declipse.vmargs=-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Xms2G
-Xmx2G
-data "D:\Dev\workspace"
-Djava.net.preferIPv4Stack=true
-Djava.class.path=D:\Dev\apps\eclipse\\plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar
 -Dequinox.init.uuid=true -Dequinox.use.ds=true -Dfile.encoding.pkg=sun.io -Dfile.separator=\ -Dgosh.args=--nointeractive -Djava.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment -Djava.awt.printerjob=sun.awt.windows.WPrinterJob -Djava.class.path=D:\Dev\apps\gradle-4.6\lib\gradle-launcher-4.6.jar -Djava.class.version=52.0 -Djava.endorsed.dirs=D:\Dev\apps\jdk1.8.0_162\jre\lib\endorsed -Djava.ext.dirs=D:\Dev\apps\jdk1.8.0_162\jre\lib\ext;C:\Windows\Sun\Java\lib\ext -Djava.home=D:\Dev\apps\jdk1.8.0_162\jre -Djava.library.path=D:\Dev\apps\jdk1.8.0_162\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;D:/Dev/apps/jdk1.8.0_162/jre/bin/server;D:/Dev/apps/jdk1.8.0_162/jre/bin;D:/Dev/apps/jdk1.8.0_162/jre/lib/amd64;C:\ProgramData\Oracle\Java\javapath;D:\oracle\product\11.2.0\client_2\bin;D:\oracle\product\11.2.0\client_1\bin;D:\Java\erl9.0\bin;D:\Java\rabbitmq_server-3.6.10\sbin;D:\Java\filebeat-5.3.0\bin;D:\Java\elasticsearch-5.3.0\bin;D:\Java\logstash-5.3.0\bin;D:\Java\hazelcast-3.8.3\bin;D:\Dev\apps\jdk1.8.0_162\bin;D:\Dev\apps\gradle-4.6\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDkIA Corporation\PhysX\Common;E:\programming\curl\curl_7_53_1;D:\Dev\apps\eclipse;;. -Djava.net.preferIPv4Stack=true -Djava.runtime.name=Java(TM) SE Runtime Environment -Djava.runtime.version=1.8.0_162-b12 -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.vendor=Oracle Corporation -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=http://bugreport.sun.com/bugreport/ -Djava.version=1.8.0_162 -Djava.vm.info=mixed mode -Djava.vm.name=Java HotSpot(TM) 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Oracle Corporation -Djava.vm.version=25.162-b12 -Djnidispatch.path=C:\Users\user\AppData\Local\Temp\jna-3599307\jna4670851901676208977.dll -Dlibrary.jansi.path=C:\Users\user\native\jansi\1.14\windows64 -Dline.separator=
 -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog -Dorg.eclipse.debug.ui.breakpoints.toggleFactoriesUsed=true -Dorg.eclipse.equinox.launcher.splash.location=D:\Dev\apps\eclipse\\plugins\org.eclipse.epp.package.common_4.7.2.20171218-0600\splash.bmp -Dorg.eclipse.equinox.simpleconfigurator.configUrl=file:org.eclipse.equinox.simpleconfigurator/bundles.info -Dorg.eclipse.m2e.log.dir=D:\Dev\workspace\.metadata\.plugins\org.eclipse.m2e.logback.configuration -Dorg.eclipse.swt.internal.deviceZoom=100 -Dorg.eclipse.update.reconcile=false -Dorg.osgi.framework.executionenvironment=OSGi/Minimum-1.0,OSGi/Minimum-1.1,OSGi/Minimum-1.2,JavaSE/compact1-1.8,JavaSE/compact2-1.8,JavaSE/compact3-1.8,JRE-1.1,J2SE-1.2,J2SE-1.3,J2SE-1.4,J2SE-1.5,JavaSE-1.6,JavaSE-1.7,JavaSE-1.8 -Dorg.osgi.framework.language=ko -Dorg.osgi.framework.os.name=Windows8 -Dorg.osgi.framework.os.version=6.3.0 -Dorg.osgi.framework.processor=x86-64 -Dorg.osgi.framework.storage=D:\Dev\apps\eclipse\configuration -Dorg.osgi.framework.system.capabilities=osgi.ee; osgi.ee="OSGi/Minimum"; version:List<Version>="1.0, 1.1, 1.2",osgi.ee; osgi.ee="JRE"; version:List<Version>="1.0, 1.1",osgi.ee; osgi.ee="JavaSE"; version:List<Version>="1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8",osgi.ee; osgi.ee="JavaSE/compact1"; version:List<Version>="1.8",osgi.ee; osgi.ee="JavaSE/compact2"; version:List<Version>="1.8",osgi.ee; osgi.ee="JavaSE/compact3"; version:List<Version>="1.8" -Dorg.osgi.framework.system.packages=javax.accessibility,javax.activation,javax.activity,javax.annotation,javax.annotation.processing,javax.crypto,javax.crypto.interfaces,javax.crypto.spec,javax.imageio,javax.imageio.event,javax.imageio.metadata,javax.imageio.plugins.bmp,javax.imageio.plugins.jpeg,javax.imageio.spi,javax.imageio.stream,javax.jws,javax.jws.soap,javax.lang.model,javax.lang.model.element,javax.lang.model.type,javax.lang.model.util,javax.management,javax.management.loading,javax.management.modelmbean,javax.management.monitor,javax.management.openmbean,javax.management.relation,javax.management.remote,javax.management.remote.rmi,javax.management.timer,javax.naming,javax.naming.directory,javax.naming.event,javax.naming.ldap,javax.naming.spi,javax.net,javax.net.ssl,javax.print,javax.print.attribute,javax.print.attribute.standard,javax.print.event,javax.rmi,javax.rmi.CORBA,javax.rmi.ssl,javax.script,javax.security.auth,javax.security.auth.callback,javax.security.auth.kerberos,javax.security.auth.login,javax.security.auth.spi,javax.security.auth.x500,javax.security.cert,javax.security.sasl,javax.sound.midi,javax.sound.midi.spi,javax.sound.sampled,javax.sound.sampled.spi,javax.sql,javax.sql.rowset,javax.sql.rowset.serial,javax.sql.rowset.spi,javax.swing,javax.swing.border,javax.swing.colorchooser,javax.swing.event,javax.swing.filechooser,javax.swing.plaf,javax.swing.plaf.basic,javax.swing.plaf.metal,javax.swing.plaf.multi,javax.swing.plaf.nimbus,javax.swing.plaf.synth,javax.swing.table,javax.swing.text,javax.swing.text.html,javax.swing.text.html.parser,javax.swing.text.rtf,javax.swing.tree,javax.swing.undo,javax.tools,javax.transaction,javax.transaction.xa,javax.xml,javax.xml.bind,javax.xml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml.bind.attachment,javax.xml.bind.helpers,javax.xml.bind.util,javax.xml.crypto,javax.xml.crypto.dom,javax.xml.crypto.dsig,javax.xml.crypto.dsig.dom,javax.xml.crypto.dsig.keyinfo,javax.xml.crypto.dsig.spec,javax.xml.datatype,javax.xml.namespace,javax.xml.parsers,javax.xml.soap,javax.xml.stream,javax.xml.stream.events,javax.xml.stream.util,javax.xml.transform,javax.xml.transform.dom,javax.xml.transform.sax,javax.xml.transform.stax,javax.xml.transform.stream,javax.xml.validation,javax.xml.ws,javax.xml.ws.handler,javax.xml.ws.handler.soap,javax.xml.ws.http,javax.xml.ws.soap,javax.xml.ws.spi,javax.xml.ws.spi.http,javax.xml.ws.wsaddressing,javax.xml.xpath,org.ietf.jgss,org.omg.CORBA,org.omg.CORBA_2_3,org.omg.CORBA_2_3.portable,org.omg.CORBA.DynAnyPackage,org.omg.CORBA.ORBPackage,org.omg.CORBA.portable,org.omg.CORBA.TypeCodePackage,org.omg.CosNaming,org.omg.CosNaming.NamingContextExtPackage,org.omg.CosNaming.NamingContextPackage,org.omg.Dynamic,org.omg.DynamicAny,org.omg.DynamicAny.DynAnyFactoryPackage,org.omg.DynamicAny.DynAnyPackage,org.omg.IOP,org.omg.IOP.CodecFactoryPackage,org.omg.IOP.CodecPackage,org.omg.Messaging,org.omg.PortableInterceptor,org.omg.PortableInterceptor.ORBInitInfoPackage,org.omg.PortableServer,org.omg.PortableServer.CurrentPackage,org.omg.PortableServer.POAManagerPackage,org.omg.PortableServer.POAPackage,org.omg.PortableServer.portable,org.omg.PortableServer.ServantLocatorPackage,org.omg.SendingContext,org.omg.stub.java.rmi,org.w3c.dom,org.w3c.dom.bootstrap,org.w3c.dom.css,org.w3c.dom.events,org.w3c.dom.html,org.w3c.dom.ls,org.w3c.dom.ranges,org.w3c.dom.stylesheets,org.w3c.dom.traversal,org.w3c.dom.views,org.w3c.dom.xpath,org.xml.sax,org.xml.sax.ext,org.xml.sax.helpers -Dorg.osgi.framework.uuid=778e745e-328f-4f46-ab50-6656454abfd5 -Dorg.osgi.framework.vendor=Eclipse -Dorg.osgi.framework.version=1.8.0 -Dorg.osgi.supports.framework.extension=true -Dorg.osgi.supports.framework.fragment=true -Dorg.osgi.supports.framework.requirebundle=true -Dos.arch=amd64 -Dos.name=Windows 8.1 -Dos.version=6.3 -Dosgi.arch=x86_64 -Dosgi.bundles=reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar,reference:file:org.eclipse.equinox.simpleconfigurator_1.2.0.v20170110-1705.jar@1:start -Dosgi.bundles.defaultStartLevel=4 -Dosgi.compatibility.bootdelegation=true -Dosgi.compatibility.bootdelegation.default=true -Dosgi.configuration.area=file:/D:/Dev/apps/eclipse/configuration/ -Dosgi.framework=file:/d:/Dev/apps/eclipse/plugins/org.eclipse.osgi_3.12.50.v20170928-1321.jar -Dosgi.framework.extensions=reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar -Dosgi.framework.shape=jar -Dosgi.framework.useSystemProperties=true -Dosgi.frameworkClassPath=., file:d:/Dev/apps/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar -Dosgi.install.area=file:/D:/Dev/apps/eclipse/ -Dosgi.instance.area=file:/D:/Dev/workspace/ -Dosgi.instance.area.default=file:/C:/Users/user/eclipse-workspace/ -Dosgi.logfile=D:\Dev\workspace\.metadata\.log -Dosgi.nl=ko_KR -Dosgi.os=win32 -Dosgi.requiredJavaVersion=1.8 -Dosgi.splashLocation=D:\Dev\apps\eclipse\\plugins\org.eclipse.epp.package.common_4.7.2.20171218-0600\splash.bmp -Dosgi.splashPath=platform:/base/plugins/org.eclipse.platform -Dosgi.syspath=d:\Dev\apps\eclipse\plugins -Dosgi.tracefile=D:\Dev\workspace\.metadata\trace.log -Dosgi.ws=win32 -Dpath.separator=; -Dsun.arch.data.model=64 -Dsun.boot.class.path=D:\Dev\apps\jdk1.8.0_162\jre\lib\resources.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\rt.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\sunrsasign.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\jsse.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\jce.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\charsets.jar;D:\Dev\apps\jdk1.8.0_162\jre\lib\jfr.jar;D:\Dev\apps\jdk1.8.0_162\jre\classes -Dsun.boot.library.path=D:\Dev\apps\jdk1.8.0_162\jre\bin -Dsun.cpu.endian=little -Dsun.cpu.isalist=amd64 -Dsun.desktop=windows -Dsun.io.unicode.encoding=UnicodeLittle -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.6 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=MS949 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level -Dsvnkit.http.methods=Basic -Dsvnkit.library.gnome-keyring.enabled=false -Duser.dir=D:\Dev\apps\eclipse -Duser.home=C:\Users\user -Duser.name=user -Duser.script -Duser.timezone=Asia/Seoul -Dfile.encoding=MS949 -Djava.io.tmpdir=C:\Users\user\AppData\Local\Temp\ -Duser.country=KR -Duser.language=ko -Duser.variant -cp D:\Dev\workspace\smtp\build\classes\java\main;D:\Dev\workspace\smtp\build\resources\main;C:\Users\user\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-jdbc\1.5.10.RELEASE\f78396b57f70a0ca8422bcbe8959aa49baf49023\spring-boot-starter-jdbc-1.5.10.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter\1.5.10.RELEASE\d935ac98f84c1d97d7ccd702d21abdc236fa7aa0\spring-boot-starter-1.5.10.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-logging\1.5.10.RELEASE\62c73688208b3173645d6701fc3eb95ca657e6c8\spring-boot-starter-logging-1.5.10.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.subethamail\subethasmtp\3.1.7\41381242daa11113c32da5b25d001bfdf4df53fb\subethasmtp-3.1.7.jar;C:\Users\user\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.7\557edd918fd41f9260963583ebf5a61a43a6b423\commons-lang3-3.7.jar;C:\Users\user\caches\modules-2\files-2.1\commons-io\commons-io\2.6\815893df5f31da2ece4040fe0a12fd44b577afaf\commons-io-2.6.jar;C:\Users\user\caches\modules-2\files-2.1\javax.mail\mail\1.4.7\9add058589d5d85adeb625859bf2c5eeaaedf12d\mail-1.4.7.jar;C:\Users\user\caches\modules-2\files-2.1\com.github.ulisesbocchio\jasypt-spring-boot-starter\1.18\dc7c35b33473eeb2a4ed655be6e6aa0d7e75a2df\jasypt-spring-boot-starter-1.18.jar;C:\Users\user\caches\modules-2\files-2.1\com.oracle.jdbc\ojdbc6\11.2.0.4.0\a483a046eee2f404d864a6ff5b09dc0e1be3fe6c\ojdbc6-11.2.0.4.0.jar;C:\Users\user\caches\modules-2\files-2.1\com.oracle.jdbc\orai18n\11.2.0.4.0\2ca732c9b5043d39a6b300d190ba0dbce29f3a3\orai18n-11.2.0.4.0.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-autoconfigure\1.5.10.RELEASE\be96efab0d35181f18c486b0ec8d6a41a7042fce\spring-boot-autoconfigure-1.5.10.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework.boot\spring-boot\1.5.10.RELEASE\594b3efa04829f62754a19f59f81ba204636167a\spring-boot-1.5.10.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-jdbc\4.3.14.RELEASE\1b1b9045d9ec1e067d99bf158210e9e7cf2ebfd2\spring-jdbc-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-context\4.3.14.RELEASE\e50a712960926c30e537ef4a633f5d9dd5a8b155\spring-context-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-tx\4.3.14.RELEASE\1c9449fcb805837db3c706eab4c729f89688a267\spring-tx-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-aop\4.3.14.RELEASE\dfe55b0592aead8e3eb0e6a4e98db433b9e09bd7\spring-aop-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-beans\4.3.14.RELEASE\7bcd17a68dd64e9447d7bff2c42ba7417678596e\spring-beans-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-expression\4.3.14.RELEASE\58477b44debcb49b09e962e3047ee74c2c033e89\spring-expression-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.springframework\spring-core\4.3.14.RELEASE\c70ddb6204457a802d1f6882d65bca3e5b3c41df\spring-core-4.3.14.RELEASE.jar;C:\Users\user\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.17\7a27ea250c5130b2922b86dea63cbb1cc10a660c\snakeyaml-1.17.jar;C:\Users\user\caches\modules-2\files-2.1\org.apache.tomcat\tomcat-jdbc\8.5.27\f37dfae9e9afb6b2742e04a401e32264c5fec0ec\tomcat-jdbc-8.5.27.jar;C:\Users\user\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.1.11\ccedfbacef4a6515d2983e3f89ed753d5d4fb665\logback-classic-1.1.11.jar;C:\Users\user\caches\modules-2\files-2.1\org.slf4j\jcl-over-slf4j\1.7.25\f8c32b13ff142a513eeb5b6330b1588dcb2c0461\jcl-over-slf4j-1.7.25.jar;C:\Users\user\caches\modules-2\files-2.1\org.slf4j\jul-to-slf4j\1.7.25\af5364cd6679bfffb114f0dec8a157aaa283b76\jul-to-slf4j-1.7.25.jar;C:\Users\user\caches\modules-2\files-2.1\org.slf4j\log4j-over-slf4j\1.7.25\a87bb47468f47ee7aabbd54f93e133d4215769c3\log4j-over-slf4j-1.7.25.jar;C:\Users\user\caches\modules-2\files-2.1\javax.activation\activation\1.1.1\485de3a253e23f645037828c07f1d7f1af40763a\activation-1.1.1.jar;C:\Users\user\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.25\da76ca59f6a57ee3102f8f9bd9cee742973efa8a\slf4j-api-1.7.25.jar;C:\Users\user\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\1.3.9\40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf\jsr305-1.3.9.jar;C:\Users\user\caches\modules-2\files-2.1\com.github.ulisesbocchio\jasypt-spring-boot\1.18\70b3db6f7186857f6545cec7aca7fa465406c7e6\jasypt-spring-boot-1.18.jar;C:\Users\user\caches\modules-2\files-2.1\org.apache.tomcat\tomcat-juli\8.5.27\583a08f2f59c6abdd86833b572b9a2f55e61a0f2\tomcat-juli-8.5.27.jar;C:\Users\user\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.1.11\88b8df40340eed549fb07e2613879bf6b006704d\logback-core-1.1.11.jar;C:\Users\user\caches\modules-2\files-2.1\org.jasypt\jasypt\1.9.2\91eee489a389faba9fc57bfee75c87c615c19cd7\jasypt-1.9.2.jar xxxx.smtp.SmtpApplication
12:55:27.029 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Environment for process 'command 'D:\Dev\apps\jdk1.8.0_162\bin\java.exe'': {USERDOMAIN_ROAMINGPROFILE=USER-PC, LOCALAPPDATA=C:\Users\user\AppData\Local, PROCESSOR_LEVEL=6, FP_NO_HOST_CHECK=NO, USERDOMAIN=USER-PC, LOGONSERVER=\\USER-PC, JAVA_HOME=D:\Dev\apps\jdk1.8.0_162, SESSIONNAME=Console, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, HAZELCAST_HOME=D:\Java\hazelcast-3.8.3, GRADLE_HOME=D:\Dev\apps\gradle-4.6, PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\, SystemDrive=C:, ERLANG_HOME=D:\Java\erl9.0, APPDATA=C:\Users\user\AppData\Roaming, LOGSTASH_HOME=D:\Java\logstash-5.3.0, USERNAME=user, ProgramFiles(x86)=C:\Program Files (x86), SGHOME=C:\Program Files (x86)\SecureClient\, CommonProgramFiles=C:\Program Files\Common Files, Path=D:/Dev/apps/jdk1.8.0_162/jre/bin/server;D:/Dev/apps/jdk1.8.0_162/jre/bin;D:/Dev/apps/jdk1.8.0_162/jre/lib/amd64;C:\ProgramData\Oracle\Java\javapath;D:\oracle\product\11.2.0\client_2\bin;D:\oracle\product\11.2.0\client_1\bin;D:\Java\erl9.0\bin;D:\Java\rabbitmq_server-3.6.10\sbin;D:\Java\filebeat-5.3.0\bin;D:\Java\elasticsearch-5.3.0\bin;D:\Java\logstash-5.3.0\bin;D:\Java\hazelcast-3.8.3\bin;D:\Dev\apps\jdk1.8.0_162\bin;D:\Dev\apps\gradle-4.6\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDkIA Corporation\PhysX\Common;E:\programming\curl\curl_7_53_1;D:\Dev\apps\eclipse;, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, OS=Windows_NT, COMPUTERNAME=USER-PC, FILEBEAT_HOME=D:\Java\filebeat-5.3.0, FINDBUGS_HOME=D:\Java\findbugs-3.0.1, PROCESSOR_REVISION=5e03, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\Windows\system32\cmd.exe, ProgramData=C:\ProgramData, ProgramW6432=C:\Program Files, HOMEPATH=\Users\user, RABBITMQ_HOME=D:\Java\rabbitmq_server-3.6.10, SystemRoot=C:\Windows, TEMP=C:\Users\user\AppData\Local\Temp, HOMEDRIVE=C:, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel, USERPROFILE=C:\Users\user, TMP=C:\Users\user\AppData\Local\Temp, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, ELASTICSEARCH_HOME=D:\Java\elasticsearch-5.3.0, NUMBER_OF_PROCESSORS=8, windir=C:\Windows, =::=::\}
12:55:27.029 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
12:55:27.029 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'D:\Dev\apps\jdk1.8.0_162\bin\java.exe'.
12:55:27.033 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
12:55:27.033 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
12:55:27.034 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'D:\Dev\apps\jdk1.8.0_162\bin\java.exe''
12:55:27.143 [ERROR] [system.err] 오류: 기본 클래스 1.1,을(를) 찾거나 로드할 수 없습니다.
12:55:27.147 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED

**Comment by donat** [comment]
Closing as inactive. If it's still relevant, please reopen this issue, preferably with a stack trace and a sample project exhibiting the problem.
