### ISSUE TITLE
Collect possible use cases for an initial API

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#676]
Let's collect ideas and use cases on this issue about how the Buildship API should look like.

**Comment by donat** [comment]
As described at #256 Buildship should define a simplistic, synchronous API for project import. Something like this:

    BuildIdentifier id = new BuildIdentifier(directory, gradleDistribution)
    GradleCore.workspace().import(id, monitor)

**Comment by kdvolder** [comment]
Sorry it took a while to get round to responding. Some quick feedback of the top of my head.

1. This should be obvious, but the most important point of a 'stable' api would be that it doesn't change, or if it does it remains backwards compatible.

2. A very important point is that, there must be a way for the caller to determine when the import is finished and whether or not it succeeded. The above api is synchronous so I think that is great in that respect. An async api is also good but must provide a easy way to determine when its finished.

3. The above api may be too simplistic. Probably it would be good to get some information back about what was imported. For example, maybe it was a mutti-project. If an import was succesful I would assume some projects where added/created in the workspace as a result. It would probably be useful to return a list of the added projects.

4. Having to provide a 'gradleDistribution' as a parameter is an inconvenience/difficulty to the caller. How does the caller know which distribution they should pass? Isn't it up to buildship to figure that out based on gradle wrapper etc?

**Comment by kdvolder** [comment]
For reference this is how we currently use (non public) api of buildship at the moment to support the start.spring.io import wizard.

https://github.com/spring-projects/spring-ide/blob/master/plugins/org.springframework.ide.eclipse.buildship20/src/org/springframework/ide/eclipse/buildship20/Buildship20ImportStrategy.java

I think your proposed api would be sufficient to replace that non-public api without any loss of functionality. However, there is one thing that it currently does that is somewhat broken. And perhaps this might be a chance to address that.

Project's in STS need a spring nature added to enable functionalities. In m2e this is done by defining a ProjectConfigurator. This is a mechanism provided by m2e to let other eclipse plugins participate in configuring projects. We didn't have such a mechanism with BuildShip so we did the next best thing we could think of which is, to add the spring nature from our import wizard. But there is a bit of a problem with that. 

1. spring projects imported without using our wizard do not get spring nature added.
2. spring nature has a tendency to get removed from the project if user is sufficiently aggressive at making BuildShip refresh project configuration.

**Comment by kdvolder** [comment]
Another thought came to me. 

In the past I have run into to some difficulties around synchronization rules. I.e. what you pass in Eclipse job api via `Job.setRule`. Typically the import is run from a Job. And the Job needs approrpiate sych rule. If STS is going to call your synchronous api then it will need to know ahead of time what synchronization rule your acync api needs. It is typically not allowed by the Job api to broaden the rule once it has been set. Maybe this comes down to simply documenting the requirements clearly in the api javadoc. However, note that the sync rule should probably be explicitly part of the `API contract` so care should be taken on changing that on subsequent releases.

**Comment by kdvolder** [comment]
Final thought. If you implement the proposed API, it is probably a good idea that I should try it out. I.e. try and implement our 'GradleImportStrategy' object using the proposed api. It is often hard to anticipate subtle issues until you actually try to use an API for real.

So if you have something we can try let me know.

**Comment by donat** [comment]
Thank you for the elaborate answer! My proposed import API above was more of a conversation starter. Nonetheless, we'll definitely try to incorporate your proposals into the API draft. For the time being, I can already answer some of your concerns:

> Having to provide a 'gradleDistribution' as a parameter is an inconvenience/difficulty to the caller. 

The question here is, what should happen during the import. Should the workspace settings always use during the import, or should we expose customization options like the `GradleDistribution` on the API? I'm leaning towards the first one and we can later extend it if required. 

> In the past I have run into to some difficulties around synchronization rules

We refactored the 3.0 branch so that all project synchronization is not based on async jobs. From now on, it will be the client's responsibility to create jobs and job rules.

> So if you have something we can try let me know.

We definitely will. Thanks for all the help!

**Comment by kdvolder** [comment]
> The question here is, what should happen during the import. Should the workspace settings always use during the import, or should we expose customization options like the GradleDistribution on the API? I'm leaning towards the first one and we can later extend it if required.

Actually... to me the question is not so much about 'what should happen'. Its more about 'who is in the best position to know what should happen'. So, for example, I don't really know the answer to your questions. Should it use workspace settings? Should it look inside the project's wrapper? Or should it be something else entirely? Whatever the answer is...my point is... I do not know. And if you provide api that makes me decide this, I may not be in a good position to pass in the right information.

Instead I would hope buildship is in a better position to determine the correct gradle distibution for a given project and so it won't force me, when calling this api to pass in something arbitrary that I didn't have a good way to determine.

Anyhoo... long story short. If you add a parameter like 'gradleDistribution' then make sure it is optional (i.e. the api clearly states I can just pass in 'null' and buildship will do its best to make the most sensible choice).

**Comment by kdvolder** [comment]
BTW: In retrospect... don't get too hung up on my point 3 from above. (i.e. when I said the API may be too simplistic). Shouldn't go overboard in trying to make the api anticipate every possible need.

Perhaps it makes more sense to try and balance between simplicity and point 1. (i.e. stability and backward compatibility).

I.e. for example. I think its a good idea to anticipate returning some information from the operation about what it has done is probably sensible. But it is probably very hard to anticipate all the information that might be useful.

So the API should be designed in such a way that you can extend it easily without breaking backwards compatibility. So, maybe it returns a type called 'ImportResult' (i.e something specific, containing information... not `void`. For now, this 'ImportResult could be as simple as a object that indicates just whether the import succeeded or not. And in the future all sorts of extra attributes could be added without breaking backwards compatibility.

**Comment by kdvolder** [comment]
> We refactored the 3.0 branch so that all project synchronization is not based on async jobs. From now on, it will be the client's responsibility to create jobs and job rules.

That makes sense. However, it probably means the caller has to lock the whole workspace (i.e. use something like `ResourcesPlugin.getRuleFactory().buildRule() ` on its job. This is because the caller really doesn't have any knowledge about what buildship api will do other than that it will make changes to the workspace. So it really can not be more precise.

BuildShip itself might be in a position where it could be more precise but it creates challenges around job composition on the caller's side. For this there's probably no easy answer.

Anyhoo... making the caller responsible for wrapping stuff in jobs and adding the synchronisation around the calls seems like a reasonable choice.

**Comment by UdoW** [comment]
I would like to be able to call Gradle tasks from wizards, event handlers and other UI interfaces.

**Comment by simonjhy** [comment]
I want to make the import API provide some callback interface to let client can know when project successfully import or failed or add some extension points.

**Comment by donat** [comment]
@UdoW see my comments at #723.

**Comment by donat** [comment]
We discussed it internally and concluded that we'll provide the project import API for Buildship 3.0. Thanks everyone for the comments and suggestions. 

I'm closing this issue now. It is just a technicality though, to keep our project board up-to-date. If you have more to add feel free to comment on this ticket or create a new one. 

@kdvolder @simonjhy: keep an eye on #722 and #326 :)

**Comment by donat** [comment]
@UdoW Change of plans. We discussed it internally and decided to implement the [task execution API](#725) as part of Buildship 3.0.

**Comment by donat** [comment]
Hi everyone! Just a quick FYI. I've published the specifications for the proposed Buildship 3.0 APIs:
- hierarchical preferences: https://github.com/eclipse/buildship/issues/732
- project synchronization: https://github.com/eclipse/buildship/issues/256
- Tooling API access: https://github.com/eclipse/buildship/issues/726
- project configurators: https://github.com/eclipse/buildship/issues/326

If you have any concerns or comments, let us know at the corresponding GH issue.

**Comment by donat** [comment]
The project synchronization API is now part of the latest [3.0 snapshots](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md#update-sites-for-buildship-3x).

**Comment by kdvolder** [comment]
@donat Thanks for the headsup, I added a ticket to our backlog for trying out / adopting the new api. 
What's the timeline for releasing BuildShip 3.0, and what's the timeline for dropping the old internal api?

Just so we can have a rough idea on how to prioritize this into our backlog. Thanks for keeping us in the loop, much appreciated.

**Comment by kdvolder** [comment]
Our requirements on the project configurator are probably pretty basic and since we are actually moving away from having a dedicated 'spring nature' this might be even further reduced (really all our configurator did was adding sping nature to projects that look like spring projects). I think @fbricon might have more use cases and be a better person to include in the discussion about project configurators, assuming you haven't asked him already.

For STS our main use case is being able to drive gradle project import from a wizard (mainly so we can have a nice wizard to integrate STS with the https://start.spring.io/ webservice to materialize it's generated projects into the workspace all nicely setup for the user to start coding.

Anyhoo... looks like we will have to work on BuildShip 3.0 connector for our wizard in the near future. Probably planning to do something for next release.

PS: Just thought of another 'job' for the 'project configurator of old' we had before buildship existed. This was also used for enabling / configuring annotation processors. Now to be honest it seems kind of wrong to me that STS would have to be responsible for this via a custom project configurator. I think proper configuraton of annotation processors would be more of the responsibility of BuildShip itself as its really not much different from configuring stuff like the project's classpath, source folders etc. and it isn't really specific to spring or spring boot projects.

**Comment by kdvolder** [comment]
@donat Decided to do a quick pass at updating our connector. It works :-)

I did hit a small snag which I was able to relatively easily work around. But I decided to tell you about it, just in case you might want to do something with that feedback.

The problem: It doesn't seem possible right now for the importing operation to find out what project(s) were imported after import is done.

Now... I'm not really sure I really really need that in the long run, but for now, I guess I do because at the moment we do still support users on the old STS 3 and so we want to add spring nature to the imported spring boot projects.

I worked around it simply by finding the imported project myself using its location. This is fine for the start.spring.io wizard as its really just a single project import. It might be more problematic for use cases importing multi-project builds.

As mentioned before, if there would be a project configurator mechanic, then we would/should probably use that instead of doing some post-import processing in the wizard.

Anyhoo... although taking all this together, my use-case it does not really need to know the imported project, it does seem likely to me that in general, if someone is programatically executing a project import, they may need to be able to discover, after the import completed, which projects were added to the workspace as a result.

Not sure if you'd want to add something to the api for that now, or if you'd rather wait until someone comes up with a real / pressing use case.

**Comment by donat** [comment]
@kdvolder Thanks for all the feedback. We didn't expose the set of changed projects via the synchronization API because it will be available via the project configurator API. That will be implemented very soon and will be part of Buildship 3.0. I have to finish #726, and I'll immediately get started.

**Comment by donat** [comment]
@UdoW https://github.com/eclipse/buildship/issues/726 is almost ready. The only thing missing is to update the Gradle (Tooling API) dependency 5.0, which is supposed to be released at the end of October. You can still try the new API by using the latest 3.0 snapshot. Your feedback is much appreciated.

**Comment by UdoW** [comment]
@donat , where can I find the SNAPSHOT repository?

**Comment by donat** [comment]
@UdoW Here's the update site for Eclipse 2018-09: http://download.eclipse.org/buildship/updates/e49/snapshots/3.x

**Comment by UdoW** [comment]
Ok, thanks. I will try to integrate the new feature into my plug-in.

**Comment by donat** [comment]
Cool! Let me know if something is not clear with the new APIs.

**Comment by UdoW** [comment]
I don't know how to use the API: I found this 

build.withConnection(conn -> conn.newBuild().forTasks("init").run());

on this page https://github.com/eclipse/buildship/issues/726 but it does not work with the snapshot from today.

**Comment by donat** [comment]
@UdoW You can configure the `ModelBuilder` object returned by `newBuild()` to use a custom output stream with the `setStandardOutput()`. By default it is wired to the Gradle UI console  but you can change it to a `ByteArrayOutputStream`.

**Comment by UdoW** [comment]
When I call the above API from my plug-in I get this exception:

`Caused by: java.lang.IllegalStateException: Cannot use Gradle distribution 'https://services.gradle.org/distributions/gradle-4.5-bin.zip' as it has been stopped.
	at org.gradle.internal.concurrent.ServiceLifecycle.use(ServiceLifecycle.java:56)
	at org.gradle.internal.concurrent.ServiceLifecycle.use(ServiceLifecycle.java:46)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.run(DefaultAsyncConsumerActionExecutor.java:49)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:83)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:76)`

What should I do to get rid of the message?

**Comment by UdoW** [comment]
I found this bug report where my exception is explained. But the bug was just closed without a comment how it was fixed: https://bugs.eclipse.org/bugs/show_bug.cgi?id=492118

**Comment by UdoW** [comment]
I try to get a property name from the properties task of my gradle project. I do this with-in an UI handler (a button in the toolbar). Maybe if I call your API from UI produces the problem?

How do you test the API? In which test source can I see how you use it?

**Comment by donat** [comment]
Here's the test that runs a Gradle task: https://github.com/eclipse/buildship/blob/release-3.0/org.eclipse.buildship.core.test/src/main/groovy/org/eclipse/buildship/core/GradleBuildConnectionTest.groovy#L69

**Comment by UdoW** [comment]
Should I call the gradle tooling with-in a Display.syncExec() ?

**Comment by donat** [comment]
Well, technically you should be able to call the APIs from any threads you like. On the other hand, you should not execute any long-running operations on the UI thread, said case included.

**Comment by UdoW** [comment]
I created a test plug-in. See attached ZIP file. Please unpack and set the target file. Then run the plug-in in the runtime Eclipse.

You will see a text button in the toolbar with the label "Run task". It tries to call the properties task.

Then create with the runtime Eclipse a new Gradle project. Then select the project name in the Package Explorer and press the "Run task" toolbar button. 

Then in the Console view of the master Eclipse you see the exception 

`java.lang.IllegalStateException: Cannot use Gradle distribution 'https://services.gradle.org/distributions/gradle-4.8.1-bin.zip' as it has been stopped.
	at org.gradle.internal.concurrent.ServiceLifecycle.use(ServiceLifecycle.java:56)
	at org.gradle.internal.concurrent.ServiceLifecycle.use(ServiceLifecycle.java:46)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor.run(DefaultAsyncConsumerActionExecutor.java:49)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:83)
	at org.gradle.tooling.internal.consumer.DefaultBuildLauncher.run(DefaultBuildLauncher.java:76)
	at de.bs.test.UiHandler.runTask(UiHandler.java:52)
	at de.bs.test.UiHandler.execute(UiHandler.java:35)`

**Comment by UdoW** [comment]
[de.bs.test.zip](https://github.com/eclipse/buildship/files/2614689/de.bs.test.zip)

**Comment by donat** [comment]
Awesome, I'll check the sample project today.

**Comment by UdoW** [comment]
You found the problem? Is it in my code?

**Comment by UdoW** [comment]
@donat , thank you for fixing my usage problem and yes, next time I'll start a new ticket.

**Comment by donat** [comment]
I'm glad I could help :)
