### ISSUE TITLE
Option to attach javadoc when sources are missing?

### ISSUE THREAD

**Issue by mauromol** [eclipse/buildship#681]
Right now, by default Buildship downloads sources and attach them to the JAR artifacts of dependencies.
However, if the source JAR is missing, Buildship does not download Javadoc either.
I would find it extremely useful if Buildship could at least download Javadocs for dependencies for which sources are missing.

I know I can change the build.gradle script and add:

    eclipse {
        classpath {
            downloadJavadoc = true
        }
    }

However, this causes Javadocs for ALL dependencies to be downloaded (even for those having sources).

I would appreciate either a "download Javadoc if sources are missing" default fallback behaviour, or at least an option to download Javadoc only when sources are missing.

**Comment by donat** [comment]
I agree that it would be nice to be able to control source/Javadoc download for each dependency individually. However, the investment needed to implement this outweighs the created value IMHO.

Your second suggestion is interesting. It doesn't make sense to download the sources and the Javadoc at the same time, does it? Maybe the `eclipse` plugin should prioritize the settings such that when
```
eclipse {
    classpath {
        downloadSources = true
        downloadJavadoc = true
    }
}
```
is set then download the sources for all dependencies, then download the Javadoc where the sources are missing. 

This change request is related to #gradle/gradle, could you please move the feature request there?

**Comment by mauromol** [comment]
Hi Donat, as you suggested I opened https://github.com/gradle/gradle/issues/5139
