### ISSUE TITLE
Gradle preference dialog looks horrible in the dark theme

### ISSUE THREAD

**Issue by vogella** [eclipse/buildship#683]
Maybe you are using a hard-coded background color but currently the page is not usable.

![preferences _304](https://user-images.githubusercontent.com/139910/38361772-c989e2c4-38ce-11e8-8a23-634cd62096d1.png)

**Comment by donat** [comment]
There's no color set when the page is created. We only implement a custom `Composite`. I tried to debug it, but I didn't find the solution within the assigned timeframe. 

If anybody has an idea why there are wrong colors, let me know.

**Comment by vogella** [comment]
Is the custom composite an annoymous class or a separate widget?

Donát Csikós <notifications@github.com> schrieb am Fr., 6. Apr. 2018, 10:07:

**Comment by donat** [comment]
It's a separate widget:

    public final class GradleProjectSettingsComposite extends Composite

**Comment by vogella** [comment]
Just add:

GradleProjectSettingsComposite {

    Copy values for composite styling here

}


Currently of my computer hence I don't have access to the values, they
are stored in eclipse.platform.ui in org.eclipse.ui.themes


Donát Csikós <notifications@github.com> schrieb am Fr., 6. Apr. 2018, 11:19:

**Comment by donat** [comment]
I was able to influence the background color of the widget my defining a new `org.eclipse.core.expressions.propertyTesters` extension. However, I failed to compile the css that looks good with both the light and the dark theme. Some help here would be appreciated.

**Comment by donat** [comment]
Btw I don't understand why the children of a custom composite won't inherit the CSS settings from the parent elements. Does every developer have to do the same thing in their Eclipse plugins?

**Comment by vogella** [comment]
> org.eclipse.core.expressions.propertyTesters

This sounds way to complex. I will try to have a quick look

**Comment by vogella** [comment]
![image](https://user-images.githubusercontent.com/139910/38510808-674faade-3c26-11e8-87ae-0e4b804337b3.png)

PR on its way....

**Comment by vogella** [comment]
Here we go: https://github.com/eclipse/buildship/pull/688

**Comment by vogella** [comment]
> Btw I don't understand why the children of a custom composite won't inherit the CSS settings from the parent elements

I believe this is similar to HTML styling H2 does not inherit from H1. So every SWT elements needs either to use the same CSS id or class or separately styled.

**Comment by vogella** [comment]
PR has been merged.

**Comment by mimmoz81** [comment]
this was duplicate of #532. You can close that too.
