### ISSUE TITLE
Syntax highlighting in Text compare view for build.gradle files?

### ISSUE THREAD

**Issue by fapdash** [eclipse/buildship#684]
Would it be possible to also provide syntax highlighting for the Text compare / Git merge view?

![selection_195](https://user-images.githubusercontent.com/459631/38422368-c361b552-39aa-11e8-9e8f-908b541c8bf9.png)

**Comment by donat** [comment]
This would be nice to have, but I don't think we can schedule the implementation anytime soon. I'll leave the issue open, in case somebody wants to vote for it or wants to submit a pull request with the implementation.
