### ISSUE TITLE
"Synchronize Gradle projects ..." blocks deletion of file

### ISSUE THREAD

**Issue by fapdash** [eclipse/buildship#685]
Currently the background synchronization blocks me from deleting files. (might be other actions too, but this is the only reliable reproduction I could find)
Is this really necessary?

Reproduction:
1. Make change to build.gradle to trigger long running sync
2. try to delete a file

Result: async background action becomes blocking with dialog

![knowledgeforge - knowledgeforge-build gradle - spring tool suite _189](https://user-images.githubusercontent.com/459631/38424679-22b84d52-39b2-11e8-9bfd-b8c37ce5cb1b.png)

**Comment by donat** [comment]
This is expected. For the project synchronization, Buildship locks the entire workspace as any workspace project can be changed and new projects can be created in the process. The cancellation should work correctly though, as it is wired to Gradle's cancellation API.
