### ISSUE TITLE
Buildship uses Eclipse Java JRE for imported project

### ISSUE THREAD

**Issue by teuhc** [eclipse/buildship#686]
When we import a gradle Java9 project in eclipse (STS 3.9.2). Buildship uses the Eclipse java path (Version8) to the imported project.

Buildship 2.2.0
STS 3.9.2 - Eclipse Oxygen

**Comment by lukeu** [comment]
I've just written [this comment](https://github.com/eclipse/buildship/issues/687#issuecomment-380728655) which might be relevant to you also?

**Comment by oehme** [comment]
Please see the [FAQ](https://github.com/eclipse/buildship/blob/master/docs/user/Faq.md#q-running-java-compilation-tasks-fails-with-could-not-find-toolsjar-how-can-i-fix-this).
