### ISSUE TITLE
Seems Buildship 2.2.1v20180125-1441 wont work with JDK 9.0.4 on Windows 10 STS 3.9.3 x64. Have ~.gradle/gradle.properties set.

### ISSUE THREAD

**Issue by mikepotter1024** [eclipse/buildship#687]
Followed the FAQ to set still get the BAU console error:
...
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 4.6
Java Home: C:\Program Files\Java\jre-9.0.4
JVM Arguments: None
Program Arguments: None
Build Scans Enabled: false
Offline Mode Enabled: false
Gradle Tasks: build

:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Cannot find System Java Compiler. Ensure that you have installed a JDK (not just a JRE) and configured your JAVA_HOME system variable to point to the according directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

# Images
*** There is a java.exe
![java exe -version](https://user-images.githubusercontent.com/38142311/38440501-df15b804-399e-11e8-9af2-ddb23742b1a4.jpg)
*** There is a ~.gradle/gradle.properties file
![gradle folder](https://user-images.githubusercontent.com/38142311/38440723-8de4d22a-399f-11e8-8c7b-95c3e8bdabac.jpg)
*** gradle.properties file has correct contents
![gradle properties content](https://user-images.githubusercontent.com/38142311/38440845-f5d6601a-399f-11e8-9e36-a7bd557b2407.jpg)
*** Is STS 3.9.3
![is sts 3 9 3](https://user-images.githubusercontent.com/38142311/38441063-b05a66a2-39a0-11e8-9871-c3a44af37e1e.jpg)
*** Buildship Version
![buildship ver](https://user-images.githubusercontent.com/38142311/38441147-fb7cc7ec-39a0-11e8-92df-2845d7c7f3a2.jpg)
*** Is JDK 9.0.4
![jdk 9 0 4](https://user-images.githubusercontent.com/38142311/38441278-76fe503e-39a1-11e8-8612-4b8973df8b33.jpg)
*** Have JAVA_HOME set
![even have java_home set](https://user-images.githubusercontent.com/38142311/38441562-662a680a-39a2-11e8-8979-8879a5af7e8a.jpg)
*** Is Windows 10 64bit
![is win 10 64bit](https://user-images.githubusercontent.com/38142311/38441602-8a1e1928-39a2-11e8-9a74-d67a1c5d42da.jpg)

**Comment by lukeu** [comment]
I don't recall the precise rules for how Buildship selects which JVM/JRE to run on, but I know it falls back to the version of Java that Eclipse is using - which looks like it's happened to you, due to:

> Java Home: C:\Program Files\Java\jre-9.0.4

One solution could be to get Eclipse itself to launch using the JDK instead of JRE. Edit the Eclipse.ini file and add (on 2 separate lines, between `--launcher.appendVmargs` and `-vmargs`):

    -vm
    C:/Program Files/Java/jdk-9.0.4/bin/server/jvm.dll

Another could be to tell buildship to set all your Gradle projects to use a specific JDK (named the same as what's configured in your Eclipse preferences). This might be done in the top-level `build.gradle` file, for example:

    allprojects {
        eclipse {
            jdt {
                javaRuntimeName = "jdk-9.0.4"
            }
        }
    }

There are other options, around setting a GRADLE_USER_HOME, etc too. What works best probably depends on the circumstances of your project/team.

**Comment by lukeu** [comment]
Also, IIRC, the message about JAVA_HOME might be misleading as that comes from Gradle, but I don't think Buildship makes use of it. (Might want to search around to confirm that mind you.)

**Comment by oehme** [comment]
Your setup should work, Gradle will use the java home specified in your `~/.gradle/gradle.properties`. Make sure you haven't overwritten it in the Gradle settings or run configuration settings. in Eclipse

**Comment by lukeu** [comment]
> Also the eclipse.jdt.javaRuntimeName has no influence on it, it just determines which runtime to use inside Eclipse.

Ah yes, sorry I was conflated this with my setup (which uses the Eclipse compiler) with this output. Clearly here Gradle is doing the compiling. Silly me. I've added a warning to my comment that it's bad advice.
