### ISSUE TITLE
'runtimeOnly' Dependencies not Deployed to Tomcat

### ISSUE THREAD

**Issue by markus-wa** [eclipse/buildship#691]
### Expected behaviour

`runtimeOnly` dependencies get deployed to `WEB-INF/lib` when using the Eclipse 'Servers' view (Tomcat 8.0).

### Actual behaviour

Any `runtimeOnly` dependencies are missing from `WEB-INF/lib` after deployment

```gradle
dependencies {
	// Ok
	compile project(':compile-lib')

	// Missing from WEB-INF/lib!
	runtimeOnly project(':runtime-lib')
}
```

### Reproduction / Example

See https://github.com/markus-wa/eclipse-buildship-dependency-deployment-bug for a minimal working example

### Notes

Java `runtime` dependencies inside projects that are listed as `compile` dependencies get deployed. (e.g. `a: compile project(':b')`; `b: runtime project(':c')` = ok)

`webapp/.settings/org.eclipse.wst.common.component` is missing  the `dependent-module` `runtime-lib` after importing the project into eclipse. (Bug in https://github.com/gradle/gradle `eclipse-wtp` plugin?)

After manually adding the `runtime-lib` as `dependent-module` only `runtime-lib.jar` is deployed. The dependencies of `runtime-lib` are still missing.

I suspect this is because the `webapp` project is supposed to know about them by itself as they are listed in the 'Project and External Dependencies' in Eclipse.

### Environment
Eclipse Neon.3
Buildship 2.2.1
Gradle 4.6
Win 10

**Comment by donat** [comment]
Currently the `eclipse-wtp` plugin doesn't include `runtimeOnly` by default in `libConfigurations`. You can fix that by adding `runtimClasspath` to `libConfigurations`:
```
eclipse {
    wtp {
        component {
        	libConfigurations += [ configurations.runtimeClasspath ]
        }
    }
}
```

Note, that it will also [include the dependencies from the `api`, `compile`, `implementation` and `runtimeOnly` scopes](https://docs.gradle.org/5.1.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) too. To overcome that, you can declare your own dependency scope and add that to `libConfigurations`.
```
configurations {
    webLib
}

dependencies {
    webLib project(':compile-lib')
}

eclipse {
    wtp {
        component {
        	libConfigurations += [ configurations.webLib ]
        }
    }
}
```
