### ISSUE TITLE
AutoSync Project Synchronization only looks at build.gradle file apply/includes are not watched

### ISSUE THREAD

**Issue by jclx** [eclipse/buildship#693]
Currently the build.gradle file is only watched in 
    private boolean hasBuildScriptFileChanged(IProject project, IResourceDelta[] deltas) {
            IPath buildScriptPath = model.getbuildScriptPath();
            Set<IPath> affectedResourcePaths  = collectAffectedResourcePaths(deltas);
            return affectedResourcePaths.contains(buildScriptPath);
But when a build.gradle has an apply 
apply from: "common.gradle"
Changes to common.gradle do not trigger synchronization.
Also changes to gradle.properties and settings.gradle file in Project directory should be watched if they exist.

**Comment by donat** [comment]
The auto-sync feature is intentionally simple. Implementing a complete solution would make Buildship much slower. In addition, an estimation (reading the raw file contents and matching on `apply` statements) would be limited and error-prone.
