### ISSUE TITLE
I'm not sure the EclipseProject component is working

### ISSUE THREAD

**Issue by lukeu** [eclipse/buildship#694]
When adding the following to a `build.gradle` in a given project...

    eclipse {
      classpath {
        println "CLASSPATH"
        file.whenMerged {
          println "CLASSPATH-MERGED"
        }
      }
      project {
        resourceFilter { println 'RF' }
        file {
          withXml {
            println "XML"
          }
          whenMerged {
            println "MERGED"
          }
        }
      }
    }

and then do **[Gradle > Refresh Gradle Project]** then I see 3 things printed, but not "XML" or "MERGED"

Bug? (or does the `.project` file updating happen at some other time?)

The real problem of course is that nothing else declared inside `eclipse.project.file` seems to works either.

Tested with:
 * Gradle 4.6
 * (Eclipse 4.8M5 + Buildship 2.2.1) and (Eclipse 4.7.3a + recent 2.2.2 snapshot)
 * Java 8 (u162) and 9.0.4

**Comment by lukeu** [comment]
Ooooh, so these are only supported by `gradle eclipse` on the command-line? Right, I didn't realise there was a distinction.

**Comment by SchwingSK** [comment]
having this would help greatly in keeping the same behaviour between the 'eclipse' task & Buildship.

**Comment by donat** [comment]
Thank you @lukeu for looking into the implementation of @oehme's proposal!
The implementation should be done inside Gradle entirely, so IMHO we can close this issue. This doesn't mean that I don't want the implementation to happen, I just want to keep the project's issue tracking up-to-date.

**Comment by lukeu** [comment]
I figured out most of my questions in the end. A first cut at the code is referenced above - comments & suggestions welcome!
