### ISSUE TITLE
"Gradle Task" view never updates based on the open projects

### ISSUE THREAD

**Issue by aram535** [eclipse/buildship#698]
When you have multiple gradle projects and switch between them, the "Gradle Tasks" view never updates to show/hide the new projects. 

Scenario: 

Open Eclipse with ProjectA (already open).   Gradle Task View: ProjectA 
ProjectA->Close, ProjectB->Open Project.  Gradle Task View: ProjectA 
ProjectB->Gradle->Refresh... Gradle Task View: ProjectA 

Eclipse IDE for Java Developers

Windows 10
Oracle Java 8
Version: Oxygen.3a Release (4.7.3a), Build id: 20180405-1200
Buildship: Eclipse Plug-ins for Gradle	2.2.1.v20180125-1441

Projects with multiple Gradle versions (mostly 4.5+)

**Comment by donat** [comment]
Currently, you have to execute the `Refresh Gradle Project` action manually from the view's toolbar. There's a [PR](https://github.com/eclipse/buildship/pull/677) for that, we're just waiting for the contributor to reopen it with a clean commit history.

**Comment by donat** [comment]
Duplicate of #385
