### ISSUE TITLE
It will lock the workbench resources when using GradleLaunchConfiguration to run task with "--continuous"

### ISSUE THREAD

**Issue by jtydhr88** [eclipse/buildship#703]
hey Guys,
When I am using **GradleRunConfigurationAttributes** and **GradleLaunchConfigurationManager** to get an ILaunchConfiguration that running some gradle tasks with "--continuous", it will lock the workbench/projects resources. it wouldn't happen on 2.2.1 but happening the latest 3.x.
Is that an issue? or am I using wrong way to run continuous tasks? Any Suggests?
Thanks a lot!

**Comment by jtydhr88** [comment]
Thanks so much on it

**Comment by simonjhy** [comment]
maybe the DefaultToolingApiOperationManager should not call "ResourcesPlugin.getWorkspace().run(new WorkspaceRunnableAdapter(runnable, tokenSource), efficientMonitor)" to run a WorkspaceRunnable thread. This will be conflict with the SynchronizationJob, all of them will be lock whole  eclipse workspace.  When we run two tasks, one of them is a long duration task, then the other task will be hold on until long duration task finished. Maybe we can just use "new WorkspaceRunnableAdapter(runnable, tokenSource).run(efficientMonitor);"
