### ISSUE TITLE
Please add more API examples

### ISSUE THREAD

**Issue by UdoW** [eclipse/buildship#711]
Please add more API examples to your already started page: https://github.com/eclipse/buildship/blob/master/docs/development/ApiExamples.md

Or where can I get information on how to extend  Buildship from with-in my own plug-ins and what is possible to extend?

**Comment by donat** [comment]
There's no other public API to document at the moment.
There's, however, an ongoing effort to collect requirements for a stable API. We'll soon implement a stable API based on the discussion [here](https://github.com/eclipse/buildship/issues/676).

Can you please elaborate what you are trying to achieve? Just add a comment there, and we'll see what can we do.
