### ISSUE TITLE
build folder in Eclipse not refreshed after a build

### ISSUE THREAD

**Issue by vogella** [eclipse/buildship#713]
As I generate documentation with Gradle I make the build folder visible to open the generated html.

![javamag-gradle30](https://user-images.githubusercontent.com/139910/42292945-9709d102-7fd6-11e8-8a8a-94dcb0f32d56.png)

I noticed that after a build the build folder (or the project) is not refreshed, I need to refresh manually.

To reproduce:
````
plugins {
    id 'org.asciidoctor.convert' version '1.5.6'
}

apply plugin: 'java'
apply plugin: 'org.asciidoctor.convert'

version = '1.0.0-SNAPSHOT'

asciidoctorj {
    version = '1.5.6'
}

asciidoctor {
    sourceDir = file('.')
  	sources {
    	include '*.adoc'
  	}
    backends = ['html']
}
````
Create a file test.adoc with the following content:

````
Hello
````
And run the "asciidoctor" tasks -> build folder is not shown unless you manually refresh (via F5).

**Comment by vogella** [comment]
FYI - Next german Java Magazin Eclipse article will point to this issue, it covers how to create documentation with Eclipse, Asciidoctor and Gradle.

**Comment by donat** [comment]
The task execution action doesn't refresh any project resources. I think we should approach this in a more generic way: all project resources should be refreshed after task execution. For that, we already have https://github.com/eclipse/buildship/issues/339 open.

**Comment by donat** [comment]
Superseded by #339.
