### ISSUE TITLE
Add initial API to import new project into the workspace

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#751]

**Comment by mickaelistria** [comment]
There is now this API which BuildShip could contribute to: https://wiki.eclipse.org/E4/UI/Smart_Import .
It's the one used by File > Import Projects from Filesystem... to detect the possible import scenario for a given folder. Basically BuildShip could jump in whenever there is a build.gradle and suggest import of the modules that have a build.gradle and even run the typical operations to compute the list of modules.

**Comment by donat** [comment]
@mickaelistria Thanks for notification. Frankly, I didn't think about smart import when I sketched the API outline. Nonetheless, I've read through [the related discussion](https://bugs.eclipse.org/bugs/show_bug.cgi?id=469636). It seems to me that the original design problems @oehme mentioned on that thread are still valid. The new synchronization APIs don't actually do more than what we had already in the internal packages. If you have more insights or updates how should we approach the implementation of the Gradle project configurator, let me know.

**Comment by mickaelistria** [comment]
To be honest, I was never convinced by @oehme or whoever that it was fully impossible. The Smart Import API allows to let Gradle compute the actual modules to import, even if they don't have a build.gradle file directly.
And even if some important limitations are found, it'd still be highly profitable to at least implement one basic approach (looking only at build.gradle files) and then upon completion to open a pop-up suggesting additional analysis if it seems worth it, possibly redirecting to the complete Gradle import wizard.

**Comment by donat** [comment]
I agree, it would be nice if we could enable the importer for the basic Gradle use-cases. 

How can we execute something at the end of the project configuration phase, though? Judging from the API there's no ordering between the configurators. What happens when there are multiple configurators trying to open import dialogs?

**Comment by mickaelistria** [comment]
> How can we execute something at the end of the project configuration phase, though?

There is no API that does that, but IIRC, you can create a Job that first waits for `Job.join(SmartImportJob.class)` to wait for completion of the import job and then run whatever you want.

> Judging from the API there's no ordering between the configurators. 

There is one, but the API doesn't show it, so it's indeed better to not rely on it at the moment.

> What happens when there are multiple configurators trying to open import dialogs?

At the moment, only the Maven configurator would show a dialog in case of missing lifecycle listeners. I guess in case 2 configurators open a dialog, both dialog would pop-up simultaneously or so. But so far, it doesn't seem to be a very probably case.
Note that if you mimic some parts of the MavenConfigurator for instance, it would prevent both Maven and Gradle configurators to try configuring the same folder as one would take priority (kind of randomly, but again, in the vast majority of cases, it's not likely to happen).

**Comment by donat** [comment]
Waiting for the `Job.join(SmartImportJob.class)` could be a start, thanks for the tip.
