### ISSUE TITLE
Buildship fails to import project as it expects working directory to be project root

### ISSUE THREAD

**Issue by a1dutch** [eclipse/buildship#773]
Hi

I'm unable to import the [springfox](https://github.com/springfox/springfox) project into eclipse photon with buildship  2.2.1.v20180125-1441, this project applies a plugin from the buildSrc that is using git to parse a version number and expects the working directory to be the project directory.

The project builds fine from the terminal and imports into intellij correctly.

is it possible that buildship can set the working directory on import to the project directory?

**Comment by donat** [comment]
The problem is in the project's build script. @a1dutch your PR ⬆️is the proper way to fix it.
