### ISSUE TITLE
Refreshing Gradle Project causes breaks JRE configuration

### ISSUE THREAD

**Issue by nlisker** [eclipse/buildship#778]
Creating a new Gradle project or using Refresh Gradle Project causes the JRE system library configuration to break. The error message displayed in the `Problems` view  is:

> Unbound classpath container: 'JRE System Library [JavaSE-11]' in project 'myProject'.

The `Enable project specific settings` checkbox under `Java Compiler` also checks itself when this happens.

It does not matter what the previous JRE setting was (I tested 10 and 11 and it reverted to the broken 11 both times, although 11 is not even the workspace default).

![image](https://user-images.githubusercontent.com/37422899/46355096-cba09f80-c668-11e8-89f5-82b2f730baf8.png)

Eclipse Photon (4.8) Build id: I20180611-0500
Buildship 3.0.0.v20180925-2319-s (I think it happened on 2.2 as well)
Gradle 4.8 or 4.10.2
Win 10

I found one [question](https://stackoverflow.com/questions/52538556/refresh-gradle-project-in-eclipse-rewrites-project-settings) on SO about this as well.

**Comment by oehme** [comment]
The setting is derived from your project's target compatibility, so if you have a Java 11 project, it'll use a Java 11 execution environment. I guess you haven't specified your target compatiblity, so it just uses whatever VM Gradle runs on as the default.

**Comment by nlisker** [comment]
`build.gradle` contains the lines

```
sourceCompatibility = 11
targetCompatibility = 11
```

**Comment by oehme** [comment]
So why do you expect anything else than a Java 11 execution environment?

**Comment by nlisker** [comment]
I'm expecting to Java 11, but I'm not getting it. I'm getting an error "Unbound classpath container", and as you can see in the screenshot, no JRE selected. I am expecting that if 11 is selected, then that it will continue to be selected after a refresh, but it's not.

**Comment by oehme** [comment]
Can you please have a look at your "Java Execution Environments" tab in the Eclipse preferences? Maybe they changed the naming pattern of the environment for Java 11 (they changed them a few times before)

**Comment by oehme** [comment]
You're not supposed to specify one directly, Gradle specifies the execution environment and Eclipse maps that to an concrete JRE. What entries do you have under "Execution Environments"? Maybe your Eclipse version simply doesn't support Java 11 yet.

**Comment by nlisker** [comment]
This is for Eclipse Photon (4.8) Build id: I20180611-0500:

![image](https://user-images.githubusercontent.com/37422899/46362901-27275900-c67a-11e8-94c6-d2b5b16afb11.png)

This is for Eclipse 2018-09 (4.9) Build id: I20180906-0745:

![image](https://user-images.githubusercontent.com/37422899/46362968-563dca80-c67a-11e8-97df-fd67a0bb578c.png)

Eclipse states they have added Execution Environment for JavaSE-11: https://bugs.eclipse.org/bugs/show_bug.cgi?id=535986

If this is a problem with Eclipse I'll gladly take it up with them, I just didn't know where the problem originated.

It is possible to map Execution Environment JavaSE-10 to a JRE11 (Eclipse will give a warning). If I specify
`sourceCompatibility = 11` and `targetCompatibility = 10` will it be a legitimate configuration?

**Comment by oehme** [comment]
Yep looks like Eclipse doesn't support 11 yet. You can't have source>target, so you'll have to stick with 10 until Eclipse is ready.

**Comment by nlisker** [comment]
Thanks, the patch for Java 11 for Eclipse added Execution Environment JavaSE-11 and the problem is solved.

**Comment by odys-z** [comment]
@nlisker 
Hi, I have exactly the same problem. And I don't want to change project properties each time I refreshed gradle project.
I don't catch what you mean by "patch". How exactly you fixed the problem?
My eclipse version is 
Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200
OS: Linux, v.4.15.0-136-generic, x86_64 / gtk 3.18.9, WebKit 2.20.5

**Comment by nlisker** [comment]
@odys-z Your eclipse is *very* old. Use the latest one.

**Comment by odys-z** [comment]
Got it!
