### ISSUE TITLE
Gradle dependency not added to the Eclipse launch classpath

### ISSUE THREAD

**Issue by Horcrux7** [eclipse/buildship#781]
Since the update of buildship 2.2.2 on some launch configuration the dependencies of Gradle is not added to the classpath. The dependencies are added to the "Project and External Dependencies" that the project compile correctly.

The symptom is that the "-classpath" parameter of the starting Java VM contains only project directories and direct added jar files. All jar files into the Gradle cache are missing.

The problem occur not on all launcher. Only on the very complex launcher.

For one launcher I have resolve it by deleting the launcher and recreating. But this not work for a different project.

I use Eclipse Version: 2018-09 (4.9.0)
In the log I can not see any exception at this time.

**Comment by donat** [comment]
We added only one change to the runtime classpath computation: https://github.com/eclipse/buildship/pull/692. Can you please check if it's relevant?
Otherwise, I'd need a sample project to investigate your problem further.

**Comment by Horcrux7** [comment]
After investigating many hours to make my workspace working again it sounds that not the buildship update is the cause. I have uninstall the buildship plugin 2.2.2 and have install 2.2.1 and then 2.2.0. It has not solve the problem. But I am not sure if such uninstall is enough.

Then I have reset the workspace, delete .metadata and all .gradle directories. It has not solve the problem.

Then I have switch back to Eclipse 4.8 with the same workspace and the problem occur continue.

But I have see that the classpath definition of the launcher look curios. All of the dependencies was added to the Bootstrab Entries. I have reset the classpath to default and it work now.

Before I had delete the launcher in version 4.9 of Eclipse multiple time that it should already be default.

That I think the problem starts with Eclipse 4.9. But the problem occur first if you modify an launcher. An existing launcher or copied launcher will work and this is the cause because I have not see the context to an update of Eclipse for some days. Buildship 2.2.2 was the last update before the problem.

That the problem occur only with my complex launcher can be an effect of frequently modify this launcher.

Because I have delete my workspace settings and delete Eclipse 4.9 I have not enough to verify this theory now.

**Comment by Horcrux7** [comment]
After investigating more time because the problem occur repeated it look like the cause are the additional attributes "gradle_scope"  and "gradle_used_by_scope".

Because we use src folder for different scopes but Gradle use only the last scope for the .classpath file:

```
sourceSets {
    main {
        java {
            srcDirs = ['src']
            exclude '...'
            exclude '...'
            exclude '...'
        }
    }
    javascriptCompress {
        resources {
            srcDir 'src'
            include '**/*.js'
        }
    }
}

```
We solve it with an additional call to entry.getEntryAttributes().clear() in the eclipse merge rule :

```
apply plugin: 'eclipse'
eclipse {
    project {
        linkedResources = []
    }
    classpath {
    	defaultOutputDir = file("bin")
        file {
            whenMerged { classpath ->
                classpath.entries.removeAll { entry ->
                    if ( entry.kind == 'src' ) {
                        entry.includes = []
                        entry.excludes = []
                        entry.getEntryAttributes().clear()
                    }
                    if ( entry.hasProperty('output') ) {
                        entry.output = null // use the default
                    }
                    false
                }
            }
        }
    }
}

```
