### ISSUE TITLE
Performance issue when importing multi module project into eclipse 

### ISSUE THREAD

**Issue by moley** [eclipse/buildship#794]
Hi, 

We want to import our gradle multimodule projects via "Import->Existing Gradle Project...".

Having a real world project (which I cannot upload), which needs about 4 minutes to be imported into eclipse, while a complete clean build (gradle clean testClasses) on commandline needs about 1 minute and importing it into idea lasts about 10 seconds, we cannot migrate to use gradle until this bug is fixed.

I have extracted an example project https://github.com/moley/buildshipImportExample, were you can even notice this bug.

Demoproject
* Building on commandline after dependencies are all downloaded: 6 s
* Importing into IntelliJ: 10 s
* Importing into Eclipse: 36 s (11 s Importing + 26 s Synchronizing)

Real-World project
* Building on commandline: 58 s
* Importing into IntelliJ: 28 s
* Importing into Eclipe:	230 s

I'd expect the build to need the same time both in Idea and in Eclipse.

**Comment by moley** [comment]
Outputs from my profiler, hope they help....

<img width="1457" alt="bildschirmfoto 2018-11-06 um 15 31 59" src="https://user-images.githubusercontent.com/3918367/48070953-511fee00-e1d9-11e8-9ca7-e6c4ce3324ed.png">

**Comment by moley** [comment]
This occurs once the project is imported AND - and that's the bigger pain - everytime the workspace is reopened

**Comment by moley** [comment]
You're welcome. 
Sorry for the dep resolution problem, I have fixed it, you can pull.
If having further problems or a fix which I should test, please call.....

Cheers
Markus

**Comment by donat** [comment]
Recently I've fixed a performance regression that caused the synchronization to execute multiple times per build. I've tested the latest 3.0 snapshot and importing your sample project seems much better now. Can you please give it a try?

**Comment by moley** [comment]
Hi donat, 
thank you, I will surely take a look. Currently I am ill, so I think next week I could manage. I will give feedback asap.

**Comment by donat** [comment]
No worries and get well soon!

**Comment by moley** [comment]
Hi Donat, 
I retested performance with building a snapshot from branch "release-3.0". I think performance improved a little bit, so it was a step in the right direction, but still both import of projects and rebuilding taskmodel after restarting the ide are very slow compared to idea. So would be nice if you could check if with my first insights you can improve it a little bit more. Thanks a lot

**Comment by donat** [comment]
Once again, we've found another performance regression in Buildship 3.0. Can you please do another round with the latest snapshot? I tried to import your sample project, and it finished almost instantaneously.

**Comment by donat** [comment]
Closing just to keep the board clean. Please re-open it if we missed something.

**Comment by moley** [comment]
Hi again, Donat, 

as performance is better but not optimal for us, I still did some profiling, getting a similar result like in the picture I still attached to this bug. A hotspot is the DefaultSerializer in this case. Could you please grant me a short insight, what this does? I thought that at this point the output which is shown in the progress view is grabbed from daemon - is this correct? We have a lot of dependencies in our scenarios, so I think a lot of infos are grabbed. On commandline the performance is OK meanwhile - perhaps because I never determine all dependencies of all subprojects at one time - different to IDE here. Would be nice if you could give me some additional infos. 
Thanks
Markus

**Comment by oehme** [comment]
The event handling happens on a separate thread, so it's unlikely to be the problem unless it takes so long that it prevents the synchronization from finishing. Also I can see you used instrumentation, which greatly exaggerates small method calls. Please use sampling instead and send us the full JProfiler recording and we'll take a look.

**Comment by moley** [comment]
Hi Stefan, 
thank you for the fast answer. You're right, using sampling does have less influence on profiling in this case and it seems that buildship is fast enough. 
I have found another performance issue regarding to our own XText plugin, so I think I have to check these at first. If I find another thing, I will open a new bug, but looks good so far, 

Have I nice time
Markus
