### ISSUE TITLE
com.gradleware.tooling.model plugin is missing from 2018-12 M2 EPP

### ISSUE THREAD

**Issue by josephca** [eclipse/buildship#797]
Is this an intended removal? it affects update install for the missing dependency. 

e.g.
Missing requirement: Maven tools for Java EE headless tests (com.ibm.etools.maven.javaee.core.tests) requires 'osgi.bundle; com.gradleware.tooling.model 0.0.0' but it could not be found
        Cannot satisfy dependency:

**Comment by donat** [comment]
Yes, we intended to get rid of that library as it became obsolete and it added significant maintenance burden to the project.

**Comment by donat** [comment]
FYI We have migrated all useful classes to the `org.eclipse.buildship.core` plugin. Closing this issue now. Feel free to reopen it if we need to do something.
