### ISSUE TITLE
Gradle configurations and IDE configuration

### ISSUE THREAD

**Issue by bkeyser** [eclipse/buildship#803]
### Expected Behavior

The Eclipse IDE (and IntelliJ IDEA) should be properly configured when using configurations different than main or test.

### Current Behavior

The IDE is not configured to use Gradle configurations.

### Context

Combine several libraries that are generated and configure Eclipse to recognize those libraries.  The example simulates the set of generated and compiled files to create a library.  This library (and others) are aggregated into a singe library that used by other projects.

### Steps to Reproduce (for bugs)

1.  Clone the git repository at https://github.com/bkeyser/gradle-ide-configurations.git
2.  Compile aggregated-libs/person-lib/resources/src/entity/Person.java

```
$ cd aggregated-libs/person-lib/resources
$ javac -d classes src/entity/Person.java
```

3.  Build the project using Gradle from the command line

```
$ ./gradlew build
```

4.  Import the project in Eclipse
5.  The `entity.Person` class is not found by the dependent-lib project.

_NOTE:_  You may notice that the `person-lib` project only uses the base plugin.  This is intentional as the class files that comprise the library are generated and compiled by the same utility (clientgen).  If the `java` plugin is applied, then the result is similar.

### Your environment

 Eclipse 2018-09 and Buildship 2.2.2 were used in the development of the example (IntelliJ 2018.2 was also used and exhibited a similar problem to Eclipse).

**Comment by oehme** [comment]
The `dependent-lib` project depends on the `aggregatedLibs` configuration in the `aggregated-libs` project. This configuration exposes no transitive dependencies. So it is expected that Eclipse can't find those classes. Eclipse doesn't use the fat jar, it uses a project dependency.

If you want Eclipse to work, you'll have to let `dependent-lib` depend on the `libCollection` configuration instead. You can still use `aggregatedLibs` as a `compile` dependency for the command line build, but you'll have to adjust the `eclipse.classpath` configuration of `dependent-lib`  to also include `libCollection` to get the transitives.

**Comment by bkeyser** [comment]
Thanks @oehme for the explanation and I hope you don't mind if I ask another question to help clarify my understanding.  I thought that specifying the dependency of `dependent-lib` on `aggregatedLibs` would associate the result jar of the `aggregated-libs` project be a dependency of `dependent-lib` (as the jar task depends upon the `aggregatedLibs` configuration).  Your explanation suggests that I should form a dependency between the `dependent-lib` and the `libCollection` and that I believe the following block establishes that dependency?

```
eclipse {
    classpath {
        plusConfigurations += [ configurations.aggregatedLibs, configurations.libCollection ]
    }
}
```

I am confused as to why the dependencies are not established as defined?

Thanks for your guidance!

**Comment by oehme** [comment]
Yes, that's exactly why 👍
