### ISSUE TITLE
Support Test Jar for Composite Builds (Eclipse 2018-09)

### ISSUE THREAD

**Issue by maciejmiklas** [eclipse/buildship#808]
Composite Build does not suport transitive test dependencies, like this one:
`testCompile ('org.myapp:module-c:1.0.0-SNAPSHOT:tests') {changing = true }`
Class Path for Unit Test in Eclipse does not contains test jars at all, this is resulting in such exception:
```
java.lang.NoClassDefFoundError: org/junit/platform/engine/EngineExecutionListener
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:59)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.<init>(JUnit5TestLoader.java:34)
```
Not only classes from imported `module-c` are missing, but also other classes from test configuration:
```
    testCompile('org.junit.jupiter:junit-jupiter-api:5.3.1')
    testRuntime('org.junit.jupiter:junit-jupiter-engine:5.3.1')
```

I've created a simple project, in order to reproduce it: https://github.com/maciejmiklas/buildship-module-test

Project consist of 4 jars: `module-a,` .... , `module-d` and one war: `myapp`
![dd](https://user-images.githubusercontent.com/3326660/48784286-a7fdeb00-ece2-11e8-945f-e6cf40aad07f.jpg)

`myapp` is a simple Wicket Web Application, this one is working fine, so it's not relevant, but it's Gradle configuration enables Composite Builds:
```
rootProject.name = 'myapp'

includeBuild '../module-a'
includeBuild '../module-b'
includeBuild '../module-c'
includeBuild '../module-d'
```
This is the structure of Unit Tests:

![cd](https://user-images.githubusercontent.com/3326660/48784744-9537e600-ece3-11e8-8ddc-8207f6a35c55.jpg)

The Unit Test: `MyAppTest` from `myapp` can be executed as a Unit Test in Eclipse and it's working fine. Changes in any module are immediately reflected, so the classpath seams to be fine. `MyAppTest` references every module as `compile` and `testCompile`.

The problem starts when we try to execute test from modules: `ModCTest` or `ModBTest`. This is causing the exception mentioned above. 

The test would run fine, after removing `includeBuild` from `setting.gradle` and installing `module[a-d]` in local repo, maven plugin is active.

**Comment by donat** [comment]
Hi! I think the root of your problem is the a limitation of Gradle itself: composite builds don't support multiple publications automatically: https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work

You can resolve your issue by restructuring your projects a bit. Depending on test publication seems like a bad practice to me. I'd consider refactoring the shared test fixtures to a separate `module-test-fixtures` project.

**Comment by maciejmiklas** [comment]
Thank you!
