### ISSUE TITLE
Buildship should resolve local project dependencies

### ISSUE THREAD

**Issue by fr1zle** [eclipse/buildship#809]
Assuming you have projectA and projectB, both are build independently and are hosted in their on git repository.

A bug in projectB now also creates a bug in projectA. So I clone both projects into my eclipse workspace and import them as gradle projects.

projectA has a dependency on projectB with version 1.0.0-SNAPSHOT. The projectB in cloned the eclipse workspace has the version 1.0.0-SNAPSHOT as well.

Now, Buildship seems to create projectAs classpath using the locally installed projectB.jar and not the eclipse project. Forcing me to do a `gradle publishToMavenLocal` after every change in projectBs code. I also can't take advantage of the eclipse hot reloading in debug mode.

This differs from the behaviour of the m2e plugin where the described workflow is possibly. Is there any specific reason for this? What would be the proper way to handle this workflow?

I also noticed that m2e won't resolve workspace-local gradle projects. Is there a way to support this?

**Comment by fr1zle** [comment]
Okay, when projectA and projectB are both gradle projects, using Composite Builds seems to do the trick.

Is there anything i can do if projectA is a maven/m2e project?

**Comment by donat** [comment]
For testing purposes, you can hack the Gradle project classpath.  You can use the `eclipse.classpath.file.whenMerged {}` block to modify that. You'll find examples how to do that [here](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available).

Please note, that this is only a workaround in the IDE and it doesn't have an effect on the actual build.

**Comment by oehme** [comment]
Use a [composite build](https://docs.gradle.org/current/userguide/composite_builds.html).

**Comment by eric-creekside** [comment]
> For testing purposes, you can hack the Gradle project classpath. You can use the `eclipse.classpath.file.whenMerged {}` block to modify that. You'll find examples how to do that [here](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available).
> 
> Please note, that this is only a workaround in the IDE and it doesn't have an effect on the actual build.

I've read that announcement but it's not clear how to set up the project classpath to depend on another Eclipse project. Can you provide a complete example of using the `eclipse.classpath.file.whenMerged {}` block to do that?

As an aside, seeing as m2e has supported this with a simple UI checkbox, and it's a common development situation, is there a reason this hasn't been built into Buildship?
