### ISSUE TITLE
"Refresh Gradle Project" runs the dependencies of compileJava task?

### ISSUE THREAD

**Issue by dukeyin** [eclipse/buildship#817]
I have a Gradle 5.0 project using an annotation processor.  Because compilation fails if the generated source file is preexisting, I tried to setup my build script like this:

```
def srcgenMainJavaPath = "srcgen"
task emptySrcgen() {
	delete "${srcgenMainJavaPath}"
	file(new File(projectDir, '/' + "${srcgenMainJavaPath}")).mkdirs()
}

compileJava {
	dependsOn "emptySrcgen"
	doFirst {
		options.compilerArgs << "-s"
		options.compilerArgs << "${projectDir}/${srcgenMainJavaPath}"
	}
}
```
However, I am observing that anytime I refresh the Gradle Project in Eclipse, my generated source files get deleted.  Does "Refresh Gradle Project" intentionally execute the prerequisite tasks of `compileJava`, or is this a bug?

Note that if I setup my build script a little differently like this instead:
```
def srcgenMainJavaPath = "srcgen"
compileJava {
	doFirst {
		delete "${srcgenMainJavaPath}"
		file(new File(projectDir, '/' + "${srcgenMainJavaPath}")).mkdirs()

		options.compilerArgs << "-s"
		options.compilerArgs << "${projectDir}/${srcgenMainJavaPath}"
	}
}
```
then when I refresh my Gradle Project in Eclipse, my files do not get deleted.  (This is what I want.)

I am able to reproduce the above two scenarios always with these steps:
1. Create a new Gradle Project in Eclipse
2. Paste one of the two build script excerpts to the end of the default `build.gradle` file.
3. Create an empty file in the "srcgen" folder.
4. Refresh Gradle Project

I am using Eclipse 2018-09 which has org.eclipse.buildship.*_2.2.3.v20181113-2315-s jars.  I also tried Buildship 3.0.0.v20181205-1711-s which exhibits the same behavior.

**Comment by donat** [comment]
It seems that your configuration already works when launching the build from the command line. A similar - [Run tasks on synchronization](https://github.com/eclipse/buildship/issues/265) - is missing from Buildship at the moment, but we plan to implement it in the 3.2 release.

**Comment by oehme** [comment]
@donat I think you misunderstood the question. @dukeyin is not asking how to execute tasks.

@dukeyin Your task setup is broken, you are deleting files at configuration time. The task should be

```
task emptySrcgen() {
    doLast {
	delete "${srcgenMainJavaPath}"
	file(new File(projectDir, '/' + "${srcgenMainJavaPath}")).mkdirs()
    }
}
```

**Comment by dukeyin** [comment]
@oehme Thanks for the clarification.
