### ISSUE TITLE
We used GradleBuild.withConnection to start a continuous task will block other tasks 

### ISSUE THREAD

**Issue by simonjhy** [eclipse/buildship#818]
When we upgrade to latest builship3.0, we tried to use withConnection to execute a continuous task instead of using Builship launchConfigurtaionManager to execute a gradle task. But we found the new way will be block other tasks execution.

**Comment by donat** [comment]
@simonjhy This is the expected behavior. We designed `withConnection` for general usage which requires the workspace root lock. For your use-case, it might make sense to add a method overload which takes a scheduling rule as an argument.

**Comment by oehme** [comment]
@donat Why does general `withConnection` usage require the workspace root lock? It doesn't change anything in the workspace model.

**Comment by simonjhy** [comment]
Where I need to add? The implemetion DefaultBuildLauncher or DefaultGradleBuild?

**Comment by donat** [comment]
@simonjhy I meant that it might make sense for us to introduce a separate API method for your use-case. But in fact @oehme we don't even need that workspace root scheduling rule. I'll double-check why was it added on the first place.

**Comment by donat** [comment]
@simonjhy We've published a [3.0.1 milestone](http://download.eclipse.org/buildship/updates/e410/milestones/3.x) with the fix.

**Comment by simonjhy** [comment]
@donat Thanks.
