### ISSUE TITLE
How can I call "Refresh Gradle Project" from API?

### ISSUE THREAD

**Issue by UdoW** [eclipse/buildship#824]
How can I call "Refresh Gradle Project" from API?

All the refresh project classes are in internal packages and not accessible for my Eclipse plug-in.

How could I do it?

**Comment by donat** [comment]
Check the _Project Synchronization API_ section in the [Buildship 3.0 release announcement](https://discuss.gradle.org/t/buildship-3-0-is-now-available/29758).

**Comment by UdoW** [comment]
Ok, that works. Thanks.
