### ISSUE TITLE
Dependencies from external JAR's META-INF/MANIFEST.MF not propagated  to Eclipse?

### ISSUE THREAD

**Issue by Matschbirne86** [eclipse/buildship#834]
Hi there,

I got the following build.gradle file:

```
plugins {
    // Apply the groovy plugin to add support for Groovy
    id 'groovy'		
}


dependencies {

    compile project(':PwUtil')
		
    compile files(':oracle.odi-sdk-jse')
    compile ':oracle.jdbc/ojdbc8'

    testCompile 'org.spockframework:spock-core:1.1-groovy-2.4'
}

repositories {

	mavenCentral()
	
	flatDir {
		dirs "D:\\Programme\\Oracle\\Middleware\\Oracle_Home\\oracle_common\\modules", "D:\\Programme\\Oracle\\Middleware\\Oracle_Home\\odi\\sdk\\lib"
	}
}
```

My source uses some Classes from external JAR oracle.odi-sdk-jse.jar in "D:\Programme\Oracle\Middleware\Oracle_Home\odi\sdk\lib", which is a JAR containing only a META-INF/MANIFEST.MF which references lots of jars relative to the jar, e.g. (not complete):

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.2
Created-By: 1.8.0_40-ea-b19 (Oracle Corporation)
Extension-Name: oracle.odi-sdk
Specification-Version: 2.0
Implementation-Version: 12.2.1
Oracle-Version: 12.2.1
Class-Path: odi-core.jar odi-sap.jar odi-wls-template-gen.jar odihapp_
 common.jar odihapp_essbase.jar odihapp_planning.jar ogg_jmx_interface
 .jar oracle.odi-jaxrsri.jar XmlSchema-1.4.2.jar activation.jar aopall
 iance.jar bsf.jar commons-beanutils-1.7.0.jar commons-codec-1.3.jar c
 ommons-codec-1.9.jar commons-discovery-0.4.jar commons-lang-2.2.jar c
 ommons-logging-1.1.1.jar commons-logging-1.2.jar commons-net-3.3.jar
```

Now compiling on commandline works just fine, the build finished successfully. The problem arises when importing the gradle project to eclipse. The jar is correctly listed

![image](https://user-images.githubusercontent.com/46092588/50387578-09f5aa00-0700-11e9-954b-cc2dbf86df39.png)

but my code shows "Unable to resolve" errors in  Eclipse as the MANIFESTs entries do net get imported, it seems to me. To verify I'm not missing a point, I created a second testproject for which I included all required libraries using "Add external jar" in build path configuration. After adding the oracle.odi-sdk-jse.jar this way, eclipse list "Referenced Libraries" in the project view, which it does NOT for the gradle imported object:

![image](https://user-images.githubusercontent.com/46092588/50387541-2513ea00-06ff-11e9-9f95-71aa0963efc2.png)

With this configuration, everything works fine in Eclipse and my code compiles successfully. Thanks in advance for any hint.

Regards
Matschbirne86

**Comment by Matschbirne86** [comment]
Btw, in the Test-Project, the externally added JAR is listed like this in the builpath configuration:

![image](https://user-images.githubusercontent.com/46092588/50387618-f434b480-0700-11e9-813f-661f1bdea8f0.png)

**Comment by Matschbirne86** [comment]
Further findings:

When disabling automatic project synchronisation and adding the external JAR to the eclipse project (to clarify: I'm talking about the project that has the problems, not my second "Test" project) manually, it works in this order

![image](https://user-images.githubusercontent.com/46092588/50387911-f8180500-0707-11e9-9db0-3a29b1727908.png)

but not when placing the JAR below "Project and external Dependencies":

![image](https://user-images.githubusercontent.com/46092588/50387916-3c0b0a00-0708-11e9-8a24-68d9b8bffe1d.png)

Any suggestions?

**Comment by donat** [comment]
If I understand correctly your initial report, you're trying to make an OSGi project work in Eclipse.

The bad news is that Buildship doesn't provide any support for OSGi development out-of-the-box. My guess is that on the command line Gradle simply ignores the manifest entries as it doesn't know anything about it without a proper plugin. On the other hand in Eclipse you already have PDE installed which recognizes the OSGi headers and complains about the missing dependencies. 

You might be able to configure PDE and JDT to work correctly, but it's certainly not easy. Even Buildship doesn't use itself to import the source code into the workspace, even though it's built with Gradle on the command line.
