### ISSUE TITLE
New Gradle Project wizard w/ Gradle 5 locks up

### ISSUE THREAD

**Issue by eric-milles** [eclipse/buildship#839]
When I switch to Gradle 5+ and run the New Groovy Project wizard, the UI locks up.  I can see in the Console that Gradle is asking to choose Groovy or Kotlin for the build script DSL language.  There is no way to interact with this prompt.  (Buildship 3.0.0)

![image](https://user-images.githubusercontent.com/18193802/51075519-faf47e80-1651-11e9-9f74-f595b59f92d6.png)

**Comment by donat** [comment]
We saw this with Gradle 5.0 and implemented a fix Buildship 3.0. What version do you use?

**Comment by eric-milles** [comment]
3.0.0

**Comment by donat** [comment]
Can you please quickly check if you see the same behavior with 3.0.1?

**Comment by eric-milles** [comment]
I have Eclipse 2018-12 and when I check for updates, it states that none are available.  Should I be looking elsewhere for Buildship 3.0.1?

![image](https://user-images.githubusercontent.com/18193802/51121632-7f273d00-17dd-11e9-9e0a-f42830ac0eb0.png)

**Comment by donat** [comment]
The easiest is the Eclipse Marketplace. Otherwise, you can use the Buildship update sites: https://download.eclipse.org/buildship/updates/e410/releases/3.x

**Comment by eric-milles** [comment]
Buildship 3.0.1's New Project Wizard succeeds.
