### ISSUE TITLE
Third-party plugins based on Buildship and private API

### ISSUE THREAD

**Issue by jperedadnr** [eclipse/buildship#848]
Sorry if this question has already been asked/answered before.

We develop and maintain the [Gluon Eclipse plugin](https://marketplace.eclipse.org/content/gluon-plugin), which in part is based on Buildship, and we are in the process of refactoring it due to the recent release of the 3.0 version.

Our version based in Buildship 2.x is here: https://github.com/gluonhq/ide-plugins/tree/master/eclipse
and we used `org.eclipse.buildship.core` public classes in our wizard (see for instance [this](https://github.com/gluonhq/ide-plugins/blob/master/eclipse/com.gluonhq.eclipse.plugin/src/main/java/com/gluonhq/eclipse/plugin/wizard/GluonProjectWizard.java)).

But with Buildship 3.0, most of those classes are now part of the internal packages, and our first attempt to produce a plugin is [here](https://github.com/jperedadnr/ide-plugins/tree/BS3.0/eclipse), based on as few internal classes as possible.

We'd like to ask if it is wise to keep using the internal classes, and for any advice on a better approach. Is there public API that we are not aware of? Are internal classes going to be restricted?

Thank you in advance,
Jose Pereda

**Comment by donat** [comment]
Hi! It would be better if you could move away from using any internal APIs. Even though we don't plan to change any exports in the near future, this can change at any time. Plus, we but we do perform backward incompatible changes on the private APIs frequently, which might accidentally hurt you in the future. 

Nonetheless, in Buildship 3.0 we implemented APIs for:
- project import
- project synchronization
- task execution
- model queries
- custom configurators invoked during synchronization

Check out the contents of the `org.eclipse.buildship.core` package for the details. We added decent documentation for all API classes. The entry point is the `GradleCore` class. You probably want to start there. 

With the new APIs you should be able to remove any references to the Buildship internal classes in your codebase.
