### ISSUE TITLE
Gradle Refresh Switches Projects to Unbound JRE When Using Java 11

### ISSUE THREAD

**Issue by ghost** [eclipse/buildship#849]
If you run Eclipse with Java 11 and switch your projects to Java 11, Gradle Refresh switches the project's classpath to some unbound JRE. There is no way to use Gradle Refresh in Eclipse now.  I've checked every configurable setting and can't find anything specified that is wrong. This is in the current version of Eclipse and Buildship 3.0.0 and 3.0.1.  I am using project local gradle.properties files if that makes a difference.  Is there a way to force Buildship to use a specific JRE?  I set a custom JRE on the Eclipse Gradle preferences but that made no difference.

**Comment by ktaylor713** [comment]
I am using the current version of Eclipse with all updates applied. Problem remains. Not sure why this was closed. Also, this is on Windows, not Mac.

**Comment by ktaylor713** [comment]
Update: your suggestion does work as a work-around, but I suspect its a bug in Buildship or Eclipse.
Windows equivalent:
`eclipse {
	classpath {
		file {
			whenMerged {
				def jre = entries.find { it.path.contains 'org.eclipse.jdt.launching.JRE_CONTAINER' }
				jre.path = 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/jdk-11.0.2'
			}
		}
	}
}
`

**Comment by ktaylor713** [comment]
Sorry for the bad formatting. The Insert Code tool does not work in github!  How did you insert formatted code donat?

**Comment by donat** [comment]
re: formatting: you can use triple quotes(```) to paste snippets.

**Comment by donat** [comment]
re: unbound classpath: the problem ususually indicates that the JDK version which Buildship assigns to the project is not present in the Eclipse configuration. Can you please check that java 11 is present in the list of the installed JREs (Preferences > Java > Installed JREs)?

**Comment by rupweb2** [comment]
Per [this stackoverflow](https://stackoverflow.com/questions/73847867/cannot-see-java-19-jre-in-eclipse-ide-for-java-developers-2022-09) for JavaSE-19 you need to install [Java 19 support for Eclipse](https://marketplace.eclipse.org/content/java-19-support-eclipse-2022-09-425)

**Comment by AndreasBrieg** [comment]
I fixed the problem by explicitly specifying the `java home` in eclipse gradle preferences to point to a jvm of the correct java version.
