### ISSUE TITLE
Buildship does not recreate .project (and perhaps .classpath) on import

### ISSUE THREAD

**Issue by moley** [eclipse/buildship#851]
Hi, 

if I have a project, which is imported via "Import Existing Gradle Project" in my eclipse workspace. I then remove it, change the projectname, which is used for eclipse (project.eclipse.project.name) and import it again, the old projectname is not overwritten in .project file. 
It would be more consistent to overwrite these files anytime I import the project into eclipse again.

**Comment by donat** [comment]
I don't see this behavior. If I re-import an existing project the `.project` file always reflects the build configuration.

**Comment by donat** [comment]
Feel free to reopen this ticket if you have some specific I should consider in the investigation.
