### ISSUE TITLE
2.2 requires Java 8?

### ISSUE THREAD

**Issue by skehlet** [eclipse/buildship#856]
According to [the install docs](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md) Buildship 2.2 should only require Java 7, however when I download it and examine the included .class files I see they were built for Java 8. I checked both the files obtained through the Eclipse Marketplace and the [eclipse manual download site](https://download.eclipse.org/buildship/updates/e46/releases/2.x/2.0.1.v20170302-1039/plugins/?d). Even the oldest builds of buildship I could find ([1.0.17](https://download.eclipse.org/buildship/updates/e46/releases/1.0/1.0.17.v20160713-1853/plugins/?d)) were built for Java 8:

    $ pwd
    /Users/skehlet/Downloads/buildship-1.0.17
    $ file org/eclipse/buildship/core/AggregateException.class
    org/eclipse/buildship/core/AggregateException.class: compiled Java class data, version 52.0 (Java 1.8)

I'm on a project working on moving from 7 to 8 (Corretto), so in the meantime I want to as closely as possible replicate others' installations, meaning I need to stick with Java 7. Can I find Java 7 builds of buildship anywhere? Am I misinterpreting what I found? Any other suggestions? Thanks!

**Comment by donat** [comment]
It's been a while ago but we compiled the Buildship 2.x branch with Java 7 only if the target Eclipse version had the same or lower requirement for Java. You linked an update site for Eclipse 4.6 which requires Java 8. The following update site is compiled with Java 7: https://download.eclipse.org/buildship/updates/e42/releases/2.x/2.0.1.v20170302-1026
