### ISSUE TITLE
Importing large Multi-Project extremely slow

### ISSUE THREAD

**Issue by polaroidkidd** [eclipse/buildship#857]
Eclipse Version: 4.8.2
BuildShip Version: 3.x.x (can't see it now because it's currently running)

I am faced with  a ant -> gradle migration. I have so far managed to port the individual projects to gradle and created one root to hold them. However, importing these via the buildship plugin results in a long waiting time after the `Loading Gradle project models: Resolve files of:[PROJECT]:testClasspath` or `Loading Gradle project models: Resolve files of:[PROJECT]:runtimeClasspath`

It does this for every project and is rather slow.

the root build.gradle file looks like this

```

description = """Example Project"""

subprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'eclipse'



    idea {
        module {
            name = "${project.name}"
        }
    }
    eclipse {
        project.natures 'org.eclipse.buildship.core.gradleprojectnature'
        classpath {
            containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        }
    }

    tasks.withType(JavaCompile) {
      options.incremental = true // one flag, and things will get MUCH faster
    }
    
    test {
        testLogging {
            showStandardStreams = true

        }
    }
}
```

Now, the subprojects have a **lot** of inter-project dependencies. Any one sub-project depends on anywhere 10-30 other projects. I have decoupled them as much as possible and a topological sorting of project dependencies is possible (now). A complete `gradle assemble` (build doesn't work yet as the tests are currently failing) takes roughly four minutes within the terminal. This is the current `gradle.properties` file.

```
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx1024m
```

A typical sub-project's build-file looks like this:

FileName: `Project.build`

```


sourceSets {
  main {
      java {
          srcDirs = ['src/main/java']
      }
      resources {
          srcDirs = ['src/main/res']
      }
  }
  test {
      java {
          srcDirs = ['src/test/java']
      }
      resources {
          srcDirs = ['src/test/res']
      }
  }
}

task ProjectTests(type: Jar) {
    classifier = 'tests' 
    from sourceSets.test.output
}

configurations {
  testArtifacts
}

artifacts {
   testArtifacts ProjectTests
}

dependencies {

    implementation fileTree(dir: '../libs', include: ['**/*.jar', '**/*.zip'])
    testImplementation fileTree(dir: '../libs', include: ['**/*.jar', '**/*.zip'])
    
    testImplementation project(path: ':OtherComponent', configuration: 'mainArtifacts')
    implementation project(':other-sub-project')
}
```

I have also given the project specific build.gradle files other names to reflect their Project name. To do this I have this in the root `settings.gradle` file (the only file of its kind in the file-tree)

```
rootProject.children.each { project ->
    String fileBaseName = project.name.toLowerCase()
    project.buildFileName = "${fileBaseName}.gradle"
}
```

Generating the Eclipse Files using the `gradlew eclipse` command runs through in roughly 10 minutes. However, when I import the project via `Files > Import > General > Existing Project` the project does open quickly, however, the `Gradle Tasks` tab is unusable as Eclipse runs the commands mentioned in the beginning ( `Loading Gradle project models: Resolve files of:[PROJECT]:testClasspath` or `Loading Gradle project models: Resolve files of:[PROJECT]:runtimeClasspath`) for every project.

Any ideas to help resolve this would be greatly appreciated.

**Comment by oehme** [comment]
Have you tried giving the project a bit more RAM (e.g. `2g` instead of `1024m`)? Depending on the size of your dependency graph, that may be the limiting factor. Also make sure you're using a recent Gradle version, as newer versions generally have better performance characteristics.

If that doesn't help, you can use the [Gradle profiler](https://github.com/gradle/gradle-profiler) to measure your project's performance. Running `gradle-profiler --profile async-profiler --warmups 1 --iterations 1 eclipse` should give us some insight into where the time is spent.

**Comment by polaroidkidd** [comment]
@oehme thanks for getting back to me.

I've tried increasing the RAM for Gradle (using C:/Users/User/.gradle/gradle.properties) as well as as gradle.properties file within the root project directory (contents are identical as the global one would overwrite the settings of the local file). Unfortunately the result is the same in the sense that the import completes (the wizard closes and the workspace opens). However, right afterwards the Progress Tab lists two long-running tasks.
1. "Loading tasks of all Gradle Projects" (where it's resolving the files of various gradle classpath tasks)
2. "Syncronize Gradle with project model" (where the description is "Loading Gradle project models: Resolve files of :[COMPONENT]:runtimeClasspath"

The Gradle Tasks tab is available and does list all the tasks associated with the individual projects, but because the other two are long-running tasks I can't execute any of these.

Thank-you for pointing out the gradle-profiler. I hadn't heard about this one yet and it's currently running. Once the results are in I will share them here.

**Comment by polaroidkidd** [comment]
I've run the profiling with the jfr as I'm bound to use Win10 and unfortunately the async-profiler is only available on Linux & OSx. 

I haven't worked with the jfr before, is there anything specific I should be looking for?

Out of curiosity I also ran a 10 min. recording on the currently running Eclipse and its showing a rather high number of `Java Monitor Wait` but I'm not sure if this is normal.

Is there any preferred way I could share these JFRs?

**Comment by oehme** [comment]
If you install Perl, the Gradle profiler will output some nicely formatted graphs for you. You can also send me the recording.

**Comment by polaroidkidd** [comment]
> You can also send me the recording.

Do you have a specific email-address I could send it to or a preferred cloud-hoster?

**Comment by oehme** [comment]
Something like dropbox usually works fine.

**Comment by polaroidkidd** [comment]
We're behind a proxy so DropBox didn't work. Switched to WeTransfer. It's a zip containin the profile-out folder.

https://we.tl/t-11rQ4TkNfl

**Comment by polaroidkidd** [comment]
I have found the issue and it was entirely my fault. I added a file-tree classPath to every sub-module, making the classpath extremly long, which naturally took for ever to resolve. I'm running some more tests but if it runs through ok I will close this issue.

**Comment by oehme** [comment]
Looks like immense amounts of IO due to this line: 

`implementation fileTree(dir: '../libs', include: ['**/*.jar', '**/*.zip'])`.

For every single classpath Gradle has to walk this filetree again, as it could potentially change in between (though of course you know it never will). For this to become such a problem that folder must be quite large or your file system pretty slow.

A simple workaround would be to compute it once and cache the collection of files for further use. Something like this:

```
def cachedLibs
ext.libs = {
   if (!cachedLibs) {
     cachedLibs = fileTree(dir: '../libs', include: ['**/*.jar', '**/*.zip']).files
  }
  cachedLibs
}
```

Also note that putting stuff on both `implementation` and `testImplementation` is redundant, as the latter extends from the former.

**Comment by polaroidkidd** [comment]
you're a legend! Thank you so much for looking into this and helping out! Fault was entirely my own and I apologize for, well, being a tad rude in the other comment that you (rightfully) locked.

Again, thank you very much and have a nice weekend!

**Comment by oehme** [comment]
You're welcome, glad we could figure it out. Just for my curiosity: How long does it take now?

**Comment by polaroidkidd** [comment]
hmm.. it's not finding the dependencies in the sub-projects. Do I declare the task in the root build.gradle file outside the subprojects closure or inside it?

**Comment by oehme** [comment]
Outside it. I adjusted the example above, it was using the wrong path.

**Comment by polaroidkidd** [comment]
odd. 

its returning `> Could not find method libsDir() for arguments [] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.`

I have it in the root build.gradle file as in the example.

In the component.gradle files I placed it inside the dependencies closure as such 

```
dependencies {
    implementation libsDir()
    ...
}
```

**Comment by oehme** [comment]
Sorry, should have chosen any other name, as `libsDir` is an already existing method on `DependencyHandler` 😆

**Comment by polaroidkidd** [comment]
That was definitely it! Running `gradle eclipse` from the terminal is now blazing fast (couple of seconds at most).

However, when I use the buildship `import existing gradle project` from within Eclipse and the import wizard finishes its tasks eclipse seems to be stuck in an endless loop of `Synchronize Gradle projects with workspace`

it does complete the task but seems to generate a new one every time one is finished. This blocks any execution of gradle tasks from the gradle tool window. 

![image](https://user-images.githubusercontent.com/11783457/53792310-a5d73980-3f2b-11e9-80f6-ef93ade6b7a1.png)

**Comment by oehme** [comment]
That's definitely a bug. Can you reproduce this with a small example that has configuration similar to your real project?

**Comment by polaroidkidd** [comment]
I could not recreate the issue with a smaller project. I then found #840 and updated buildship to version 3.0.1 which fixed the issue for me..

Thank you again for your help and input!

**Comment by oehme** [comment]
Glad I could help :)
