### ISSUE TITLE
Enable tasks from included builds to be executed as if they were not part of the composite

### ISSUE THREAD

**Issue by andreabisiach** [eclipse/buildship#860]
This is related to #511 but i have chosen to create a new issue since the discussion in that issue is unclear and it mentions also multi-projects build.
The problem is related to COMPOSITE BUILDS

Problem:
All tasks of included builds are disabled as long as the associated eclipse project is open.
Closing the project of the included build enables the task but it does not make much sense

Expected behaviour
All tasks in all projects (composite build or included build) are enabled as long as the related eclipse project is open.
Additionally in IntelliJ tasks in included builds work  fine

How to reproduce:

1) Clone gradle

git clone `https://github.com/gradle/gradle.git`

2) Import sample project in Eclipse
gradle/subprojects/docs/src/samples/compositeBuilds/basic/groovy/composite

![image](https://user-images.githubusercontent.com/18190420/54202574-a2feba80-44d0-11e9-915e-57ebdf2ff138.png)

![image](https://user-images.githubusercontent.com/18190420/54202674-db05fd80-44d0-11e9-9673-e36f37381797.png)

3) Notice that ALL tasks in included builds are disabled (i.e. my-app) Only tasks in the composite build are available (adhoc)
![image](https://user-images.githubusercontent.com/18190420/54202793-156f9a80-44d1-11e9-827c-ea7902fc85a9.png)

4) Close the project my-app and refresh gradle tasks
![image](https://user-images.githubusercontent.com/18190420/54202905-5c5d9000-44d1-11e9-95f1-0e3742b3276b.png)

5) Now tasks in the my-project included build are enabled
![image](https://user-images.githubusercontent.com/18190420/54202949-71d2ba00-44d1-11e9-8cc8-ac6b1541e520.png)

**Comment by donat** [comment]
The disablement is needed there due to a limitation in Gradle itself: there's no way to address project tasks within a composite. For example you can't do this:

    $ cd gradle/subprojects/docs/src/samples/compositeBuilds/basic/groovy/composite
    gradle :my-app:run

Buildship disables the tasks for the same reason. We could work around it by launching the task in the project directory, but that woudn't be correct because then the composite build would be ignored. 

Nonetheless, enabling the tasks when the project is closed is a bug.

**Comment by andreasbisiach** [comment]
> The disablement is needed there due to a limitation in Gradle itself: there's no way to address project tasks within a composite. For example you can do this:
> 
> ```
> $ cd gradle/subprojects/docs/src/samples/compositeBuilds/basic/groovy/composite
> gradle run
> ```
> But not this:
> 
> ```
> $ cd gradle/subprojects/docs/src/samples/compositeBuilds/basic/groovy/composite
> gradle :my-app:run
> ```
> Buildship disables the tasks for the same reason. We could work around it by launching the task in the project directory, but that wouldn't be correct because then the composite build would be ignored.

But that is exactly what is needed in my opinion (and what IntelliJ does)
The task 'run' in the included build 'my-app' should be enabled and when executed it should do basically the following

$ cd gradle/subprojects/docs/src/samples/compositeBuilds/basic/groovy/composite/my-app
gradle run

The reason is that an included build, it is a completely encapsulated build that has no knowledge of the composite build.
So running the task 'run' in the included build is perfectly legal no matter in which composite (and how many) build it may be included.

For the same reason, tasks of included builds are not made automatically available in the composite build (and the included builds are not nested under the composite build).
To be able to run a task from the composite build that depend on included builds, I need to actively specify it in the composite build

At least this is what I understand from the documentation.
https://docs.gradle.org/current/userguide/composite_builds.html#included_build_task_dependencies

> 
> The workaround is to use the tasks under the composite root.
> 
> Nonetheless, enabling the tasks when the project is closed is a bug.
Yes, I guessed that it was a bug

**Comment by donat** [comment]
If you work around the composite declaration then all the dependency substitutions will not there and it would just confuse a lot of people. The limitation in Gradle is, in fact, an unfinished business. We planned to implement addressing tasks in the composite but we haven't prioritized it. The disabled tasks are a representation of that.

Nonetheless, I'm not completely against enabling the tasks, but we need a clear indication that they'll behave differently. An extra entry in the context menu (`Run without composite`) a different image in the tree and/or a dialog notifying the user to the new behavior. I don't have time for this ATM but contributions are welcome.

**Comment by donat** [comment]
BTW, I've checked IDEA and it is confusing what it does. I think we should do better.

**Comment by dperrocco** [comment]
Hey there, we're finding a similar issue, but with a multi-project build.

Included tasks are rightly greyed out, but we want to be able to run a dependency's tasks in its own folder, as its own root. We can do that by importing the dependency as a gradle project again, which seems to change what buildship considers to be root projects, but this will cascade into other dependencies, and remove some other dependencies' ability to run tasks as if they were root projects.

So a +1 to this, but could you consider multi-project builds to be covered by this issue, too?

Thanks. 😄

**Comment by dperrocco** [comment]
Actually, I want to take a stab at this. I followed the development setup guide, but ran into some issues. Is there a good place to ask questions relating to the development of Buildship?

**Comment by donat** [comment]
@dperrocco! You ask a question on the [Gradle forum](https://discuss.gradle.org/c/help-discuss/buildship). Chances are, I'll be the one who responds :)

**Comment by dperrocco** [comment]
To confirm what the requirements for this would be, it would basically be:

For Composite Builds AND for Multi-Project Builds:
- Included project tasks enabled and visible with a different icon from normal
- Included project tasks are executed from their projects' folders, as if they were the root project
- Some log output to reflect that they're being executed as if they were the root project

Is that correct?

**Comment by dperrocco** [comment]
I suppose Multi Project builds already have this kind of feature, when the task filter allows project tasks, not just task selectors...

**Comment by donat** [comment]
@dperrocco Comments below.

> To confirm what the requirements for this would be, it would basically be:
> 
> For Composite Builds AND for Multi-Project Builds:

A minor comment: I don't think we need to change anything for multi-project builds.

> - Included project tasks enabled and visible with a different icon from normal

That make sense, but don't think too much about it. We can provide a new icon if needed.

> - Included project tasks are executed from their projects' folders, as if they were the root project

The project tasks use the root project as a working directory. In case of the composite builds, we should fall back to the root of the included builds.

> - Some log output to reflect that they're being executed as if they were the root project

Absolutely. You'd need to add a new property on `RunConfiguration` that would be printed to the console in `RunGradleBuildLaunchRequestJob#writeExtraConfigInfo`

**Comment by dperrocco** [comment]
Okay, got it. At the moment I'm just trying to work out what is different in ProjectNodes and the various TaskNodes, so that the Tasks View can detect and show the difference.

**Comment by donat** [comment]
@dperrocco Any updates? Let me know if I can help with anything.

**Comment by dperrocco** [comment]
I have no idea when I'll have this legal issue at my company sorted out. It's safe to say that if there's someone else who can take over, that'd be much better/faster for you guys.

**Comment by donat** [comment]
We won't do this as the latest version already enabled task execution in included builds.
