### ISSUE TITLE
Use Import-Package instead of Require-Bundle for SLF4J 

### ISSUE THREAD

**Issue by mfriedemann** [eclipse/buildship#865]
Hey,

buildship/gradle, apparently part of Eclipse Simultaneous Releases (2018-12 as of now, maybe others) reports dependency on one specific (and ancient) version of slf4j (1.7.2, as supplied with eclipse). This can result in issues with modifications/updates to logging configurations.

To remedy, please consider dropping ```Require-Bundle: org.slf4j.api;bundle-version="1.7.2"``` from buildship.core and gradle.toolingapi and import the necessary packages instead, preferably with a less strict version range (e.g. ```Import-Package: org.slf4j;version="[1.7.0,1.8.0)"```.

https://github.com/eclipse/buildship/blob/3111a7a9fe3e22d6123366686874ecd42aa2a53a/org.eclipse.buildship.core/META-INF/MANIFEST.MF#L19

https://github.com/eclipse/buildship/blob/3111a7a9fe3e22d6123366686874ecd42aa2a53a/org.gradle.toolingapi/META-INF/MANIFEST.MF#L8

Regards,
M.

**Comment by mbooth101** [comment]
+1

FWIW, Eclipse m2e already made the switch from Require-Bundle to Import-Package for slf4j packages because (quite aside from being the OSGi best practive) the Require-Bundle was causing us issues in our downstream rebuilds (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=506473 for details)

**Comment by donat** [comment]
The constraint declaration above only says that Buildship/TAPI works with SLF4J 1.7.2 and above (see OSGi core spec 3.2.6). However, I using package requirements for slf4 makes sense, thanks @mbooth101 for the explanation.

**Comment by donat** [comment]
The changes are in: https://github.com/eclipse/buildship/compare/donat/use-package-import-for-slf4j?expand=1
