### ISSUE TITLE
Eclipse launch configuration argument variables for gradle buildscript variables

### ISSUE THREAD

**Issue by stefanleh** [eclipse/buildship#870]
Is there a way to access gradle buildscript variables via the argument variables in Eclipse launch configurations? 
I'm currently trying to use an Javaagent i define as dependency in the buildscript and need the expanded path to the dependency.

Thanks in advance, Stefan

**Comment by stefanleh** [comment]
Is there any documentation about how Buildship passes arguments to the Launchers?

**Comment by donat** [comment]
Currently, there's no way to do that. If we are talking about the execution of a `main()` then here's what I'd do:
- define a custom `JavaExec` task in the build script
- define the java agent in the `jvmargs` property
- create a simple launch configuration for the task
