### ISSUE TITLE
Problem with deploy task with gradle-ssh-plugin

### ISSUE THREAD

**Issue by peppe7119** [eclipse/buildship#874]
Hi,
starting with the following bug:

https://github.com/int128/gradle-ssh-plugin/issues/331

I have an issue after the version 2.2.2.

If i try to task a deploy i have this error:

```
* What went wrong:
Execution failed for task ':deployWar'.
> identity must be a File, String or null (deployHost[[:]:22]). Expression: (((settings.identity instanceof java.io.File) || (settings.identity instanceof java.lang.String)) || (settings.identity == null))

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

Version 2.2.1 no problem (http://download.eclipse.org/buildship/updates/e47/releases/2.x/2.2.1.v20180125-1441)

Please check this issue.

**Comment by donat** [comment]
Can you upgrade to the latest Buildship version? We still create releases for Eclipse 4.7.

**Comment by peppe7119** [comment]
I am using this version at the moment:  

Buildship: Eclipse Plug-ins for Gradle	3.1.4.v20200326-1743	org.eclipse.buildship.feature.group	Eclipse Buildship

**Comment by donat** [comment]
I'm fairly certain that this has nothing to do with. You probably don't have a wrapper configuration in your project, so Buildship falls back to a Gradle version which is specific for each Buildship release. 

Please check the following:
- Open the project preferences and select `Gradle` in the dialog
- Check `Override workspace settings`, set the `4.3` Gradle version. (version bundled with Buildship 2.2.1)
- Click `Apply and close`
- From the project's context menu, Select `Gradle > Refresh Gradle Project`
- Do the same steps for Gradle `4.10.2`. (version bundled with Buildship 2.2.2)

If you confirm that indeed the Gradle version difference causes the error then you can start investigating how to upgrade your build. If you have any questions about that, you can post them on the [Gradle forum](https://discuss.gradle.org/).

FYI, Buildship 2.2.1 is really outdated and there's no reason not to update to the latest version.
