### ISSUE TITLE
Update Gradle logo/icon

### ISSUE THREAD

**Issue by jlstrater** [eclipse/buildship#875]
We've recently published the newest Gradle elephant logos to https://gradle.com/brand. I'd be happy to contribute this change. Please let me know if I should proceed.

**Comment by donat** [comment]
Hi @jlstrater! Sorry, this issue somehow slipped through. 

All images in Buildship are stored in the icons folder. Previously Charles provided us new icons, he might have some automation in place to generate icons for this project. Can you coordinate with him?
