### ISSUE TITLE
Composite Build Import Fails With UnsupportedConfigurationException in version 3.0.1

### ISSUE THREAD

**Issue by davisbri** [eclipse/buildship#877]
I have a project that was developed using Buildship version 2.2.1.v20180125-1441 and Gradle version 5.2.1.. After updating Buildship to version 3.0.1.v20181217-1554, importing the project into eclipse fails with an UnsupportedConfigurationException: Multiple projects in the build are located in the same directory. 

This project builds using Gradle outside of Eclipse, and we are able to continue using Buildship if we downgrade the plugin to version 2.2.1 or 2.2.2. Is there a reason this configuration became unsupported in version 3.0.1?

I've created a sample/dummy project to reproduce this issue: [CompositeBuildTest](https://github.com/davisbri/CompositeBuildTest).
To reproduce: 
Clone repository above. 
Using Buildship version 3.0.1, import the project into eclipse by setting the Project Root Directory to the CoreProject and by using gradle version 5.2.1 or above (see screenshots below).

My environment consists of Windows 10 Pro (v1809), Eclipse  2019-3(4.11.0), Buildship 3.0.1.v20181217-1554

![Wizard1](https://user-images.githubusercontent.com/5470231/56592712-70a0ac80-65a8-11e9-8167-a5a197ac295f.PNG)
![Wizard2](https://user-images.githubusercontent.com/5470231/56592721-726a7000-65a8-11e9-8976-f2dd4d73d3e3.PNG)
![Wizard3](https://user-images.githubusercontent.com/5470231/56592728-75656080-65a8-11e9-91de-14fba0e7de66.PNG)
![Eclipse](https://user-images.githubusercontent.com/5470231/56592737-78605100-65a8-11e9-8832-68018f6222c8.PNG)
![ImportError](https://user-images.githubusercontent.com/5470231/56592740-79917e00-65a8-11e9-987f-82bee2bab876.PNG)

**Comment by hanct** [comment]
Have u solved this issue? Cos I encounter the same issue previously. If I dont recall wrongly, i think i resolve it by ensureing the settings.gradle file's rootProject.name is set to the name of the project folder u import. For your case, CoreProject.

**Comment by davisbri** [comment]
No, I have not solved the issue yet. Currently, the settings.gradle file for the imported project folder has the rootProject.name property properly set to 'CoreProject', and it's still an issue.

**Comment by catonymous** [comment]
This is a really annoying bug. The only way to work it around is to comment composite builds in settings.gradle, to import/synchronize and then uncomment them back.

**Comment by euschn** [comment]
> 
> 
> This is a really annoying bug. The only way to work it around is to comment composite builds in settings.gradle, to import/synchronize and then uncomment them back.

Can you elaborate on how to work around this? I have exactly the same problem.

**Comment by deanorderly** [comment]
Shucks, I was looking to switch from Intellij.  I guess I am stuck then for now.  I wanted to test our builds in eclipse as I like their compile better for our team, but until this is fixed, I can't seem to get it to work.

**Comment by jhyry-gcpud** [comment]
I am seeing this issue as well.
It started happening when I went from a multi-project to multi-project/-composite build.

**Comment by drkstr101** [comment]
I was running into this issue, and it turned out I had the same project included twice from two different relative locations (both technically correct by themselves).

I had to get rid of the `includeBuild '../other-project` that existed farther down, and just keep the `includeBuild 'other-project` at the top. Note: This didn't cause the Gradle build to fail, but both eclipse and VSCode didn't seem to like it when that was in there.

**Comment by hakanai** [comment]
Same issue here. Structure is essentially:

Project A includes Project B and Project C
Project B includes Project D
Project C includes Project D

And then I get an error about Project D being in the same directory as Project D. Seems like buildship should be deduplicating projects as it imports the dependency graph but isn't?

**Comment by washtubs** [comment]
Yes I had a similar structure where

A includes B and C
B includes C

The issue went away when I made A stop explicitly including the build for B

**Comment by donat** [comment]
Sorry for the late reply. I no longer have access to the sample in the first comment. At the same time, this is exactly we fixed in the latest Gradle/buildship release. Can you please try with Gradle 6.8 and with Buildship 3.1.5?

**Comment by andresmtz98** [comment]
> Sorry for the late reply. I no longer have access to the sample in the first comment. At the same time, this is exactly we fixed in the latest Gradle/buildship release. Can you please try with Gradle 6.8 and with Buildship 3.1.5?

It's working for me with 3.1.5
