### ISSUE TITLE
Replace project dependencies with the published artifacts if corresponding workspace project is closed

### ISSUE THREAD

**Issue by donat** [eclipse/buildship#881]
## Overview 
In order to work with Gradle projects with Buildship, all projects need to be imported into the workspace. If the user closes or deletes a workspace project then all project referencing the closed one will have an incomplete classpath.

To make the situation more convenient, Gradle should replace the project dependencies with binaries based on the state of the workspace.  With that, 
a missing project reference would turn into a (valid) dependency to a jar file. 

The implementation has the following steps:
- Buildship sends the project open/close status to Gradle
- Gradle runs the publication task (`jar`) before building the model
- The `EclipseProject` builder replaces the project dependencies with binaries 

## Step 1: Buildship sends the project open/close status to Gradle

The `EclipseWorkspaceProject` should have a new `isOpen()` method which is populated and passed to Gradle.

## Step 2: Gradle runs the publication task (`jar`) before building the model

The synchronization should use the phased API (`BuildActionExecuter.Builder.projectsLoaded`) to pass the `EclipseWorkspace` model to Gradle and let it execute the tasks creating the publications. The calculation can be done via `ArtifactViews`:

```groovy
 def closedProjectDeps = configurations.runtimeClasspath.incoming.artifactView {
    it.componentFilter { c ->
        c instanceof ProjectComponentIdentifier && c.projectPath == ':closed-project'
    }
}

closedProjectDeps.files.buildDependencies.getDependencies(null).each {
    System.err.println("task to execute=$it.path")
}
```

## Step 3: The `EclipseProject` builder replaces the project dependencies with binaries 

Like in Step 2, the artifact view can be used to calculate dependencies by filtering the result with and without the closed project entries and checking the difference.

**Comment by donat** [comment]
FTR this is an alternative approach for partial import described at #246 and #247.

**Comment by kuniss** [comment]
@donat, I wondering, how this is related to #690?

**Comment by donat** [comment]
Composite builds should work as well. Can you please give it a try and check if it works as you expect it to work?

**Comment by kuniss** [comment]
@donat, at least it does not work as I expected on example provided with #690 .
![grafik](https://user-images.githubusercontent.com/1107971/65898874-c62c8100-e3b2-11e9-93fa-06daa006782a.png)

(I enabled Automatic Project Synchronization)
![grafik](https://user-images.githubusercontent.com/1107971/65898929-e52b1300-e3b2-11e9-8443-db51e9d6cba5.png)

Did I miss something? 

I'm using Eclipse 2019-09 with
Eclipse Buildship	Buildship, Eclipse Plug-ins for Gradle	3.1.2.v20190903-1802	org.eclipse.buildship.branding

Denis

**Comment by donat** [comment]
I managed to import the sample project from #690 and use the substitution feature locally. 

I think there's a fundamental difference in what this feature and #690 describes. This feature deals with dependencies within a single (but potentially composite) build. What #690 describes is basically assembling a new composite build based on the contents of the workspace.

**Comment by kuniss** [comment]
@donat, but shouldn't the solution of this issue work well also for the given example from #690?

Maybe, I misunderstood you: What do you mean with "... and use the substitution feature locally"? Did it work for you?

**Comment by donat** [comment]
Yes, the example works as expected. Let me show you:

1. Import the project with Gradle 5.6.2 (the supplied wrapper uses Gradle 4.3 which is ancient)

<img width="760" alt="Screenshot 2019-10-10 at 11 50 40" src="https://user-images.githubusercontent.com/419883/66558742-5ce80300-eb54-11e9-959a-90bd432bfe24.png">

2. Closing the `project-client` project causing an incomplete classpath

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/419883/66558924-c0723080-eb54-11e9-958a-6f37374b9da2.png">

3. Executing synchronization replaces the closed project dependency with the jar file published from `project-client`

<img width="1020" alt="Screenshot 2019-10-10 at 11 57 35" src="https://user-images.githubusercontent.com/419883/66559170-34143d80-eb55-11e9-98b8-54c6540ff386.png">

The jar file contains all the changes from `project-client` and will be updated every time you execute project synchronization but you don't have to have it open in the workspace.

This is a big step towards partial import, but right now we still need to have the closed projects in the workspace. The final piece is to remove this constraint and offer a filter for the users and let them choose which subprojects they want to import.

**Comment by kuniss** [comment]
Hi @donat, works for me too now after having upgraded the wrapper to the latest Gradle version.

What I'm a little bit suprized, however, is that when I reopen the project-client project again, the jar dependency is sustituted automatically by the local Eclipse project depenedency. The project does not need to be refreshed. 

This is a kind of inconsistent behavior between opening and closing a project which are complementary actions, normally. Is this intended that way?

Wouldn't it be more consistent if closing the project-client would automatically make a "Refresh Gradle Project" such that the classpath does not become incomplete? 

[BTW, sorry for having mixed up client and server in the example - the dependency should be vice versa. Just realized by myself.]

**Comment by kuniss** [comment]
> This is a big step towards partial import, but right now we still need to have the closed projects in the workspace. The final piece is to remove this constraint and offer a filter for the users and let them choose which subprojects they want to import.

Is this where #690 could help to provide a solution?

**Comment by donat** [comment]
> What I'm a little bit suprized, however, is that when I reopen the project-client project again, the jar dependency is sustituted automatically by the local Eclipse project depenedency. The project does not need to be refreshed.

I don't see this behaviour: when I open the closed `project-client` project again then nothing happens: `project-server` still references `project-client-1.0.0.jar`. I have to explicitly start the project synchronization to revert the jar dependency to a project dependency to `project-client`. If you see a different behavior then that's a bug.

I think this behavior (i.e. not running synchronization automatically) is better as project configuration is potentially expensive and could potentially block users from continuing their work.

**Comment by donat** [comment]
> Is this where #690 could help to provide a solution?

No, the missing pieces are mainly UI-related: we need to provide UI to select the subproject that should be imported in the workspace.
