### ISSUE TITLE
Project Import does not persist workspace overrides

### ISSUE THREAD

**Issue by fraenkelc** [eclipse/buildship#893]
The options specified during project import are not transferred to the resulting gradle project. This works for creating new projects though:

**Create Project (works)**
![2019-06-17 22_26_18-New Gradle Project](https://user-images.githubusercontent.com/4005102/59634923-2541ef00-9150-11e9-8519-4c394cce4cb6.png)
![2019-06-17 22_27_04-create confirmation](https://user-images.githubusercontent.com/4005102/59634926-283cdf80-9150-11e9-8284-40793a894a66.png)
![2019-06-17 22_28_11-Properties for created](https://user-images.githubusercontent.com/4005102/59635030-6afeb780-9150-11e9-8fb6-0f07617e98fe.png)

**Import of the same project (fails)**
![2019-06-17 22_28_56-Import Gradle Project](https://user-images.githubusercontent.com/4005102/59634967-40146380-9150-11e9-8dbb-81c5eba3a340.png)
![2019-06-17 22_29_20-Import Gradle Project confirmation](https://user-images.githubusercontent.com/4005102/59634975-43a7ea80-9150-11e9-8278-2b05c749ae8c.png)
![2019-06-17 22_30_15-properties for imported](https://user-images.githubusercontent.com/4005102/59634979-460a4480-9150-11e9-9957-4c2846fa2c1f.png)

I noticed this while debugging another issue. There I noticed that the first execution listed in the Gradle Operations console was running with the gradle version specified in the console. The second execution in the console was using the version in the gradle wrapper.

# Environment
Buildship 3.0.1.v20181217-1554
Eclipse 4.11.0

**Comment by donat** [comment]
I was able to reproduce the issue.
