### ISSUE TITLE
那个最终释放的gradle  buildship-REL  文件，我应该如何在eclipse使用呢？

### ISSUE THREAD

**Issue by Apyz** [eclipse/buildship#898]
我尝试直接拖入eclipse，或者直接安装，它提示错误，无法直接安装这个插件。
那么在安装这个插件之前，我应该做些什么呢？
希望有人能够明白我在说什么。

**Comment by donat** [comment]
I tried to use google translate, and the only thing I could understand is that you have some sort of installation problem. If you could elaborate on the problem in English then you'll have a better chance to get help.
