### ISSUE TITLE
Buildship & Guava & 2019-09 M2

### ISSUE THREAD

**Issue by cdietrich** [eclipse/buildship#906]
The Buildship version (3.1.0) contributed to 2019-02 M2 still contains a dependency to guava 21 which was dropped from Orbit 2019-09 M2 (along with guava 18)

=> should be updated to >= 3.1.1

**Comment by cdietrich** [comment]
I also wonder if we can take this opportunity to publish 3.1.2

**Comment by donat** [comment]
I've just added Buildship 3.1.1 to simrel: https://git.eclipse.org/r/#/c/148188/
I have a few things to finish regarding [test debugging,](https://github.com/eclipse/buildship/issues/249) but after that, we'll proceed with the 3.1.2 release.
