### ISSUE TITLE
Support for multi-composite builds

### ISSUE THREAD

**Issue by Kameecoding** [eclipse/buildship#908]
Buildship should properly support multi-composite builds, e.g. when multiple projects use a shared library and want to include it.

There is already a few issue reported here that relate to this.

Let's imagine a scenario where you have a library that you are developing that is used by multiple projects.

`libraryProject`

then you have two projects A and B

    A - settings.gradle
    includeBuild "../libraryProject"

 and also an application where you use both A and the library:

    B - settings.gradle
    includeBuild "../libraryProject"
    includeBuild "../B"

This not an unreasonable scenario if you want to have a dev environment where you want to see all the changes that are being made, yet the projects themselves are built separately for release.

However when you try to import the `app` using buildship 3.+ it fails with the message that multiple projects share the same directory, in this case it's cause because the `libraryProject` gets duplicated and buildship detects it as two different projects.

In buildship 2.0 this worked, with some minor inconveniences:
e.g. https://github.com/eclipse/buildship/issues/360

Similar case reported here: https://github.com/eclipse/buildship/issues/877

**Comment by euschn** [comment]
I have exactly the problem as described above with my project. The project has multiple composite build dependencies and works fine in the command line and in Netbeans, but not with Eclipse/Buildship.

Please fix this, as it keeps me from developing my project in Eclipse. If there is some workaround to this problem, I would also greatly appreciate it.

**Comment by donat** [comment]
Related issue: https://github.com/gradle/gradle/issues/8031

**Comment by donat** [comment]
I've created a [WIP PR](#962) for solving this issue and I'm planning to publish a snapshot release based on it. @Kameecoding (and anybody interested): would you be interested trying it out and/or reviewing my changes?

**Comment by Kameecoding** [comment]
@donat I can test on our older codebase, we have switched away from composite builds since because we weren't able to update to Buildship 3+.

**Comment by donat** [comment]
The update site of the snapshot is available here: https://download.eclipse.org/buildship/updates/e414/snapshots/3.x/3.1.4.v20200108-1545-s

**Comment by AndreasFagschlunger** [comment]
@donat Just wanted you to know that in my setup it works. I used eclipse 2019-12 with the latest Buildship plugin version and within eclipse the project had an error saying something about two projects using the same path. Then I installed the snapshot version, restarted eclipse, refreshed gradle project and the error was gone. Love it, thanks!

**Comment by ams-tschoening** [comment]
@Kameecoding What do you have switched to instead of composite builds? Multi-project builds or publishing each build to some internal repo or ...?

**Comment by ams-tschoening** [comment]
Successfully tested the linked version of buildship as well, the error message is gone now. Though, it still prints in my opinion unnecessary warnings and loading Gradle tasks etc. is still very slow, as it seems that the same builds are processed multiple times.

Any plans to publish that version of Buildship with the next Eclipse? Some people like me manage one system wide Eclipse with different configs+workspaces and lack write permissions on Eclipse itself. This makes replacing Buildship a bit more difficult: One needs to get write permissions to Eclipse, uninstall Buildship from the default deployment and install it manually per config+workspace again.

**Comment by euschn** [comment]
@ams-tschoening I fixed composite builds in eclipse/buildship by following the accepted answer here:
https://stackoverflow.com/questions/43989057/how-to-allow-workaround-nested-composite-gradle-builds

Using the composite check works for me in the current version of buildship.

**Comment by Kameecoding** [comment]
@ams-tschoening 
We have switched our build into a multi-project setup for the time being.

**Comment by ams-tschoening** [comment]
@euschn Thanks for the hint, but that approach especially breaks transitive resolution of dependencies among all included builds: The including root-project needs to include each build which would otherwise be included automatically because of nested includes. Additionally, it doesn't change a thing [about task views](https://github.com/eclipse/buildship/issues/511#issuecomment-420921463).

OTOH, the [warning produced](https://github.com/eclipse/buildship/pull/962#issuecomment-590994535) by the linked version of Buildship seems to be removed that way and things seem to be a bit a faster when Buildships processes projects. Not sure currently what I prefer...

**Comment by donat** [comment]
This should work with the latest version of Gradle (6.8-rc-1) and Buildship ([link to snapshot update site](https://download.eclipse.org/buildship/updates/e416/snapshots/3.x/3.1.5.v20201209-1704-s/)). Would you mind giving it a try?

**Comment by stephanebastian** [comment]
Hi,
I've tested the latest Gradle version (6.8-rc1) and the latest buildship version (the one with the link above) and I confirm that I could import the CompositeB gradle project into Eclipse

```
- CompositeA
  - sharedGradlePlugins
  - projectA
  - setting.gradle.kts is:
     includeBuild("sharedGradlePlugins")
     include("projectA)
- CompositeB
  - projectB
  - setting.gradle.kts is:
     includeBuild("../CompositeA/sharedGradlePlugins")
     includeBuild("../CompositeA")
     include("projectB)

```

In  the end, all projects were imported in my workspaces
- projectA
- projectB
- sharedGradlePlugins

This is great!
Thanks a bunch

**Comment by donat** [comment]
Excellent, thank you for checking. I'm planning a Buildship release shortly after Gradle 6.8 comes out.

**Comment by donat** [comment]
Closing as implemented. The Buildship release is imminent :)

**Comment by claui** [comment]
Thanks @donat, appreciate your hard work!
