### ISSUE TITLE
Buildship changes build path settings

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/buildship#910]
Hi

When using a gradle buildship project, is see this behavior.

I did these settings manually in the Eclipse UI:

In build path --> libaries --> "Project and External Dependencies" --> "External annotations"
Here I set a path for the null-annotations files.

In build path --> Source --> for the test sources I set
- Ignore optional compile error = yes
- Contains test sources = Yes

After doing a gradle -> "refresh gradle project", those settings got reverted to defaults.
This does not happen always on refresh. I don't know why I happened.

Can you help?
Or can i define those settings in build.gradle, so buildship can take them from there?

Frank

**Comment by donat** [comment]
That's the correct behavior, as Buildship infers those values from the project configuration.

> Or can i define those settings in build.gradle, so buildship can take them from there?

You can set the proper classpath attrbute with a similar script: 

```groovy
plugins {
    // ...
    id 'eclipse'
}

eclipse {
    classpath {
        containers 'org.eclipse.buildship.core.gradleclasspathcontainer'
        file {
            whenMerged {
                def con = entries.find { it.path == 'org.eclipse.buildship.core.gradleclasspathcontainer' }
                def src = entries.find { it.path == 'src/test/java' }
                con.entryAttributes['test'] = 'false'
                src.entryAttributes['ignore_optional_problems'] = 'true'
            }
        }
    }
}
```

**Comment by frankbenoit** [comment]
Thanks, that help me a lot.
