### ISSUE TITLE
There is a project property that can be used to determine, at runtime, that a build was run with Eclipse/Buildship

### ISSUE THREAD

**Issue by autonomousapps** [eclipse/buildship#911]
This can be useful for build scans, as we can use the property to tag the build `Eclipse`. See for example this working Groovy code:
```groovy
void tagIde() {
    if (project.hasProperty('android.injected.invoked.from.ide')) {
        buildScan.tag 'Android Studio'
    } else if (project.hasProperty("idea.executable")) {
        buildScan.tag 'IDEA'
    } // TODO Eclipse?
}
```

**Comment by donat** [comment]
@autonomousapps as a workaround, you could check for the presence of the `eclipse.buildId` environmental variable.

**Comment by donat** [comment]
Closing as there's a system property available.

**Comment by autonomousapps** [comment]
Is it an environment variable or a system property? Your comment from 5 days ago says the former, and the latest from 4 days ago says the latter.

**Comment by donat** [comment]
it's a system property inherited from the host Eclipse process.
