### ISSUE TITLE
subproject has changing .settings/org.eclipse.buildship.core.prefs

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/buildship#915]
I have several projects as siblings in one directory.
one the the "share" project. Then there is project "A" and "B".

Those three are not in gradle multi-project.
Instead "A" is independent from "B". But "A" and "B" include "shared" with settings.gradle:

    include ":shared"
    project(":shared").projectDir = file("../shared")

The problem is, once i work with "A", in base/.settings/org.eclipse.buildship.core.prefs is changed connection.project.dir=../A
And if i work with "B", the .settings/org.eclipse.buildship.core.prefs changes to connection.project.dir=../B

This is not good, as this file is in version control and repeatedly marked as changed.

Can this change in the base/.settings/org.eclipse.buildship.core.prefs file be avoided?

**Comment by Yay295** [comment]
I've run into this problem too. It would be nice if it could be a list of paths instead of just one, but Java properties files don't support arrays... There are definitely ways around that though.

**Comment by kxweili** [comment]
I've run into this problem too. Every time refresh the Gradle projects. I need to manually reset them back.

**Comment by donat** [comment]
All I can say is that Buildship is not prepared for this use-case. 

Let's say we remove the limitation.  If you right-click on the `shared ` project in eclipse and run project synchronization, which build would you sync, A or B? You could argue that it probably doesn't matter. Still if `shared` could technically be configured differently in the context of A and B. Overall, the solution would just make Buildship more confusing.

It might be a silly proposal, but can you solve the problem with symlinks? 
- create two new directories, `shared-a` and `shared-b`
- in both directories, create symlinks to `shared/src` 
- replace `project(":shared").projectDir = file("../shared")` with project(":shared").projectDir = file("../shared-a")

I'm closing this issue just to keep our project board clean, but it doesn't mean that the conversation is over. I'll reopen it if there's a compelling argument for the implementation.
