### ISSUE TITLE
Importing large maven project in eclipse 2019-6 is extremely slow(er than in 2019-3)

### ISSUE THREAD

**Issue by NourNuxeo** [eclipse/buildship#920]
Hi,
I have a 350 modules project I'm used to import in eclipse 2019-3 (everytime I work on a new branch). It imports (without building) in something like 4 minutes which is fine.
The same project imported in eclipse 2019-6 takes approx 30 minutes and can end up with projects not being packaged correctly in the explorer.

This is whithout even building. (Disable automatic build)

I can't find what's the reason...in the end I tried using an external maven to be sure to use the same on both eclipses and the difference is still the same.

btw "updating maven projects" will be as slow / fast as the initial import which makes it really hard to work.

Any idea what's going on ?

Edit: I can definitely tell by the heat and the sound of the fans of my computer that 2019-6 is not using as much resources as 2019-3 for the task. (Both have 8g allocated as max memory)
Edit2: I forgot to mention I'm on the latest macOS

**Comment by donat** [comment]
It seems like your problem has nothing to do with Gradle/Buildship. Please post your question at the [m2e-users](https://accounts.eclipse.org/mailing-list/m2e-users) mailing list.

I'm closing this issue as invalid. If you indeed have a Gradle problem feel free to re-open it.
