### ISSUE TITLE
Wrong update site on 2019-06

### ISSUE THREAD

**Issue by Seth-Gecko** [eclipse/buildship#921]
Just downloaded and installed Eclipse IDE for Java Developers 2019-06 on a Linux Mint VM. Checked the Available Software Sites section where `https://download.eclipse.org/buildship/updates/e410/releases/3.x` is set. Shouldn't it be set to `https://download.eclipse.org/buildship/updates/e412/releases/3.x` according to the [installation instructions](https://github.com/eclipse/buildship/blob/master/docs/user/Installation.md#installing-from-eclipseorg-update-site)? 

Or maybe Eclipse should be rolled out with `https://download.eclipse.org/buildship/updates/latest/` in newer versions?

Additional info:
- I came across this due to a [repository not found](https://github.com/eclipse/buildship/issues/488) issue which I was able to fix by using `https://download.eclipse.org/buildship/updates/latest/` instead.
- Maybe this is related to #892.

**Comment by Siedlerchr** [comment]
I had the same problem. Doing the update via Eclipse marketplace client seemed to work.

**Comment by jamestomk** [comment]
Agree, Eclipse should be rolled out with https://download.eclipse.org/buildship/updates/latest/ in newer versions, and should be an option suggested for all add-on developers (probably is?)

**Comment by donat** [comment]
> Just downloaded and installed Eclipse IDE for Java Developers 2019-06 on a Linux Mint VM. Checked the Available Software Sites section where https://download.eclipse.org/buildship/updates/e410/releases/3.x is set

That might have been a mistake on our side but we can't do anything about it as the release is out.

> Or maybe Eclipse should be rolled out with https://download.eclipse.org/buildship/updates/latest/ in newer versions?
Eclipse has a hard requirement to contribute specific plugin versions to the Simultaneous Release. 

You can use the `latest` update site or the marketplace to always get the latest version.
