### ISSUE TITLE
eclipse.classpath.file.withXml is never executed

### ISSUE THREAD

**Issue by dejvu** [eclipse/buildship#923]
I want to modify .classpath eclipse file using gradle. According to the docs https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html i should use withXml for advanced configuration but withXml closure is never invoked.
Here is a minimal sample to reproduce issue
```
apply plugin: "java"
apply plugin: "eclipse"

group = "example"
version = "1.0.0"

eclipse.classpath.file {
    withXml { xml ->
        println "This is never executed"
        println xml.asNode().text()
    }
}
```
Project is imported in eclipse using Buildship plugin.
As an extra note withXml is not executed even if run over command line.

Eclipse 2019-06
Buildship 3.1.1
Gradle 5.6.2

**Comment by stefanleh** [comment]
In my experience it is executed when using the pure eclipse plugin via "gradle eclipse" on commandline but not when using "Refresh Gradle Project" from within Eclipse IDE.

Have you tried the example from the docs as well?

	withXml {
		def node = it.asNode()
		node.appendNode('xml', 'is what I love')
	}

**Comment by donat** [comment]
This is unfortunate but expected. The `eclipse` Gradle plugin and Buildship have _some_ common configuration but are mutually exclusive.

When working with Buildship you need to use `whenMerged` as opposed to `withXml`. 

Context: `whenMerged` is not special, we just hooked it into the sync process to leverage the mission configuration options. We could do the same with `withXml`, but the only value would be consistency, and it would only work with the Gradle release containing the fix.

The ultimate solution would be to have a separate DSL for Buildship. This is something I wanted to have for a very long time.
