### ISSUE TITLE
Test classes leaking into Deployment Assembly when configuring APT in Eclipse

### ISSUE THREAD

**Issue by esz** [eclipse/buildship#926]
# Expected Behavior
Enabling Annotation Processing in a Web Project should not result in content from `.apt_generated_tests` being packed into the Deployment Assembly.

# Current Behavior
Enabling Annotation Processing on a Web Project adds the following entry to `.settings/org.eclipse.wst.common.component`:

```
<wb-resource deploy-path="/" source-path="/.apt_generated_tests"/>
```
The corresponding `classpathentry` in `.classpath` is:

```
<classpathentry kind="src" output="bin/test" path=".apt_generated_tests">
	<attributes>
		<attribute name="optional" value="true"/>
		<attribute name="test" value="true"/>
	</attributes>
</classpathentry>
```

# Steps to Reproduce
Please have a look at [esz/buildshipapt](/esz/buildshipapt) where I created a small example.

## Variant 1

1. Import the project using Buildship and Gradle Wrapper
2. Observe the contents of `buildshipapt-core/.settings/org.eclipse.wst.common.component`:

```
<?xml version="1.0" encoding="UTF-8"?><project-modules id="moduleCoreId" project-version="1.5.0">
	<wb-module deploy-name="buildshipapt-core">
		<wb-resource deploy-path="/" source-path="src/main/java"/>
        	<wb-resource deploy-path="/" source-path="/.apt_generated"/>
        	<wb-resource deploy-path="/" source-path="/.apt_generated_tests"/>
	</wb-module>
</project-modules>
```

I'm using the `net.ltgt.apt-eclipse` and the synchronization task `eclipseJdtApt` (see `build.gradle` in project root) to have APT configured automatically upon project import. AFAIK there's no out-of-the-box support for that in gradle ([gradle/#2300](/gradle/gradle/issues/2300#issuecomment-460065789), #329).

## Variant 2

1. Uncomment `net.ltgt.apt-eclipse` and the synchronization tasks in `/build.gradle` before importing the project:

```
/* plugins {
  id "net.ltgt.apt" version "0.21" apply false
}*/

allprojects {
	group = 'at.szente.sample'
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'eclipse-wtp'
	// apply plugin: 'net.ltgt.apt-eclipse'

	repositories {
		jcenter()
	}

	/* eclipse {
		synchronizationTasks 'eclipseJdtApt', 'eclipseFactorypath', 'eclipseJdt'
	}*/
}
```
2. Import the project using Buildship and Gradle Wrapper
3. Enable Annotation Processing manually in the Project Properties of `buildshipapt-core`
![enable_apt](https://user-images.githubusercontent.com/436707/65908253-588a5000-e3c6-11e9-8ca0-6ce33b83daa6.png)
4. Observe that the Deployment Assembly contains `.apt_generated_tests` again.

# Environment
- Gradle 5.6.2
- Eclipse  2019-09 R (4.13.0)
- Buildship 3.1.2.v20190903-1802

**Comment by donat** [comment]
Buildship doesn't provide any annotation processing support at the moment. If you have a working example of how to configure the eclipse plugin to support that please publicize though. I think it would be valuable for the community.
