### ISSUE TITLE
Replace jar dependencies by eclipse project dependency

### ISSUE THREAD

**Issue by cilheo** [eclipse/buildship#935]
Project_A is a gradle project.
    - Group : "com.myproject"
    - Version : "1.0.0-SNAPSHOT"

Project_B is another gradle project import in eclipse.
    - Group : "com.myproject"
    - Version : "1.0.0-SNAPSHOT"

Project_B have a dependencies declaration like that : 
dependencies {
    api "com.myproject:Project_A:1.0.0-SNAPSHOT
}

In eclipse, i see the jar publish by project A. All is ok.
If i import Project_A in eclipse , i would like to see Project_B with an eclipse project dependency on Project_A instead of jar (only if Project_A is open).

Maven plugin on eclipse used to do that. How i can do that with buildship ?

**Comment by donat** [comment]
Check out Gradle's [composite build](https://docs.gradle.org/current/userguide/composite_builds.html) feature. With that, you can combine independent builds into a composite one. Buildship support importing composite builds, sho the jar-project substitution should happen automatically.

**Comment by cilheo** [comment]
I don't think composite build can resolve my problem.

I really want to depends on a jar and not on another project. If i used composite build, i need to have both Project_A and Project_B project on my computer.

I will prefer the opposite. I depends on jar and if i have Project_A source, i depends on it.

But maybe, I do not understand how to use composite build.

For a better understanding. I do not work with 5-6 project but 70-80 who have dependencies between them.

**Comment by donat** [comment]
You are right, with my proposed solution, you'd end up with both project A and B fully imported in the workspace. There's no automatic support for ad-hoc dependency substitution like m2e. There's a solution though. You can [adjust](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012) the content of the Gradle classpath container.
You can add a snippet to your build script that replaces all library dependency with project dependency if it exists in the workspace.

**Comment by cilheo** [comment]
thanks for the information. I'm going to see this tomorrow. I looked quickly and I do not feel like I saw an example with what I want.

Did you think that such features could be integrated into buildship one day?

**Comment by donat** [comment]
What you want is dependency substitution based on the project name. In general, it's not a good idea because the project names are not fixed in the workspace: they are deduplicated to avoid name clashes (try to create an independent project then add/rename a Gradle project with the same one). The dependency substitution would be unstable without the deduplication being disabled.

**Comment by cilheo** [comment]
sorry for the long time response.

I don't want to do it on the project name. But on the group/name and version define in the gradle project. Like maven who based the substitution on the primary artifact.

I don't know if it's easy to do that. I don't know which information is accessible.

**Comment by donat** [comment]
> I really want to depends on a jar and not on another project. If i used composite build, i need to have both Project_A and Project_B project on my computer.

I don't quite follow. In order to match the coordinates (group/name), we would need to load them from the Gradle build, which requires both projects to be available locally.

**Comment by cilheo** [comment]
Yes. Exactly.

Project A have a dependency on com.myproject:B:2.0.0
```
<dependencies>
       api 'com.myproject:B:2.0.0
</dependencies>
```

If Project B is not present in eclipse or not open or not in version 2.0.0, Project A get the jar
If Project B is open in eclipse, project A have a dependency on project B

**Comment by chhex** [comment]
@cilheo that would only work by assuming some naming convention between artifact coordinates and vcs module naming.  Or buildship would have to implement substantial workspace knowledge into it‘s code. Yes, m2e does this, but i actually came to prefer the buildship approach, since it is explict and you are in control.  Not only for performance reason, but yes also, especially if you have many modules in your workspace.

**Comment by cilheo** [comment]
yes, you are true. Team are more in control with your solution @chhex .
We are switching from maven to gradle and the politics of change is not easy to put in place.

I am against the fact that the current solution is easier with a large number of modules. If i work on a project A,B,C who depends on D. I need to modify A,B,C build.gradle. Automatic operation like m2e is simpler. Maybe, with a checkbox for activate this thing in the configuration of buildship.

**Comment by chhex** [comment]
@cilheo yep, i understand and know about the situation. You are migrating from maven with a large code basis  and the developers, don‘t care and don‘t have deep knowledge about neither maven nor gradle. For them both are just means to an end. I think an action in eclipse, which automates the changes necessary for a composite buildfor a project , with a list of possible candidates to be included, a good idea and probably not that difficult to implement. If within buildship or not is another question.

**Comment by donat** [comment]
@chhex There's something similar in the works: https://github.com/eclipse/buildship/issues/832

**Comment by chhex** [comment]
@donat ahh great. Sorry missed that one. That would be a helpful one. It could also be done outside of the import possibly.

**Comment by cilheo** [comment]
Yes, the other solution can work. So i think i can close this issue.

**Comment by donat** [comment]
Thanks.
Could you please add a 👍 on #832? It helps prioritizing what issues to work on next.

**Comment by kuniss** [comment]
> @chhex There's something similar in the works: #832. We haven't heard back from the contributor who wanted to implement the feature, but this can change.

@kuzniarz, who implements #832 on our side, is out for a while, but would be back in January, probably.

**Comment by fhackenberger** [comment]
Looks like #832 is not happening. @donat do you think you could share a working snipped for you solution, so people who come here to figure out how to fix this, actually have an actionable way to go ahead until there's a fully working solution built into buildship?

**Comment by kuzniarz** [comment]
@fhackenberger actually it is still in progress. Right now the GUI part is done and needs implementation now in terms of backend.
