### ISSUE TITLE
Adds CSS styling for the Debug/Breakpoint view over mouse  on dark theme 

### ISSUE THREAD

**Issue by pelukron** [eclipse/buildship#938]
Hi all,

I am facing these issue on dark theme, this could be something related with this issue https://github.com/eclipse/buildship/pull/688

![image](https://user-images.githubusercontent.com/5886170/67989753-687d9580-fbf9-11e9-898f-8f2983e25e69.png)

![image](https://user-images.githubusercontent.com/5886170/67989804-8f3bcc00-fbf9-11e9-8aae-56752ab5d0a7.png)

![image](https://user-images.githubusercontent.com/5886170/67989838-b4c8d580-fbf9-11e9-87d8-8f62f093e70a.png)

Best regards

**Comment by donat** [comment]
This is not a Buildship issue. Please send a bug report to the SWT project maintainers.
