### ISSUE TITLE
Changing dependency transitivity in gradle.projectsEvaluated broken

### ISSUE THREAD

**Issue by andilem** [eclipse/buildship#940]
We have several dependencies to external libraries and don't want further dependencies (through transitivity) of those. To achieve that, we are setting all module dependencies to be non-transitive:
```
gradle.projectsEvaluated {
    allprojects {
        configurations.each { config ->
            config.dependencies.each { dep ->
                if (!(dep instanceof ProjectDependency) && dep.hasProperty('transitive')) {
                    dep.transitive false
                }
            }
        }
    }
}
```
When importing our projects in Eclipse with Gradle < 5.6, everything was working fine. We didn't see the dependencies of our declared dependencies.

Starting with Gradle 5.6.0, this is broken. All dependencies of our declared dependencies are listed under "Project and External Dependencies".

Note that this is only an Eclipse / Buildship problem. When calling (from the command line) `gradlew :projectA:dependencies`, we see that the script is still working and properly excluding these dependencies.

**Comment by 3ll3d00d** [comment]
this seems similar to the issue I noticed in https://discuss.gradle.org/t/does-the-lifecycle-of-a-build-differ-when-called-by-buildship-to-import-a-project/33939/6 and which I have logged in https://github.com/eclipse/buildship/issues/952

**Comment by donat** [comment]
@3ll3d00d Yes, it seems like it's the same problem.

**Comment by andilem** [comment]
Any news on this or #952 ? We're still forced to use Gradle 5.5.x because of this, and we would really like to update to 6.x

**Comment by donat** [comment]
Can you please try to create a minimal example project with the problem?
Otherwise, you could try to do the following: 
```
allprojects {
    configurations.all {
        dependencies.all { dep ->
            if (!(dep instanceof ProjectDependency) && dep.hasProperty('transitive')) {
                dep.transitive = false
            }
        }
    }    
}
```

**Comment by andilem** [comment]
Your suggestion (without `gradle.projectsEvaluated {}`) doesn't work, because the dependencies are declared afterwards (in the subproject's build.gradle) and therefore not affected by these lines.

But it works when using
```
allprojects {
    afterEvaluate {
        ....
    }    
}
```
Then, I only have to make sure that there is no `afterEvaluate` block added after this which declares dependencies again (they would again be transitive, because they were added after this code has run).

But I still think that it's a severe bug.

For a minimal example, just declare a dependency to a library which has a transitive dependency to a second library. In `gradle.projectsEvaluated {...}`, set the transitive flag to false. Import the project in Eclipse and be surprised that you still have the second library in your classpath and can use classes from it. It compiles in Eclipse, but not with Gradle itself, because Gradle correctly removes the dependency to the second library.

**Comment by donat** [comment]
`afterEvaluate` seems a reasonable workaround for the time being.

I've done some poking and found that the issue is with Gradle itself. Buildship uses special [phased action API](https://github.com/gradle/gradle/blob/7f371d8a1dc49006abed56bf75412326ed31f2ee/subprojects/tooling-api/src/main/java/org/gradle/tooling/BuildActionExecuter.java) to query the Eclipse model which seems to ignore the `projectsEvaluated`.

**Comment by donat** [comment]
The bug is in Gradle and not in Buildship.
