### ISSUE TITLE
Dependency of different sourceSet is ignored

### ISSUE THREAD

**Issue by andilem** [eclipse/buildship#941]
A project has an additional sourceSet with a declared dependency that is required to compile it:
```
sourceSets {
    another
}
dependencies {
    anotherImplementation 'javax.xml.bind:jaxb-api:2.3.1'
}
```
This dependency is not recognized in Eclipse / Buildship, making it impossible to access classes of the library.

**Comment by donat** [comment]
This has been fixed in the latest Gradle version.
