### ISSUE TITLE
Buildship renames Eclipse project

### ISSUE THREAD

**Issue by fljmayer** [eclipse/buildship#944]
I have a project whose Gradle name is 'service' (after its directory), but the Eclipse project name is 'web-service'. After I do 'Configure > Add Gradle Nature', Buildship renames the Eclipse project to 'service' in the .project file. I think Buildship should leave the Eclipse project alone as it's none of its business.

Currently I am using Eclipse 4.9.0 with Buildship 3.1.2, but I have seen this behavior with Buildship for a long time.

**Comment by donat** [comment]
Duplicate of #1056
