### ISSUE TITLE
Buildship adds Gradle nature to all projects when I add it to just one

### ISSUE THREAD

**Issue by fljmayer** [eclipse/buildship#945]
I have a multi-project Gradle build that has projects with different technologies. Some are OSGI bundles and shouldn't have the Gradle nature so I can use the Eclipse PDE for dependency management within Eclipse. Others are not, and I need the Gradle dependency management within Eclipse. All are built with Gradle on the command line. When I add the Gradle nature to one of the latter projects, Buildship spends a lot of time to add it to all projects in the workspace, even the OSGI bundles. This is not appropriate and it wasn't a problem with the STS Eclipse Integration Gradle. Please only add the Gradle nature to the projects that I requested.

In addition, Buildship also added any intermediate folders as projects into the workspace. 

Then when I try to clean up the mess (i.e. reverting .classpath and .project files, deleting extraneous projects), something starts 'Building workspace' and never completes. I had to kill Eclipse. Next time I started Eclipse, the same never ending 'Building workspace' happens again. I guess Buildship didn't like me removing its 'enhancements' from my Eclipse configuration files.

Currently I am using Eclipse 4.9.0 with Buildship 3.1.2, but I have seen this behavior with Buildship for a long time.

**Comment by donat** [comment]
This is just how Buildshio works: loads the configuration from Gradle, and creates/updates project configuration accordingly.  Check the source code of the Buildship project, there we do something similar: we remove the Gradle dependencies in favor of PDE.
