### ISSUE TITLE
Several problems with Oomph-based setup

### ISSUE THREAD

**Issue by Rhamao** [eclipse/buildship#948]
Hi,

Recently I've been trying to work on Buildship Plug-ins. I followed your "Development Setup Instructions". I chose to use the "Oomph-based setup". I used Windows 10. But I had Several problems. Firstly the process could not finish when I selected "Oxygen" as the product version. Here, are the steps I took before the process failed :  
![1](https://user-images.githubusercontent.com/47444260/69352491-5386a600-0c7d-11ea-8ce7-72a01217af83.png)
![2](https://user-images.githubusercontent.com/47444260/69352493-5386a600-0c7d-11ea-903c-941c41da5286.png)
![3](https://user-images.githubusercontent.com/47444260/69352494-541f3c80-0c7d-11ea-9d5e-2c0caf3bfd2b.png)
![4](https://user-images.githubusercontent.com/47444260/69352495-541f3c80-0c7d-11ea-8a13-546076724349.png)
![5](https://user-images.githubusercontent.com/47444260/69352497-541f3c80-0c7d-11ea-8b08-d19e0f604d8b.png)

But, only a few moments after I hit the finish button, it failed : 
![6](https://user-images.githubusercontent.com/47444260/69352498-54b7d300-0c7d-11ea-8018-3d8dc4a381b1.png)

However, I tried again and selected "Latest Release (2019-09)"  instead : 
![1](https://user-images.githubusercontent.com/47444260/69353106-49b17280-0c7e-11ea-8269-a9942038a13c.png)

This time the process ended without any error messages. But once the IDE was fully launched I had a lot errors. Here is what I have immediately after the end of the set up :
![6](https://user-images.githubusercontent.com/47444260/69353244-7c5b6b00-0c7e-11ea-86a3-bb80298939d0.png)

It seems that, most of the errors I get are due to missing packages : 
![7](https://user-images.githubusercontent.com/47444260/69353426-c3496080-0c7e-11ea-8221-9a90249415f7.png)

Here is an example of missing packages : 
![8](https://user-images.githubusercontent.com/47444260/69353667-25a26100-0c7f-11ea-9d72-60dd887877c8.png)

Several warnings tell me that some Plug-ins do not export all their packages : 
![9](https://user-images.githubusercontent.com/47444260/69353889-83cf4400-0c7f-11ea-98de-21a1a4060944.png)

Since that, I remain stuck. I tried several things such as reseting the target platform, exporting missing packages with "Deployable plugins and fragments" window, etc... . But nothing changed. What could I do to change that ? and is there anything I did wrong during the "Oomph-based setup" ?

**Comment by donat** [comment]
The Buildship IDE setup only supports the latest IDE version. Any particular reason why would you want to work with an old Eclipse version? 
I'll check out the compilation failures and get back to you.

**Comment by donat** [comment]
It was a slight error on our side. I've [fixed](https://github.com/eclipse/buildship/commit/059714303da01e7a659fd5c15eda2fdd6941f845) it. After updating your clone to the latest master the compilation errors should disappear.

**Comment by Rhamao** [comment]
Thank you for answering so quick. I just left my work. But I'll checked that back home. The reason why I want to work with Oxygen version, it's because my company use it.

**Comment by Rhamao** [comment]
Back home ! I tried it, it worked. There is no more errors. Thank you 👍.
![image](https://user-images.githubusercontent.com/47444260/69374327-20a4d800-0ca6-11ea-8027-aceb2b11d070.png)
