### ISSUE TITLE
JUnit Plug-In-Test with org.eclipse.buildship.core.test seems to be frozen

### ISSUE THREAD

**Issue by Rhamao** [eclipse/buildship#949]
Hi,

I tried to run this package org.eclipse.buildship.core.test as a JUnit Plug-In-Test. But the JUnit Plug-In-Test seems to be frozen at run  448/487. I did not modify any file. I wanted to see what would be the default result of this test. I have 3 failures and one error so far. As you can see below : 
![image](https://user-images.githubusercontent.com/47444260/69432072-40d1a700-0d39-11ea-8f44-b12021e528ad.png)
 
I stopped the test and began it again 2 times. I waited more than 15 minutes after reaching run 448/487. But it remained frozen. Should I wait longer ? Or is there something else I can do ?

PS: This is the first JUnit Plug-In-Test I run.

**Comment by donat** [comment]
Can you please check that the `Run in UI thread` option is disabled in the run config preferences?

**Comment by Rhamao** [comment]
Ok i'll check that.

**Comment by Rhamao** [comment]
I went to Run > Run configurations > JUnit Plug-In-Test. But couldn't find Preferences or Run in UI thread parameter.

**Comment by donat** [comment]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/419883/69433496-fc93d600-0d3b-11ea-868c-d0332cb69546.png">

**Comment by Rhamao** [comment]
Right. I should have scrolled down my window :/. Sorry. I found it. Disabled it. It was enabled by default. Should I run the test again now ?

**Comment by donat** [comment]
Yes, the tests should pass at this point.

**Comment by Rhamao** [comment]
Ok, thank you. I try that. I come back to you after.

**Comment by Rhamao** [comment]
This the result I have : 
There is 584/487 runs.  A message tells me that it's finished : 
![image](https://user-images.githubusercontent.com/47444260/69436396-91e59900-0d41-11ea-9e5f-cca0cd0f6f56.png)

Global view :
![image](https://user-images.githubusercontent.com/47444260/69436434-a1fd7880-0d41-11ea-8295-7be44cbde721.png)

Is it working properly ?

**Comment by Rhamao** [comment]
Once "Finished" is displayed, should I consider that the test was successful ? Nothing else needs to be check ?

**Comment by Rhamao** [comment]
I'm trying to know if some failures and errors can be tolerated, in order to consider the test succesfull. Or, if I need to have a test without any of them and a green bar. Since I want to modify this package, I would like to be able to identify a succesfull test.

**Comment by donat** [comment]
By default, all tests should pass. Could you please check if you see any failures from the command line? You can execute all tests with the `./gradlew eclipseTest` command. If that one works then something in your IDE is not configured properly.

**Comment by Rhamao** [comment]
Thx. I did so. Apparently I have a jdk/jre problem : 
![image](https://user-images.githubusercontent.com/47444260/69548653-01ed5c80-0f98-11ea-842a-bb030832817d.png)
I looked for "tools.jar", but I didn't anything ("Fichier introuvable" means "File not found") :
![image](https://user-images.githubusercontent.com/47444260/69549301-50e7c180-0f99-11ea-9314-52138629cf23.png)
Maybe I need an another jdk/jre.

**Comment by Rhamao** [comment]
I think, I found way a way to solve that. I come back to you after that.

**Comment by Rhamao** [comment]
Fix "Could not find tools.jar" **for windows 64 bits** : 

1. Make sure you downloaded jdk-1.8 or higher : "jdk-8u231-windows-x64" works, but you have to use an oracle account. However you can borrow someone else account. You won't be able to download the 64 bits version somewhere else. You can easily download the 32 bits versions without an oracle account, but you can't run Oomph setup with it. 
2. In environments variable, create : 

- new variable : JAVA_HOME : C:\Program Files\Java\jdk1.8.0_231
- new Path : C:\Program Files\Java\jdk1.8.0_231\bin

**Comment by Rhamao** [comment]
I ran again the command line gradlew eclipseTest, but it failed again : 
![image](https://user-images.githubusercontent.com/47444260/69621650-cd34e000-103f-11ea-8b6f-c0befb793c06.png)

**Comment by Rhamao** [comment]
This what I have if I run the the test with stacktrace : 
![image](https://user-images.githubusercontent.com/47444260/69622998-5a793400-1042-11ea-96a2-92a49954ecf0.png)

**Comment by Rhamao** [comment]
I am solving that. I come back to you after.

**Comment by Rhamao** [comment]
I thought my environnement variable to "git.exe" were wrong. But It's not the case. It seems that I have to run a bash command with Git Bash. I doesn't work using the windows command prompt.

**Comment by Rhamao** [comment]
All Right the eclipseTest finished. I think it worked. I had only once some "Caused by" messages. It starts with that  : 
![10](https://user-images.githubusercontent.com/47444260/69642099-8a83ff80-1061-11ea-84e0-5a09783e4a53.png)
Then I had a several "Caused by" in a row, here is the first of them : 
![11](https://user-images.githubusercontent.com/47444260/69642169-a5ef0a80-1061-11ea-849d-f8c518820eaf.png)

However the test finished and this the result I have : 
![12](https://user-images.githubusercontent.com/47444260/69642285-ce770480-1061-11ea-8931-38596da010b0.png)

Could you confirm me please if I have the expected result ?

**Comment by donat** [comment]
The stack traces are expected: some integration tests produce build failures without suppressing the error messages. If the `eclipseTest` task successfully finishes then everything is fine.

**Comment by Rhamao** [comment]
Good news. Thank you.

**Comment by Rhamao** [comment]
All right. I ran a last row of test. I ran separately every test as a JUnit Plug-in Test. They all ran without any errors or failures except : 

- org.eclipse.buildship.ui.test : 1 failure persists
![15coreTest](https://user-images.githubusercontent.com/47444260/69648643-0125fa80-106c-11ea-93db-557a5e23ab23.png)

It seems tolerable, is it ?

**Comment by donat** [comment]
Yes. In the meantime, I'll check the failing test.

**Comment by donat** [comment]
I vaguely remember fixing this. I'll close this issue to keep the board clean. Let me know if there's still a problem.

**Comment by Rhamao** [comment]
There is indeed no more problems. I should have closed the issue myself. Thank you for your awareness.
