### ISSUE TITLE
Source code lookup performance issue in multi-project configuration with exported entries

### ISSUE THREAD

**Issue by axls** [eclipse/buildship#950]
I had noticed a performance issue when trying to debug an application that uses buildship. There are 2-3 min delays between debugger stops at breakpoint  and displaying source code in editor's view on my configuration. The application is a multi-project web appllication with exported classpath entries in some projects. After debugging buildship plugin I found that `GradleClasspathContainerRuntimeClasspathEntryResolver`  generates classpath entries arrays with duplicates in some code pathes. In my case these arrays may contain about 800 000  entries (but unique is only ~200 entries). If I understand it correctly, travesing these arrays leads to delays I'm talking about.

I'm working on PR for the issue.

**Environment:**
Eclipse IDE for Eclipse Committers
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
OS: Linux, v.4.15.0-72-generic, x86_64 / gtk 3.22.30, WebKit 2.26.2
Java version: 1.8.0_222
Buildship: Eclipse Plug-ins for Gradle 3.1.0.v20190501-0832

**Comment by donat** [comment]
I'm checking your PR at the moment. It's not illegal to modify the exported flag on the library dependencies. Still, I'd like to understand why you need that. For each project, Buildship assigns the transitive dependencies to each project's classpath, so in theory, there's no need for that.

**Comment by axls** [comment]
@donat 
> Still, I'd like to understand why you need that.

I'm not sure exactly why this was needed, but perhaps this is a legacy from STS (Spring Tool Suite) gradle plugin (which one some of our developers are still using).

**Comment by donat** [comment]
Fixed in #951.
