### ISSUE TITLE
org.eclipse.core.runtime.CoreException: SynchronizingBuildScriptUpdateListener failed

### ISSUE THREAD

**Issue by chaitanyagits** [eclipse/buildship#954]
i am also facing org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Can't read root project location for project located ...

org.eclipse.core.runtime.CoreException: SynchronizingBuildScriptUpdateListener failed

I am using jdk 11 , Eclipse 4.13 and gradle buildship update site:http://download.eclipse.org/buildship/updates/e411/releases/3.x..

**Comment by donat** [comment]
The `.settings/org.eclipse.buildship.core.prefs` file might be missing. Buildship tries to determine the root project location but it does not find it. It is an illegal state. You can fix that by using the `Import Existing Gradle Project` wizard.
