### ISSUE TITLE
Does developing Buildship plug-ins for eclipse 2019-09 make them suitable for eclipse Oxygen ? 

### ISSUE THREAD

**Issue by Rhamao** [eclipse/buildship#956]
Hi,

I am currently working on Buildship plug-ins. As mentioned in issue #948 : 

> The Buildship IDE setup only supports the latest IDE version.

However even if I can develop this plug-ins with the latest IDE version, I still need to know if it will be suitable for eclipse `Oxygen.3a (4.7.3a)`, because this is the eclipse version used by my company. Does it need any kind of adpatation ?

**Comment by donat** [comment]
That statement might be misleading there. We only provide for the latest Eclipse version to automatically set up the development environment for Buildship via Oomph. Buildship supports Eclipse versions 4.7 and above. Here's our CI pipeline: https://builds.gradle.org/project.html?projectId=Tooling&tab=projectOverview

You can use the .target files from the project root to check against the older versions. Also, you can run the builds against an older Eclipse version with the following command (from the root of the project folder): 

   ./gradlew build -Peclipse.version=47

The build documentation is available here: https://github.com/eclipse/buildship/blob/master/docs/pluginbuild/Usage.md
