### ISSUE TITLE
Don't always use testCompile dependencies for generating .classpath

### ISSUE THREAD

**Issue by mnlipp** [eclipse/buildship#961]
As has been explained in #460, buildship uses the `testCompile` dependencies for generating the `.classpath`, which includes the `runtimeOnly` dependencies. The reason why `runtimeOnly` dependencies are added to the eclipse classpath is probably that automatically generated "Run as ..." configurations work "out of the box" (they are created with the project's eclipse classpath by default). While this is nice to have, it isn't always required.

When I have a library project, I need the `runtimeOnly` dependencies in gradle in order to get a proper maven pom.xml. However, I don't need them on the eclipse classpath, because I cannot "Run as ..." anyway. So not having the `runtimeOnly` dependencies in the eclipse classpath has no disadvantages. 

There should be some possibility to configure the set of dependencies used by buildship for generating the eclipse classpath. An implicit criterion may be the "java-library" plugin. If it is added to the project, it's obvious that "Run as ..." isn't expected to work. However, I'd prefer to have an explicit configuration option, because I don't always use the "java-library" plugin for library projects.

BTW, here's a small hack that I currently add to my library projects as a workaround:
```groovy
eclipse {
    classpath {
        file.whenMerged {
            configurations.runtimeOnly.allDependencies.each { dep ->
                if (dep instanceof org.gradle.api.artifacts.ProjectDependency) {
                    def depPrj = dep.dependencyProject
                    def depPrjPath = "/" + rootProject.relativePath(depPrj.file("."))
                    entries.removeAll { it.kind == 'src' && it.path == depPrjPath }
                }
            }
        }
    }
}
```

**Comment by oehme** [comment]
There already is such a capatbility using `eclipse.classpath.plusConfigurations`, which includes all (test-)compile and (test-)runtime dependencies by default, but can be customized to anything else.

**Comment by mnlipp** [comment]
I tried `eclipse.classpath.minusConfigurations += [ configurations.runtimeOnly ]`. Doesn't work, gives `Resolving configuration 'runtimeOnly' directly is not allowed`. (Gradle 5.4.1.)

**Comment by oehme** [comment]
That's because you need to use `runtimeClasspath`. Also, please don't use `minusConfigurations`, but remove `runtimeClasspath` from the `plusConfigurations` instead. Otherwise you might remove too many dependencies that are both on your compile and runtime classpath.

**Comment by mnlipp** [comment]
Thanks, but what do you mean by "remove `runtimeClasspath` from the `plusConfigurations`"? My understanding is that `plusConfigurations` is something that is *added* to the defaults. I haven't put anything into `plusConfigurations`, so how should I remove something?

I tried nevertheless, but `plusConfigurations -= [ configurations.runtimeClasspath ]` hasn't any effect at all (i.e. runtime dependencies are still added to the classpath).

**Comment by oehme** [comment]
You also need to remove the `testRuntimeClasspath`,  which is also added to the plusConfigurations by default.

**Comment by mnlipp** [comment]
This does the trick. Thanks!
