### ISSUE TITLE
Buildship sometimes generates incorrect runtime classpath when there are conflicting library versions

### ISSUE THREAD

**Issue by tomqwpl** [eclipse/buildship#966]
I'm using eclipse 2019-12, so Buildship 3.1.3.v20191118-1057

I have a simple gradle project that I have imported into eclipse.
I have a unit test that runs correctly when I run it from the gradle command line. The test passes, and the correct classpath gets used.

When I run the same unit test within eclipse, I get a NoSuchMethodError exception being thrown, because the classpath that's been generated is incorrect. There are two conflicting versions of a library in the transitive dependency tree, and buildship is generating the classpath such that the "wrong" one is used (I define "wrong" here as "not what the gradle command line does").

The library in question is apache commons lang3. I appear to need two projects to make the problem appear. The first project has a simple class in which I make a call to StringUtils.compare from apache commons lang. This method was only introduced in version 3.5 I believe. This project has a dependency on commons-lang3:3.9

A separate project contains my junit test. This has an artificial dependency on rest-assured:4.1.2. rest-assured:4.1.2 has a transitive dependency on apache commons lang version 3.4. This artificial dependency is here to expose the problem, this setup is my attempt to replicate the problem in a simple way. In reality of course this dependency on restassured would be required by the tests I'm running.

When the test is run in eclipse the class path has:

     restassured
     ...
     commons lang 3.4 (transitive dependency of rest assurred)
     ...
     commons lang 3.9 (explicit dependency of my project)

Gradle appears to resolve the classpath differently and detect that there are multiple versions of the same library and only use one.

There is a github project containing the code that I've been using here: https://github.com/tomqwpl/buildship-classpath-problem

I believe that if you import the project into eclipse using "import existing gradle project", then try and run "Class1Test" you'll get a NoSuchMethodError thrown. Running "gradle build" runs the test successfully.

**Comment by donat** [comment]
Hi! I've checked out the runtime classpath of the tests: both versions of commons-lang3 was added to the classpath with the older version being first. 

Eclipse has a restriction that allows only one classpath per-project. Because of that, Buildship assigns a merged classpath to each workspace project. You can influence the runtime classpath configuration with the `eclipse.classpath.(plus|minus)Configurations` DSL element. I've made your sample project work with the following snippet: 
```
eclipse {
  classpath {
    plusConfigurations = [ configurations.testRuntimeClasspath ]
    minusConfigurations += []
  }
}
```
