### ISSUE TITLE
Debugging in eclipse with multi-module

### ISSUE THREAD

**Issue by cilheo** [eclipse/buildship#967]
I try to used gradle in eclipse and doing some debugging but impossible to find something who work with my projet.

I have some projet :

'A' : contains my main class
'B' : contains some code
'C' who have 2 subproject (include in the settings file) : C1 and C2

Actually, 'A' have a dependency (on jar) on 'B' and 'C2'.

IncludeBuild on 'B' in the setting file of 'A' work. But includeBuild on 'C' in the setting file of 'A' doesn't work. Eclipse say that he found a cycle.

How (in this configuration of project) can i used eclipse for debugging (using the hot code replace functionality) ?

**Comment by donat** [comment]
Something seems fishy here. Your use-case should just work.

The Eclipse error report usually says which projects are in a cycle. I suspect there's a dependency back-edge from C1/C2 to B in a different dependency scope. 

In any case, if you don't find the problem yourself, please create a minimal example project exhibiting the problem, upload it here, and I'll take a look.
