### ISSUE TITLE
Buildship Only Offers Gradle Version 6.0

### ISSUE THREAD

**Issue by WonkoDaSane** [eclipse/buildship#968]
I am setting up a new PC, and have installed the Enterprise Java Dev version of Eclipse.

I'm now attempting to import some legacy libraries that require version 4.10.3, but the only option I'm given is version 6.0 (see attached).

This is for Eclipse Buildship version 3.1.3v20191117-2045

![Gradle v6](https://user-images.githubusercontent.com/28709230/73490081-c6955280-4379-11ea-8455-fa79e3297bba.png)

**Comment by donat** [comment]
Hi! When the Buildship plugin is initialized it tries to download the version information. If there's a connectivity issue, it falls back to display the current version (the used Gradle Tooling API module version, that is). You can still type the desired version to the textbox and it should work.
