### ISSUE TITLE
Project X is missing required Java project: Y

### ISSUE THREAD

**Issue by cdalexndr** [eclipse/buildship#971]
### Expected Behavior
No problem.

### Current Behavior
"Problems" window shows "Project 'server' is missing required Java project: 'web'"

### Context
Just imported a gradle project that works in other IDEs (Intellij, Netbeans), but doesn't work in Eclipse.
Trying to build the project results in error:
`The project cannot be built until build path errors are resolved	server		Unknown	Java`

### Steps to Reproduce 
I have a multi-project gradle configuration:
ROOT project with subprojects:
1. web
2. backend (contains common dependencies)
2.1. commons
2.2. server

root settings.gradle:
```
include 'backend'
include 'backend:server'
include 'backend:commons'
include 'web'
```
backend.gradle:
```
project("server") {
    dependencies {
    	runtimeOnly project(":web")
        implementation project("commons")
    }
}
```

**Comment by metaschell** [comment]
I have related issues, see #976. Does BuildShip also rename your projects (duplicate project name, i.e. `myproject` -> `myproject-myproject`) and/or replace all dependencies in `.classpath` with the Gradle classpath container without asking?

**Comment by cdalexndr** [comment]
@metaschell I've stopped using eclipse IDE due to unsupported gradle project

**Comment by donat** [comment]
@cdalexndr can you please provide a minimal sample project showing this problem?

**Comment by donat** [comment]
@metaschell It does. Buildship configures the project based on the build scripts, project name included.

**Comment by metaschell** [comment]
@donat my problem here is that BuildShip modifies already existing Eclipse project files, see #976 .
