### ISSUE TITLE
Gradle project settings get discarded after deactivating 'Override workspace settings'

### ISSUE THREAD

**Issue by kuzniarz** [eclipse/buildship#972]
### Expected Behavior
Deactivating `Override workspace settings` in the gradle project properties should only deactivate configured properties, but not change their values. 

### Current Behavior
Deactivating `Override workspace settings` and saving the properties leads to overwriting of the deactivated configuration with the global gradle properties.

### Context
When working with gradle project configurations it would be better when deactivating the override would not cause a loss of the previous configuration, so the user can switch between those configurations more easily.

### Steps to Reproduce 
1. Check your global gradle workspace settings in Eclipse (Window>Preferences>Gradle)
2. Open gradle properties in Eclipse (Right-Click on Project>Properties>Gradle)
3. Activate `Override workspace settings` and make a configuration that differs from the global settings + apply changes
4. Close and reopen properties to check if settings are saved
5. Deactivate `Override workspace settings` + apply changes
6. Close and reopen properties
7. The configured selection now matches the global gradle workspace settings

### Environment
Eclipse: Version: 2019-12 (4.14.0), Build id: 20191212-1212
Gradle: 6.2
Buildship: 3.1.3.v20191118-1057
OS: Windows 10 Pro (64bit)

**Comment by donat** [comment]
@kuzniarz I've created a PR for this feature and published a snapshot update site with the changes: https://download.eclipse.org/buildship/updates/e416/snapshots/3.x/3.1.5.v20210204-2312-s/ 
Can you please install it and test if it works as you'd expect?

**Comment by kuzniarz** [comment]
Yes, will do!

**Comment by kuzniarz** [comment]
@donat Okay, so I did some testing, and seems to work exactly how I expected!

**Comment by donat** [comment]
I'll soon merge the changes to master. I trust you'll use the latest snapshot version and report any weird behavior.
