### ISSUE TITLE
Buildship doesn't forward command line options like "--settings-file" for included builds.

### ISSUE THREAD

**Issue by ams-tschoening** [eclipse/buildship#973]
### Expected Behavior

If additional program arguments for executing Gradle in Eclipse have been configured, those should be used for included builds as well.

![Clipboard01](https://user-images.githubusercontent.com/6223655/75374843-46f19980-58cd-11ea-8b4a-74e23340425e.png)

### Current Behavior

The first executed build uses additional program arguments like expected, but at some point it gets lost for included builds.

### Context

I was trying to [work around some limitations](https://discuss.gradle.org/t/how-to-make-buildship-use-a-specific-settings-gradle-instead-of-the-default-one/35061) of Buildship using two different settings files, `settings.gradle` and `settings_buildship.gradle`. The latter got configured in Eclipse only and contains additional statements needed to make Buildship better support composite builds. Those shouldn't be necessary in general and aren't outside of Buildship, therefore I wanted to manage those in two different files to make both files easier to maintain.

The first `settings_buildship.gradle` for the concrete project I execute tasks for using Buildship is used. But [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) shows that for all included builds `settings.gradle` is used.

    19:42:59,9047672	java.exe	10052	ReadFile	C:\Users\tschoening\Downloads\ghi\de.am_soft.sm_mtg.api\settings_buildship.gradle	SUCCESS	Offset: 0, Length: 247, Priority: Normal
    19:42:59,9218030	java.exe	10052	ReadFile	C:\Users\tschoening\Downloads\ghi\de.am_soft.sm_mtg.parser.ks\settings.gradle	SUCCESS	Offset: 0, Length: 49, Priority: Normal

The command line used to actually read the files looks the same in both cases:

    "C:\Program Files\Java\jdk-8\bin\java.exe" -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=DE -Duser.language=de -Duser.variant -cp C:\Users\tschoening\.gradle\wrapper\dists\gradle-6.2.1-all\4vp27twfwktff74t6xt7byg0o\gradle-6.2.1\lib\gradle-launcher-6.2.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.2.1

### Steps to Reproduce 

    gradlew build --settings-file=settings_buildship.gradle

[ghi.zip](https://github.com/eclipse/buildship/files/4257587/ghi.zip)

### Your Environment

Gradle 6.2.1, Buildship 3.1.3

As this happens with [Gradle itself ](https://github.com/gradle/gradle/issues/12356) on the shell as well, I created a bug for that, too.

**Comment by donat** [comment]
A composite build is technically one Gradle build. There's nothing to pass to included builds. It is a limitation of Gradle that you can specify a settings file for the root build only which should be fixed in Gradle itself, if anywhere.

You should not have different settings file. If you need to distinguish between IDE and command line usages, just do an if-else statement in the settings file based on a system property. For example you can check for `eclipse.launcher`.
