### ISSUE TITLE
Show line and column number in bottom of editor

### ISSUE THREAD

**Issue by kec2** [eclipse/buildship#974]
I would like to have the line number and column number in the bottom of the Eclipse Gradle editor.
In general standard information are missing. writable? insert/override, line/column number.

**Comment by donat** [comment]
It's there: 

<img width="1250" alt="Screenshot 2020-03-19 at 16 37 47" src="https://user-images.githubusercontent.com/419883/77085134-3336e000-6a00-11ea-8465-404f2a094e95.png">

**Comment by kec2** [comment]
I see something different.
![gradle_editor](https://user-images.githubusercontent.com/3109622/77163484-764f8c80-6aae-11ea-83fd-e65780318f5b.jpg)

My Eclipse is 2019-12, on Windows 10.

**Comment by donat** [comment]
This seems like a platform error. Judging from the screenshot you have other plugins installed that mask the line number indicator on the bottom.

**Comment by kec2** [comment]
I don't think so. There is no problem in the java editor.

Hilsen
Klaus Christiansen

________________________________
