### ISSUE TITLE
BuildShip overwrites my (generated) Eclipse project files

### ISSUE THREAD

**Issue by metaschell** [eclipse/buildship#976]
### Expected Behavior
I generate my Eclipse project files for a multi-build project using `./gradlew cleanEclipse eclipse` and BuildShip should leave them alone, i.e. not touch or change them (without asking me).

### Current Behavior
BuildShip is renaming some Eclipse projects from `myproject` to `myproject-myproject` which breaks dependencies between projects, e.g. `Project X is missing required Java project: Y`. Also see #971 for similar/related issues.
BuildShip also changes the generated `.classpath` and replaces the resolved dependencies listed therein with a Eclipse classpath container and resolve those dependencies internally.

Maybe doing this through BuildShip is a better way, but right now I would prefer to continue with my long-practised steps and workflow. Specifically, BuildShip should ask me before silently doing that and/or offer an option to disable this behavior. 

### Context
We create our Eclipse project files explicitly using the Gradle Eclipse plugins (as opposed to importing them via BuildShip). 

`./gradlew cleanEclipse eclipse` generates all `.project` and `.classpath` files and we also have customized some settings e.g. naming the Eclipse project for `:project1:core` as `project1-core` and `:project2:core` as `project2-core` and similar adjustments.

Then we import those projects into Eclipse using `Import... -> General -> Existing projects into workspace`. 

This is likely caused by the Gradle project nature and/or builder added to the `.project` files.

### Steps to Reproduce 
See steps in #971

### Your Environment
```
------------------------------------------------------------
Gradle 6.2.1
------------------------------------------------------------

Build time:   2020-02-24 20:24:10 UTC
Revision:     aacbcb7e587faa6a8e7851751a76183b6187b164

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)
OS:           Mac OS X 10.15.3 x86_64
```

```
Eclipse IDE for Enterprise Java Developers.

Version: 2019-12 (4.14.0)
Build id: 20191212-1212
Eclipse Buildship	Buildship, Eclipse Plug-ins for Gradle	3.1.3.v20191118-1057	org.eclipse.buildship
```

**Comment by donat** [comment]
I'm afraid this is not possible. You should _not_ use the `eclipse` task in conjunction with Buildship. Buildship simply overrides the `.project` and `.classpath` generated by the `eclipse` task, at least for the elements that can be configured in the build script. 

There are several ways to influence the `.classpath` file. You'll find examples [here](https://discuss.gradle.org/t/buildship-1-0-18-is-now-available/19012).

Regarding the project name, you can configure what names Buildship will use by configuring the `eclipse.project.name`. It might be deduplicated if there's a name overlap within your build or if the workspace already contains a project with the same name.

**Comment by metaschell** [comment]
My problem is that I was not actively using BuildShip but rather imported existing Eclipse projects into my workspace. As I was using the _Eclipse of JEE Developers_ (which happens to contain BuildShip) this left my workspace screwed up. 

The renaming of the Eclipse projects was not problematic per se, but because it was different to the (already established) dependencies this led to unresolved project references and hence to build errors.

This used to work with the same version of Eclipse and BuildShip maybe up to Gradle 6.0 or 6.1, only then it started to fail, maybe because only then the project files generated by the Gralde Eclipse plugin started to get the BuildShip project nature and/or builder? I searched the Gradle release notes but couldn't find any related entries...

**Comment by donat** [comment]
That's weird, I also don't recall adding the Buildship natures/builders to the `eclipse` Gradle plugin. I've checked the latest Gradle codebase and it's not present. Maybe you have it somewhere in your build scripts?

**Comment by metaschell** [comment]
No, the only Eclipse-related configuration in our `build.gradle` files are setting a specific project name and adding or removing stuff from the classpath. Nothing regarding natures or builders.

Maybe BuildShip does assume that all projects with `build.gradle` files were imported through it and adjusts the project configuration accordingly?

I now used BuildShip to import my project and all is fine on that front. But I still think BuildShip should not touch existing project files, independently of whether they were generated by Gradle outside of BuildShip or using some other means...

**Comment by donat** [comment]
That's not how it works. We built Buildship on the "build scripts are the single source of truth" principle. We configure everything in Eclipse that can be configured in the Gradle DSL. I understand it can be inconvenient at times. On the other hand, it's more robust, which is appreciated by our users.

**Comment by metaschell** [comment]
For project imported through BuildShip I fully agree. 

Just for any "random" project happening to live in the same workspace with BuildScript being installed in the Eclipse version I used to work on my projects, I'd rather have that it wouldn't touch those other projects. Until now I have never actively used BuildShip, it rather forced itself on me...

I only used BuildShip now to circumvent this issue (and am happy enough with the results, so don't get me wrong on this), it just shouldn't have touched those projects in the first place without asking me or giving me an option to opt out...

**Comment by metaschell** [comment]
Anyway, fell free to keep this issue closed, but it may serve as documentation if others stumble upon the same problem...
