### ISSUE TITLE
sourceCompatibility/targetCompatibility in compileJava block are ignored

### ISSUE THREAD

**Issue by fbricon** [eclipse/buildship#978]
Using Eclipse 2020-03, in Buildship preferences, java.home is set to use Java 13. Try opening a project with this simple build.gradle file:
```groovy
apply plugin: 'java'

compileJava {
   sourceCompatibility = 11
   targetCompatibility = 11
}
```

### Expected Behavior
The JRE in .classpath should be set to JavaSE-11

### Current Behavior
The JRE in .classpath is set to JavaSE-13, ignores build.gradle configuration:

<img width="1104" alt="Screen Shot 2020-03-23 at 1 34 26 PM" src="https://user-images.githubusercontent.com/148698/77317585-c37c6a00-6d0b-11ea-8c10-f41b42567663.png">

### Context
I was trying to check Java 14 compatibility with Gradle projects in [vscode-java](https://github.com/redhat-developer/vscode-java/issues/1338) when I noticed that weird behavior with the OP's sample project, that can be reproduced without Java 14.

### Steps to Reproduce 
Import https://github.com/fbricon/dummy-java as a Gradle project

### Your Environment
Eclipse 2020-03 - Java distro + Java 14 patch
Buildship 3.1.3.v20191118-1057

**Comment by donat** [comment]
Does it work if you specify the java version outside of the `JavaCompile` task configuration?
```gradle
plugins {
  id 'java-library'
}

sourceCompatibility = 11
targetCompatibility = 11
```

**Comment by fbricon** [comment]
Yes it works

**Comment by donat** [comment]
I've looked at Gradle the source code for the Eclipse model builders. The source and target versions are set via the `eclipse.jdt.sourceCompatibility`  and `eclipse.jdt.targeteCompatibility` which is unrelated to the `JavaCompile` configuration. I'd close this as a non-issue, although I do know that this confusing for the users.

**Comment by fbricon** [comment]
I'm not a Gradle user, so I don't personally care. But I think that's a mistake. I believe the Eclipse builder should fallback to inferring sourceCompatibility and targetCompatibility values from other standard Gradle places, when possible. Whether it's a buildship issue or an upstream Gradle issue, I'll let you decide.
