### ISSUE TITLE
buildship is creating classpath-arg and it's not working

### ISSUE THREAD

**Issue by glitch-k8s** [eclipse/buildship#982]
Hello builship team,

Using buildship 3.1.4 in my Spring boot & Spark gradle project. I am using Java 11.

buildship is creating command line java command line "<path of java>\javaw.exe -Dfile.encoding=Cp1252 "@D:\new_workspace\sparkSample\.temp-SparkApplication-classpath-arg-1586500484248.txt" org.helloworld.spark.SparkApplication"

Above command is not working.
I think its a compatibility issue between eclipse version and buildship. I downgraded my STS version to 4.2.2 and it started working.

If I reduce dependencies, than it doesnt creates classpath argument file and all works.
So, please help in configuring builship, so it doesnt creates argument file.

Regards,

**Comment by donat** [comment]
Seems like it is an STS issue. Let me know if I should investigate further on the Buildship side.
