### ISSUE TITLE
import eclipse options from gradle eclipse plugin

### ISSUE THREAD

**Issue by deanorderly** [eclipse/buildship#995]
Most teams need to roll out project settings into the teams IDE (twitter literally distributes their own Intellij now to all developers to modify all their settings).

We would like it so when someone creates a webpieces projects(we generate a build.gradle on creation), we want to check the checkbox for the project so we compile with -parameters on the JVM every time a program is launched.

I am sure there are many other options as well and it would be nice to set the teams formatter to match our build system, etc. etc.

**Comment by donat** [comment]
This is possible with Eclipse right now. You could use tools to configure Eclipse to your liking. There are several tools out there you can try:
- Eclipse Workspace Mechanic (archived): https://code.google.com/archive/a/eclipselabs.org/p/workspacemechanic/wikis/PreferenceRecorder.wiki
- Eclipse Oomph: https://projects.eclipse.org/projects/tools.oomph
- Genuitec SDC (commercial): https://www.genuitec.com/products/sdc/

You can configure the workspace default Buildship. For example, the preference key for the jvm arguments is `jvm.arguments` (configured on the `org.eclipse.buildship.core` plugin). You can get all configuration options and their current values in the `About Eclipse` dialog:

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/419883/106462870-eda7c800-6496-11eb-86d7-5d2007fdb39e.png">
