### ISSUE TITLE
Attach unresolved dependency marker to build file instead of project

### ISSUE THREAD

**Issue by fbricon** [eclipse/buildship#999]
I tried to use the latest Buildship Snapshot in jdt.ls, following https://github.com/eclipse/buildship/pull/994#issuecomment-645321645. It kinda works, but the marker is attached to the project, instead of the build.gradle file. And vscode really doesn't like it:

<img width="891" alt="Screen Shot 2020-06-17 at 7 06 13 PM" src="https://user-images.githubusercontent.com/148698/84927815-aae2dc80-b0cd-11ea-84c9-f0f47bd3601d.png">

I'd like to avoid adding more hacks to jdt.ls, so it'd be really helpful if such errors were attached to the build descriptor instead of the project.

**Comment by fbricon** [comment]
Also, is there any chance the missing dependency error range can accurately pinpoint to the actual dependency reference position in the file, not just 1:1?

**Comment by leonardobsjr** [comment]
When working on #994 i actually tried to work on pinpointing the problematic dependency in the file. However, i found that the error markers that had line indication were derived from gradle stacktraces, which isn't the case of these errors since they're buildship created.

**Comment by donat** [comment]
I've created a PR (#1000) to move the error markers to the build script if possible. Also, it tries to find the dependency in the build script to properly set the error marker line number property. If you have time please do a review on it. I'll also request an internal review and proceed accordingly.
